### ISSUE TITLE
Problem plotting dive planner points when gas partial pressure graph is enabled

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#1070]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Within the dive planner, take the default dive plan when the planner is activated. There is only one dive planner point indicated, at 15m and 20 min. Activate or deactivate the O2 partial pressure graph. Because of the PO2 graph, the vertical space available for the dive profile decreases and the profile now has to fit in less vertical space. This works ok. However, the dive planner point (or points) is not re-plotted with the rest of the profile. The result is that the white dive planner point hangs separately from the dive profile graph, usually in the area meant for the PO2 graph.

### Operating system:

Ubuntu 16.04

### Subsurface version:
 4.7.6-125 up to 4.7.6-139

test build

g18c54301

### Expected behavior:

The dive planner point(s) should re-plot with the dive plan profile.

### Mentions:

@atdotde

**Comment by janmulder** [comment]
Interestingly, I can not reproduce this. The waypoint stays attached to the profile when switching bottom stuff (like the po2 graph) on and off.

**Comment by willemferguson** [comment]
I can repeat this bug in Fedora as well. Do it as follows:
1) Create a deco dive, say to 50m.
2) Switch on the display of the dive ceiling (topmost profile tool button). Dive planner points move as they should when the O2 graph is switched on and off.
3) Switch off the display of dive ceiling.
4) Now repeat the process of switching the O2 graph on and off.
5) The dive planner points are left behind as originally described. See attached image.
![dive planner points](https://user-images.githubusercontent.com/5078706/35455575-165940d8-02db-11e8-9ea8-a06373bec329.jpg)
