### ISSUE TITLE
Planner: Cylinder pressure plot is destroyed by clicking on the dive plan profile

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#1071]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Open the dive planner. The default dive (20 min at 15m) is shown. The cylinder pressure graph (air) runs from 207 bar to around 115 bar. Click on the dive plan profile. The cylinder pressure graph is destroyed.

### Operating system:

Ubuntu 16.04

### Subsurface version:

4.7.6-125 up to 4.7.6-139

Built

g18c54301

### Expected behavior:

The cylinder pressure should not respond to a click on the dive profile. See attached image.
![diveplan1](https://user-images.githubusercontent.com/5078706/35292903-a74046e0-007a-11e8-845a-355047bbf438.jpg)

### Mentions:

@atdotde

**Comment by janmulder** [comment]
Also here, can't reproduce to the letter of this issue. I always have corrupt cylinder pressure lines as shown in the picture above. So, without clinking in it.

And as a side note. Mentioned 4.7.6-139 does not exist yet ... and when you write 
> 4.7.6-125 up to 4.7.6-139

it looks like you have bisected something ...
