### ISSUE TITLE
Reverse geo lookup icon not there

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#1079]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Reverse geo lookup icon (the small satellite) disappeared:

![grafik](https://user-images.githubusercontent.com/25316050/35471168-1840b05e-0356-11e8-9d39-8ae78b2b85c5.png)

Can anyone confirm this?

### Operating system:

Windows 10

### Subsurface version:

Latest master

**Comment by janmulder** [comment]
Yes, can confirm on current master on Linux. Icon is not shown. And I think I saw this already when I fixed a crash in this area (in commit 435181aa19a4f).

**Comment by dirkhh** [comment]
Can you bisect this and find out when it disappeared? A quick check here with 4.7.3 on Mac shows that the icon is there... but I don't think I'll be at the computer for enough time today to figure out when it disappeared (I need to head back to bed and rest)

**Comment by sfuchs79** [comment]
Waah, bisecting still sucks on my slow machine. 3 children - was not able to afford the Ryzen I wanted to buy for Christmas. DDR4 memory too f**cking expensive at the moment.
But found a better approach: Drink half a bottle of nice Italian red wine, look at the code... and fix it. Yeah, it was not too difficult ;-)
Will submit a PR...

**Comment by dirkhh** [comment]
You will forgive me for worrying about code after half a bottle of red wine (or while recovering from the flu - which is why I am not writing code right now and am hesitating to do in depth code reviews) ;-)

**Comment by dirkhh** [comment]
Oh, and bisecting Subsurface is slow, even on blazing fast systems...
