### ISSUE TITLE
Move friendly name before UUID in Subsurface-mobile on DC synchronisation page 

### ISSUE THREAD

**Issue by arosl** [subsurface/subsurface#1123]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When using the iOS version of Subsurface-mobile on an iPhone the friendly name (Perdix) is not visible in portrait orientation on an iPhone 7. Moving the "friendly name" in front of the UUID would increase the usability of the app on small screens. 

Workaround is to use the iPhone in landscape mode.

### Operating system:

iOS 11.2.5 (English US, with Norwegian time and date localisation)

Iphone 7

### Subsurface version:

Subsurface-mobile 2.0(4.7.4.280)

Official release from App Store.

### Steps to reproduce:

1. Try to sync an Perdix in portrait mode on an iPhone 7.

**Comment by atdotde** [comment]
Hmm, I thought I had already implemented that in 1c223b09c3

**Comment by janmulder** [comment]
Yes, implemented but not in the respective app store versions (yet), as we are behind with that.

**Comment by janiversen** [comment]
@janmulder When do we close a bug ?

I got confused by this one looking for outstanding iOS bugs, it is implemented and have been available in several test flight versions. Other issues are closed as soon as the fix is merged on master.

**Comment by dirkhh** [comment]
I typically close bugs once they are in master.
I am unusually late with releasing new apps - I hope to get the new v2.1 out within a week (FINALLY)
