### ISSUE TITLE
Changes to XSLT when exporting dives as *.CSV

### ISSUE THREAD

**Issue by p-neves** [subsurface/subsurface#1157]
### Describe the issue:

- [ ] Bug
- X  Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Can we have the following changes to the XSLT when exporting dives as *.CSV?
     - remove “min” from the Duration field (add to header)
     - remove “%” from O2 and He (add to header)
     - split GPS field in 2 separate fields: LAT & LONG
This would make it easier when using data with external apps (e.g. R)

### Operating system:

Arch Linux

### Subsurface version:

4.7.7

Self compiled

4.7.7-110-gcdba35530ba5

**Comment by sfuchs79** [comment]
For duration and O2/He I think your proposal would be the correct thing to do. I can look into this. Not sure yet about the GPS location but will check this as well...
