### ISSUE TITLE
Changes to XSLT when exporting dive profile as *.CSV

### ISSUE THREAD

**Issue by p-neves** [subsurface/subsurface#1158]
### Describe the issue:

- [ ] Bug
- [X ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I'd like the following changes to the XSLT for when exporting a dive profile as *.CSV:
    - Export heart rate (create new field - e.g. "sample.heartrate")
    - Use the same decimal separator for all fields (now. “sample.depth” uses “,” and “sample.temperature” uses “.” as separators)

### Operating system:

Arch Linux

### Subsurface version:

4.7.7

Self compiled

4.7.7-110-gcdba35530ba5

**Comment by sfuchs79** [comment]
> - Use the same decimal separator for all fields (now. “sample.depth” uses “,” and “sample.temperature” uses “.” as separators)

That worries me and I can't reproduce it immediately. Which unit system did you use? Metric or imperial?

**Comment by sfuchs79** [comment]
@p-neves 
Could you please test #1159 
Only quickly tested on my side. For the heartrate I have no test data at all.

I still can't explain the decimal separator issue and this still worries me...
