### ISSUE TITLE
Not possible to edit dive information from dive list.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1213]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When viewing "dive all" it is possible to edit most of the fields for an uploaded dive, which is nice.
When viewing "dive list" and trying to edit a dive an error dialog box occurs, this is inconsistent behaviour.

### Operating system:

macOSX 10.13.4

Mac

### Subsurface version:

4.7.8

Official release

### Steps to reproduce:

1) select "view"/"all"
2) Edit e.g. buddy, it works
<img width="1762" alt="screen shot 2018-04-22 at 10 55 50" src="https://user-images.githubusercontent.com/6185391/39093234-5d1bffea-461c-11e8-9b1f-924dca129ad4.png">

3) select "view"/"dive list",
4) choose an uploaded dive (NOT manually entered)
5) select "log"/"edit dive"
6) you get an error dialog box
<img width="1720" alt="screen shot 2018-04-22 at 10 56 51" src="https://user-images.githubusercontent.com/6185391/39093255-9566922a-461c-11e8-948a-880e9a55fdd1.png">

### Current behavior:

Error dialog box

### Expected behavior:

Change to "all" screen"

**Comment by dirkhh** [comment]
I see your concern, but I will file this under "Works as Designed". The dive list is designed to be read only.

**Comment by janiversen** [comment]
No problem, but then "edit dive" should not be selectable in the menu :-)

**Comment by dirkhh** [comment]
True - we should gray that out in this mode. Reopening the issue...

**Comment by bstoeger** [comment]
I tried to enable "Edit dive" for all dives: https://github.com/bstoeger/subsurface/tree/edit and removed a few lines of code-duplication while at it.
The thing is ... this puts the application in edit mode, but apart from that is pretty much a no-op.

Therefore another idea: Say "Edit dive profile" instead of "Edit dive" and enable only if a single, planned or manually entered dive is selected?

**Comment by janiversen** [comment]
Sent from my iPad

> On 3 May 2018, at 16:58, bstoeger <notifications@github.com> wrote:
> 
> I tried to enable "Edit dive" for all dives: https://github.com/bstoeger/subsurface/tree/edit and removed a few lines of code-duplication while at it.
> The thing is ... this puts the application in edit mode, but apart from that is pretty much a no-op.
> 
> Therefore another idea: Say "Edit dive profile" instead of "Edit dive" and enable only if a single, planned or manually entered dive is selected?
> 
Seems I missed something because you also need (at least some fields) to edit a downloaded dive, so why not keep “Edit dive” and allow edit all (planned etc) or limited ?

rgds
jan i

**Comment by bstoeger** [comment]
The thing is that for downloaded dives "Edit dive" is a no-op. You can start filling out the fields at any time anyway.

**Comment by janiversen** [comment]
Sent from my iPad

> On 3 May 2018, at 17:12, bstoeger <notifications@github.com> wrote:
> 
> The thing is that for downloaded dives "Edit dive" is a no-op. You can start filling out the fields at any time anyway.
> 
I agree editing the downloaded data is a no-go, but “edit-dive” could open for all editing (planned... dives), and open the extra fields if it is a downloaded dive. Both operations are “edit dive” seen from a user perspective.

rgds
jan i

**Comment by bstoeger** [comment]
Perhaps #1236 works for you. But this will need some discussion.

**Comment by atdotde** [comment]
Hi,

> On 3. May 2018, at 17:12, bstoeger <notifications@github.com> wrote:
> 
> The thing is that for downloaded dives "Edit dive" is a no-op. You can start filling out the fields at any time anyway.
> 
> 

„Edit dive in planner“ does work for downloaded dives and might be more what you are looking for.

Robert

**Comment by bstoeger** [comment]
If I understand the bug report correctly, editing the profile is *not* the point.

The perceived problem is that "Edit dive" gives an error message instead of doing what it says: editing the dive. I don't really have an opinion what to do in this case.

**Comment by bstoeger** [comment]
@janiversen: Can you please check if #1236 works for you?

**Comment by janiversen** [comment]
Done, works, see detail in PR. Nice job.

**Comment by janiversen** [comment]
solved with #1245, thanks.
