### ISSUE TITLE
Website /documentation/building are similar to INSTALL file, but not identical

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1215]
### Describe the issue:

- [ ] Bug
- [x ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

It is confusing that https://subsurface-divelog.org/documentation/building/ are slightly 
different from https://github.com/Subsurface-divelog/subsurface/blob/master/INSTALL.

Since INSTALL is easily changed to MarkDown format, it could be used directly when generating the 
WebSite and thus remove any confusion.

### Operating system:

Website

### Steps to reproduce:

Compare INSTALL and website

**Comment by dirkhh** [comment]
Agreed. And worse, the translated versions are out of sync. I am considering just dropping this from the website and pointing people to the INSTALL file instead.
Extremely few of our users are building from source (maybe 1% if that)

**Comment by janiversen** [comment]
That is in accordance with my preference, lets drop it !! you do not even need a pointer to INSTALL, developers know where to look (or they are not developers who can actually get work done).

**Comment by dirkhh** [comment]
Done. It's gone from the website
