### ISSUE TITLE
"All" formats time wrong using am/pm while dive list uses 24hour.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1234]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Look at the screenshot, Dive 23 has time "20:30" (which is the correct formatting) while time field has "8:30 PM" (does not use locale setting on Mac)

### Operating system:

macOS

### Subsurface version:

4.7.8

master

### Steps to reproduce:

Select a night dive

### Current behavior:

am/pm for editing, and 24hour for showing.

### Expected behavior:

24hour for  both editing and showing BECAUSE locale is set to 24hour
am/pm for  both editing and showing IF locale is set to 12hour

### Additional information:

<img width="1693" alt="screen shot 2018-05-03 at 18 20 47" src="https://user-images.githubusercontent.com/6185391/39589640-1317b8b2-4eff-11e8-92f3-427cd2dc36bc.png">

**Comment by dirkhh** [comment]
I can confirm this as a bug.
