### ISSUE TITLE
Tags and Many other fields are not displayed on iOS

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1235]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I understand the intention is to keep the UI identical across all platforms, and that is the reason for not using e.g. iOS special features (like deleting a dive).

However in iOS e.g. Tags is not displayed.

### Operating system:

iOS 11

### Subsurface version:

2.0.1

Official

### Steps to reproduce:

1) open "all" on a Mac and view a dive on an iPad
2) see the difference

### Current behavior:

Missing display of fields

### Expected behavior:

Display the same fields and use tabs as on the Mac.

**Comment by dirkhh** [comment]
Actually, the intention is NOT to keep the UI the same. Subsurface-mobile has a distinctly more restrictive UI to deal with the typically much smaller screen size.
As I said in #1232 I am open to more flexibility based on screen size, so if you want to work on that, I'd love to see that. But for now I'd call this "works as designed" as well.

**Comment by janiversen** [comment]
I am trying to get up to speed with Mac/ios development, but I do find the build process is not what I am used to :-) I filed a question on the ML whether it would be acceptable to add a Xcode project, so you can generate all Mac/ios variants easily

**Comment by atdotde** [comment]
Jan,

> On 4. May 2018, at 08:10, jan iversen <notifications@github.com> wrote:
> 
> I am trying to get up to speed with Mac/ios development, but I do find the build process is not what I am used to :-) I filed a question on the ML whether it would be acceptable to add a Xcode project, so you can generate all Mac/ios variants easily
> 
> 

parti of the existing process is creating an Xcode project (file).

Robert

**Comment by dirkhh** [comment]
I'll respond on the ML - I have concerns about this.
