### ISSUE TITLE
iOS: icons problems

### ISSUE THREAD

**Issue by mfbernardes** [subsurface/subsurface#1267]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

1. Some icons are not being displayed even with the correct source path.
    Delete on list:
  ![img_4175](https://user-images.githubusercontent.com/30494/39968146-d4bcb8f2-56c8-11e8-99f3-b0fd8c44386d.jpg)
    GPS fixes list:   
 ![img_4191 2](https://user-images.githubusercontent.com/30494/40301216-b39b5fec-5ceb-11e8-8518-4b97bd74b3dc.jpg)

1. The application header back button is misaligned:
With PR#1266 applied 
![img_4172](https://user-images.githubusercontent.com/30494/39968148-d4f50c34-56c8-11e8-882b-701f48c73839.jpg)

I investigated and tried to fix but could not find a solution, so reporting to keep track.

### Operating system:

iOS

**Comment by janiversen** [comment]
I do not see this on my ipad with latest master, and on my iphone with 2.0.1 release.

I do not have a < on any of those intead I have “Dive list > Settings”.

wonder if get to the window differently or your phone have special geometry.

**Comment by mfbernardes** [comment]
The < icon is supposed to appear on each Back button on the Global Drawer, i.e in Dive management or GPS.

I see these on iPhone 7 Plus and simulator (iPhone X).

The missing icons happen at least since last flight test release.

**Comment by janiversen** [comment]
See #1307 for titleIcon testing done.

**Comment by mfbernardes** [comment]
Added image for GPS fixes list, same problem of invisible icon.
