### ISSUE TITLE
linux: crash when deleting dive computers

### ISSUE THREAD

**Issue by neolit123** [subsurface/subsurface#1278]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

A user reported at the user forum:

> This is not a critical issue, but when clearing out some old backup dive computers from my device list, I get a segfault straight after confirming deletion. I'm using subsurface 4.7.8 on Mint Linux 18.3. Problem doesn't appear on my Win10 laptop.

### Operating system:

Linux Mint

### Subsurface version:

Subsurface from PPA 4.7.8.

### Current behavior:

crash when deleting DC.

### Expected behavior:

no crash.

### Additional information:

stack trace:
https://pastebin.com/712Gvaax

the crash seems to happen somwhere in:
https://github.com/Subsurface-divelog/subsurface/blob/master/qt-models/divecomputermodel.cpp

**Comment by bstoeger** [comment]
Could they perhaps check current master? The `DiveComputerModel` was refactored in #1386.

**Comment by neolit123** [comment]
cannot be reproduced on Linux with latest master.
