### ISSUE TITLE
mobile: logo shows as black spot in testFlight and master

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1307]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When starting testFlight, master or mobile on desktop, the titleIcon shows as a black spot
<img width="429" alt="captura de pantalla 2018-05-21 a las 11 19 57" src="https://user-images.githubusercontent.com/6185391/40300241-fb9077ae-5ce8-11e8-8506-cbbf37763ad1.png">

First reported on our ML, by John Smith.

Tested: 
- location of png file is correct, choose another file with same problem
- remove banner has no effect
- build a version on a commit just after Kirigami upgrade, same problem

It seems to be a Kirigami 2.4 problem.

### Operating system:

iOS and high Sierra

### Subsurface version:

testFlight, master

Yes

### Steps to reproduce:

1) Start Subsurface-mobile and watch.

### Current behavior:

Logo replaced by black spot

### Expected behavior:

Show log as in release version.

**Comment by mfbernardes** [comment]
Same as #1267

**Comment by janiversen** [comment]
Correct sorry overlooked that, will put a note in #1267 about the test.
