### ISSUE TITLE
Confused about SAC rate answer

### ISSUE THREAD

**Issue by Brett-Howard** [subsurface/subsurface#1311]
### Describe the issue:

- [x] Bug?
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I've recently gotten a Perdix AI and imported my first dive and the SAC value doesn't match that of what I've seen from another application that I imported the same dive to...  Based on the start and end pressure numbers from the equipment tab I get this calculation:  3130-1648 = 1482 PSI consumed; 1482/25minutes = 59.28PSI/min; Average Depth = 2ATA So 59.28/2 = 29.64PSI/min@1ATA; Working pressure = 3442PSI; 100/3442 = .02905 * 29.64 = 0.861cuft/min. 

This value matches the result returned by the other application.  Yet Subsurface returns 0.77cuft/min.

Also I find it strange that the starting and ending pressures in the graph are 3156 and 1644 as opposed to the 3130-1648 shown in the equipment tab.  

### Operating system:

MacOS 10.13

Apple MBP

Yes, shows same value in Linux, Windows, Android and MacOS.

### Subsurface version:

4.7.8

### Current behavior:

0.77cuft/min

### Expected behavior:

0.86cuft/min

**Comment by mturkia** [comment]
Subsurface takes gas compressibility into account. Take a look at Linus' answer in following discussion:

https://groups.google.com/forum/#!topic/subsurface-divelog/uu_TWvU810U

The difference in start and end pressure in the graph and equipment tab seems to be imperial units only thing. So it must be a bug in conversion from metric to imperial in one of these places. (In Subsurface, all the units are metric internally.)

**Comment by Brett-Howard** [comment]
Ok well that is bloody well awesome!  Makes me feel a little better about my consumption too! ;)  Man this really is a fantastic bit of kit and it warms my heart that it'll still be available when this Mac finally dies and I go back to Linux because I no longer have as pressing of a need for Photoshop and Lightroom.  Thanks again everyone who contributes!!!!
