### ISSUE TITLE
mobile: black subsurface logo due to Kirigami bug

### ISSUE THREAD

**Issue by mfbernardes** [subsurface/subsurface#1331]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Since the last Kirigami update the subsurface logo is black, as below:

 ![img_4173](https://user-images.githubusercontent.com/30494/39968147-d4da7d4c-56c8-11e8-95a1-d75eff06bf7a.jpg)

This is due to Kirigami having changed the Icon implementation, and erroneously tinting icons that should not be tinted.

I'll report and track with Kirigami dev.

### Operating system:

iOS 11.3

### Mentions:

@notmart

**Comment by mfbernardes** [comment]
I've split #1267 because I found the cause of different icons missing. This one is unrelated to the others.

Some tests reported on #1307

**Comment by neolit123** [comment]
@janiversen @mfbernardes 
please, close this issue if it's a duplicate or if we have a fix in `master` already.
thanks.

**Comment by janiversen** [comment]
@neolit123 I just tested with master on my iPhone, problem is still there, just as @mfbernardes describes it. The idea it is being tinted, sounds very logical from the debugging I have done (the image is loaded from disk/memory, but then changed on its way).
