### ISSUE TITLE
Line breaks not working when printing in macOS

### ISSUE THREAD

**Issue by fedMasias** [subsurface/subsurface#136]
When printing in macOS, line breaks entered in the notes section are not properly shown, and instead show `<br>` tags. 

Screenshots:
Notes section in Subsurface:
<img width="172" alt="linebreaksinprogram" src="https://cloud.githubusercontent.com/assets/24869704/21731644/f10859bc-d41a-11e6-9dd0-5d8cdc97e29d.png">
Notes section when printing:
<img width="295" alt="tagsuponprinting" src="https://cloud.githubusercontent.com/assets/24869704/21731646/f261a872-d41a-11e6-989b-318342998da0.png">

This is broken in the Flow Layout, One Dive, Six Dives, and Two Dives default templates.

Example file:
[lineBreakTest.xml.zip](https://github.com/Subsurface-divelog/subsurface/files/690719/lineBreakTest.xml.zip)

**Comment by atdotde** [comment]
Works for me on my Mac, both for current master as well as the Beta from the Web site.

**Comment by fedMasias** [comment]
What version of macOS? I'm on 10.11.6, and can't upgrade due to some software I need being broken on newer versions. I wonder if it's just an El Capitan problem?

The same file works for me in an Ubuntu VM using the Beta.

**Comment by Subsurface-divelog** [comment]
That should not be related to the OS version. And the Qt version is bundled. Can you give us a screenshot of the About Subsurface screen? Did you compile the binary yourself or is this one of the ones I built?

**Comment by fedMasias** [comment]
Sure:
<img width="374" alt="screen shot 2017-01-06 at 11 35 58 pm" src="https://cloud.githubusercontent.com/assets/24869704/21739728/f82e624c-d468-11e6-9031-6bf7094ad444.png">

And this was first found on the Beta 1 build, and still shows on the Beta 2 build. I've not tried compiling myself, though I probably could if need be.

**Comment by Subsurface-divelog** [comment]
Oh bother. I now have one Mac with 10.11.6 where I can reproduce your problem, and one where I can't. With the exact same binary. This is going to be painful to debug.

**Comment by Subsurface-divelog** [comment]
I think I figured it out. Subsurface is picking up an older template that you saved locally at some point. And so the dive.notes aren't marked as 'safe'.
In the print dialog, select the template you want and click on Edit. Now select Template and scroll all the way down to the bottom (and to the right as this is deeply indented). You'll see something like this

```
<div class="textArea">
                       <p> {{ dive.notes }} </p>
</div>
```

but it should read like this:

```
<div class="textArea">
                       <p> {{ dive.notes|safe }} </p>
</div>
```

Add the '|safe', save the change and apply it and it should all work.

**Comment by fedMasias** [comment]
That fix works, across all of the templates. 

My only worry is that I don't remember ever having printed or viewed that menu before -- and I've only had Subsurface installed since October. Is it possible that it's picking up an old default?

**Comment by Subsurface-divelog** [comment]
I honestly don't know. I'll add this to the FAQ
