### ISSUE TITLE
[Idea] Default Startup on View>All

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#140]
Hello.

I'm a new user of your software and also a fresh french diver, and I would like to give some ideas (please, take into consideration following ideas).

Would it be possible to open as default Subsurface directly on View>All ?

Indead I was surprise when I left Subsurface on Globe View (or any other View) to still start on this view instead of View>All who are for me more friendly.

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
Similarly, other users will tell us that they want to come back to the last view that they used. Not something we can make everyone happy with. And Ctrl-1 will fix this for you

**Comment by Ghalr** [comment]
Hello.

I do understand.
Maybe an option to check:  Startup using default view (who is View>All) who can also be a Welcome page to start with. ?

Best regards.
