### ISSUE TITLE
Can´t download dives from Oceanic/Aeris dive computers with Subsurface-mobile

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#1403]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I can´t download dives from Oceanic VT4.1 and Aeris Epic dive computers with Subsurface-mobile.
Every time I try it I get no failure message.
If I try this with the Android App Divemate it is working.
### Operating system:

Android 6
### Subsurface version:

4.7.8.369
### Steps to reproduce:

1. Connect OTG Adapter zo Galaxy Note 3
2. Connect Dive Computer Interface USB (Subsurface will open automatically)
3. Connect Dive Computer to Interface
4. Open Dive Computer in Subsurface APP
5. Select "Oceanic", "VT 4.1", "FTDI"
6. Push "Download" --> it shows for a nano second downloadind and then nothing happened
    I can push the download button again and again....

**Comment by dirkhh** [comment]
As reported in the FAQ (https://subsurface-divelog.org/faq/):

Subsurface-mobile on Android (but not on iOS beacuse of hardware limitations) is designed to be able to download from some dive computers using FTDI based download cables and a USB OTG adapter. Unfortunately, there is an issue with the way in which Subsurface-mobile opens USB devices on Android. We do this from “native code”, not from a Java application. And while many Android phones allow this method of accessing OTG devices, an (apparently increasing) number of devices don’t. On these Android devices the attempt to download from divecomputers via the USB OTG adapter always fails. We understand in theory how to work around this problem, but haven’t found the right developer who could volunteer their time to help us fix the issue.

**Comment by satoschu** [comment]
Hallo Dirk,

das verstehe ich nicht! Bis vor kurzem hat die Synchronisation wunderbar funktioniert  und an meinem Mobilgerät hat sich nichts verändert außer der Versionsstand von Subsurface-mobile.
Hätte ich noch die alte Version, ich glaube seit dem es nicht mehr funktioniert sind 5 Updates vergangen, könnte ich es nochmal testen. Es funktionierte wirklich gut.

Mit freundlichen Grüßen,

Tobias Schuster

Von: Dirk Hohndel
Gesendet: Montag, 18. Juni 2018 10:02
An: Subsurface-divelog/subsurface
Cc: satoschu; Author
Betreff: Re: [Subsurface-divelog/subsurface] Can´t download dives from Oceanic/Aeris dive computers with Subsurface-mobile (#1403)

As reported in the FAQ (https://subsurface-divelog.org/faq/):
Subsurface-mobile on Android (but not on iOS beacuse of hardware limitations) is designed to be able to download from some dive computers using FTDI based download cables and a USB OTG adapter. Unfortunately, there is an issue with the way in which Subsurface-mobile opens USB devices on Android. We do this from “native code”, not from a Java application. And while many Android phones allow this method of accessing OTG devices, an (apparently increasing) number of devices don’t. On these Android devices the attempt to download from divecomputers via the USB OTG adapter always fails. We understand in theory how to work around this problem, but haven’t found the right developer who could volunteer their time to help us fix the issue.

**Comment by dirkhh** [comment]
Ich habe leider kein einziges Android Geraet, mit dem ich das testen koennte (alle meine Telefone / Tablets verweigern den Zugriff auf OTG Geraete). Von daher ist das alles etwas frustrierend.
In welcher Version hat das denn noch geklappt? Vielleicht kann ich mit Hilfe dieser Information erraten, was das Problem sein koennte.

**Comment by satoschu** [comment]
Hello Dirk,

is it possible to get the old versions anywhere to download? Then I will test it.

Best regards,

Tobias

**Comment by dirkhh** [comment]
http://subsurface-divelog.org/downloads/test/old/ has dozens of older versions

**Comment by ecsfang** [comment]
Sorry for jumping in, but according to the following post it worked in 4.7.4.280 but failed from 4.7.5 and onwards ...
http://lists.subsurface-divelog.org/pipermail/subsurface/2018-June/032151.html

Best regards,
Thomas

**Comment by satoschu** [comment]
Hello, I tested it yesterday and Thomas is right! If I use the 4.7.4.280 the downloading of the dives is working without problems!

**Comment by satoschu** [comment]
I tried yesterday with 4.7.8.389 and it was working!

**Comment by dirkhh** [comment]
Excellent, thanks for the confirmation. And thank you @glance- for fixing the bug.

**Comment by satoschu** [comment]
Sorry to reopen this "bug" but the function to download with FTDI interface works really difficulty. If I try to download the dives I have start the download procedure more than one time. I don´t know why it worked perfectly the fist time while testing after updating. I try to describe the download procedure that worked in my case.

1. Connecting the Interface to the dive computer
2. Connecting the Interface to the mobile phone -> Subsurface is opening automatically
3. Opening dice computer download menu
4. Selecting connection FTDI (I have to select it every time it will not be stored)
5. Pushing the download button - Maybe it will download or not
6. If not closing subsurface
7. Disconnecting dive computer from the mobile phone
8. Starting at point 1.

This procedure have to be done between 1 and 10 time.

**Comment by glance-** [comment]
I'm guessing you have a dickey cable. My smartinterface.de cable Is really dicky, but the plain micro-usb cables I use for OSTC's are rock solid.

**Comment by satoschu** [comment]
Hi,if I use the app Divemate for testing purpose it is working without problems with the same cable?!?

**Comment by glance-** [comment]
Anyway, its a different issue, if it works sometimes and not other times. Open a separate issue with the log files attached.
