### ISSUE TITLE
[Idea] Help Menu order

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#141]
Hello,

Still about friendly use, would it be possible to have a Menu order like this ?

User manual
User survey
Check for updates
About Subsurface

And also some direct link to 
- mobile version
- User forum
- Mailing list page : http://lists.subsurface-divelog.org/cgi-bin/mailman/listinfo/subsurface

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
Having about on top in the Help menu (unless on a Mac) appears to be the standard.
Everything else is about personal preferences.
