### ISSUE TITLE
mobile: Dive flags are missing from the maps

### ISSUE THREAD

**Issue by mfbernardes** [subsurface/subsurface#1410]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Dive flags are missing from the maps.

As reported by John Smith. I can reproduce.

### Operating system:

iOS: 11.3.1
App Version: 2.1.0 (4.7.8.372) TestFlight

**Comment by neolit123** [comment]
@mfbernardes iOS, Android or both?

i think i saw a recent refactoring of icons that might have broken this.

**Comment by janiversen** [comment]
interesting there are flags with mobile on Mac, continue testing.

**Comment by janiversen** [comment]
testFlight iOS:

error is in MapWidget.qml line 60   cannot open qrc:////dive-location-marker-icon

can the //// be a problem, or is it just the log ?

**Comment by neolit123** [comment]
i cannot reproduce this with the mobile-on-desktop build.
`qrc:////` is a potental problem - there is an extra `/` in there.

it's not the log; tested that.

so it could be something in the mobile (iOS?) version that adds this extra `/` in the QRCs.

**Comment by janiversen** [comment]
It sure could, but I am still puzzled because I see flags with mobile-on-desktop (master) but not on iOS (also master).

**Comment by neolit123** [comment]
tested on Android with this build from couple of days ago:
https://github.com/Subsurface-divelog/subsurface/releases/tag/continuous

cannot reproduce the bug, so it seems either iOS specific or that particular test flight build has a problem.

**Comment by janiversen** [comment]
Your comments gave me an idea, and with #1412 it works on my iPad.
