### ISSUE TITLE
Subsurface-mobile beta: dive plot empty

### ISSUE THREAD

**Issue by Ebi129** [subsurface/subsurface#1419]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When a dive is manually added and saved the dive profile is not shown, only an empty graph is shown in the details view of the dive. By swiping two dives to the left and then back to the right the graph is now shown correctly. If values are changed the graph is not redrawn, only after swiping  two dives back and forth again.

### Operating system:

Android 7.0 german

### Subsurface version:

Subsurface-mobile beta 2.1.0(4.7.8.389)
### Current behavior:

![grafik](https://user-images.githubusercontent.com/40398434/41714091-807e8c52-754f-11e8-9c88-8193df4a2d71.png)

**Comment by dirkhh** [comment]
I can confirm both of these issues. I spent quite some time yesterday trying to figure out how to force the library that we use to update the profile picture, so far with no success.
Thanks for your report.
