### ISSUE TITLE
[Idea] Add a diving mode

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#142]
Hello,

Would it be possible to had a Diving Mode (maybe as pre-saved tags?) to be able to categorize more efficiently our divelogs, when we type the first letter the entire diving mode is available.

For example:
- Scuba Diving
- Free Diving
- Solo Diving
- Cave Diving
- Deep Diving
- Technical Diving
- Archaeology‎ Diving
- Biology Diving
- Photography Diving
- Student/Train Diving (for new/experienced divers training for courses)
- Instructor Diving
- others...

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
We have OC/CC/Freediving as diving modes
What you describe is exactly what the tags are intended to do.

**Comment by Ghalr** [comment]
Hello.

Yes you are right I was more thinking about auto-completion tags, If we type for example S it should give use Solo, Scuba tags directly. Was not thinking about the custom way.
