### ISSUE TITLE
Please publish the android application on f-droid

### ISSUE THREAD

**Issue by benzea** [subsurface/subsurface#1429]
Some people might be using an android phone with the Google Play support installed. I personally use a Sailfish OS device and am in the situation that I cannot download APKs from Google Play Store.

It would be useful if the APK was available through the F-Droid store or also as a direct download.

CC: @kittykat

**Comment by atdotde** [comment]
You can get the APK here on GitHub: https://github.com/Subsurface-divelog/subsurface/releases

**Comment by benzea** [comment]
Oh, nice! Thanks for the information.

**Comment by schmittlauch** [comment]
@atdotde Is the app working for you? On my Jolla1 (Android API level 4.1) it's crashing on startup.
Can I find the required Android version somewhere? I have no  Play Services of course, if that's the issue.

**Comment by dirkhh** [comment]
Subsurface-mobile on Android requires Android 4.4 or newer

**Comment by benzea** [comment]
Hmm, yeah, I just tried it finally, and I have the same problem on my Jolla X.

**Comment by IzzySoft** [comment]
@atdotde if the releases have an APK attached (the latest has not), it seems to be a debug build. What's keeping you from having it built by F-Droid (without GMS that is)? If you're OK with *having* it there, I gladly assist you with *bringing* it there.
