### ISSUE TITLE
[Idea] Add a Certifications log / Diving center with link to Dive number

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#143]
Hello,

Would it be possible to have Certifications log, something like : 

15.08.2016 OWD (PADI) - Ocean Reef Center, Australia (AUD)

It's just an idea taken from divelogs.de, it would also be an idea to track down any center diving we went, or any diving site related to this center,  something like

Name:
Adresse:
Phone Number:
Website:
Instructor Name / Phone Number:    + add if more
Linked divelog: Dive#1 Dive#3 Dive#6 Dive#12
Linked divesite:

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
That's just not the type of data I am interested in tracking. Everyone would want something else here, making the UI more and more cluttered for very few users.
