### ISSUE TITLE
Feature-Request: Add configuration for default equipment

### ISSUE THREAD

**Issue by lje** [subsurface/subsurface#1436]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

When I create a new dive, it starts with an air-tank of 11.1 liters (which don't exist, the internal default probably is an imperial unit) and 207bar. The actual real-world default for bases targeting European divers (like in Egypt) is 12 liters and 200bar. I'd like to maintain these as a default for new dives. Since I almost always dive with EAN32, I'd like to maintain that as well.
Additional defaults would be wetsuit (almost always the same one) and even buddy (diving with my significant other).

### Subsurface version:

4.7.8, German or English language, metric units

**Comment by mfbernardes** [comment]
You can set your default cylinder, just go to Preferences->General, there you have "Use default cylinder". There you can choose your 12L 200bar ;)

Other equipment have way to set default.

I can't hold myself so... I have to disagree that 11.1L 207 bar doesn't exist. It's a standard Aluminum 80cuft used specially in warm waters. The actual real world has many tank sizes and volumes.

**Comment by dirkhh** [comment]
The AL80 is the BY FAR most common tank world wide - which is why it is the default cylinder.
11.1l wet volume, rated at 300psi (or about 207bar).
For everything else, simply use Ctrl-C to copy the data you want from the previous dive and then Ctrl-V paste it into the next dive.
