### ISSUE TITLE
Deletion of images in profile not working on Windows

### ISSUE THREAD

**Issue by bstoeger** [subsurface/subsurface#1441]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

While trying to test Bluetooth on Windows I found a usability bug: Deleting images does only work sporadically in the profile plot. I can only guess that this has something to do with case insensitive filenames? It's difficult for me to debug as I have no build environment on Windows.

### Subsurface version:

Windows 7 Enterprise
Version 6.1 (Build 7601: Service Pack 1)

### Steps to reproduce:

Click on trashcan symbol.
### Current behavior:

Nothing.
### Expected behavior:

Picture gets deleted.

**Comment by dirkhh** [comment]
Since you are a Collaborator... push a branch to GitHub/Subsurface-divelog/subsurface with the code that you want to test. Since you push to the main repo, Travis will kick in, and among other things create a Windows installer for you that will be available as "release" for your branch :-)

**Comment by bstoeger** [comment]
Alright - probably not a Windows thing after all, but related to my recent changes to the thumbnails. Weird that so far I've only seen it on Windows. But I think I know how to reproduce.
