### ISSUE TITLE
Pictures shown when manually adding dives

### ISSUE THREAD

**Issue by bstoeger** [subsurface/subsurface#1445]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [x] Discussion request

### Issue long description:

When adding a dive, the dive photo tab shows the pictures of the previously selected dive(s). While this is technically correct (the dive selection is still valid), it seems weird from an UI perspective.

### Operating system:

```
$ uname -a
Linux laptop 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
I doubt that this is OS-dependent.
### Subsurface version:

Current master.

### Steps to reproduce:
1) Go to photos-tab with dive having pictures.
2) CTRL-+.
### Current behavior:

Previous pictures are shown.
### Expected behavior:

No pictures shown, unless new pictures are added manually (?)

**Comment by bstoeger** [comment]
N.B.: Same is true for statistics tab.

What about disabling all but the "Notes" and "Equipment" tabs during dive adding?

**Comment by dirkhh** [comment]
Are you going to send a patch? :-)
It would be nice to have that for 4.8.2
