### ISSUE TITLE
[Idea] Add Buddy infos

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#145]
Hello,

Would it be possible to add Buddy infos, something like:

Name:
Adress:
Location:
Phone Number:
Email:
Certifications: Highest certification and Tec
Number Dives Together:
Lastest dive: DDMMYY (X days ago)

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
Not something I am interested in adding.
Clutters the UI, very limited value to most divers.

**Comment by Ghalr** [comment]
Hello.

You are right,
Thanks anyway.
