### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by wjdp** [subsurface/subsurface#1457]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Installed application today on Ubuntu 16.04. Imported some dives from a Vyper via usb, started work on importing older dives via CSV.

Was having issues with CSV import (parser error after matching columns) so decided to launch subsurface from console to see if there was a more descriptive error message there.

Launching the application from console results in an instant crash. Launching app from window manager yields nothing.

### Operating system:

```
 Date: Tue Jul  3 21:16:35 BST 2018
 Subsurface Options: 
 Subsurface version: 
 Arch: x86_64
 Kernel: Linux 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018
 Release: Ubuntu 16.04.4 LTS (Xenial Xerus)
```

### Subsurface version:

```
~ ❯ subsurface --version
QEventLoop: Cannot be used without QApplication
QDBusConnection: system D-Bus connection created before QCoreApplication. Application may misbehave.

** (subsurface:6385): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-2sEFvxFumC: Connection refused
Subsurface v4.8.0,
built with libdivecomputer v0.7.0-devel-Subsurface-NG (02560a7e7fe82919d584d3edbf3876f90382052c)
built with Qt Version 5.5.1, runtime from Qt Version 5.5.1
built with libgit2 0.26.0
[1]    6385 segmentation fault (core dumped)  subsurface --version
```

Version from Ubuntu PPA.

### Steps to reproduce:

1. Launch subsurface

### Current behavior:

Instant crash

```
~ ❯ subsurface                                                                                                      ↩
QEventLoop: Cannot be used without QApplication
QDBusConnection: system D-Bus connection created before QCoreApplication. Application may misbehave.

** (subsurface:6425): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-2sEFvxFumC: Connection refused
[1]    6425 segmentation fault (core dumped)  subsurface
```

```
~ ❯ subsurface.debug                                                                                                ↩
QEventLoop: Cannot be used without QApplication
QDBusConnection: system D-Bus connection created before QCoreApplication. Application may misbehave.

** (subsurface:5802): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-2sEFvxFumC: Connection refused
Segmentation fault (core dumped)
QEventLoop: Cannot be used without QApplication
QDBusConnection: system D-Bus connection created before QCoreApplication. Application may misbehave.

** (subsurface:5814): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-2sEFvxFumC: Connection refused
Segmentation fault (core dumped)
find: ‘/subsurface/’: No such file or directory
Crash report available at /home/will/subsurface_crashlog-20180703_211635.log
```

Crash log: https://gist.github.com/wjdp/ca5d1aec63e15d6ea28b354eb6e09949

### Expected behavior:

Application launch

### Additional information:

- I have renamed my `~/.subsurface` folder to no effect.
- I have `apt purge` and reinstalled package
- I have rebooted

**Comment by neolit123** [comment]
hi @wjdp
thank you for the report.

```
~ ❯ subsurface --version
QEventLoop: Cannot be used without QApplication
...
Segmentation fault (core dumped)
```
> Version from Ubuntu PPA.

that particular build of the app seems broken.

please, try using our AppImage instead:
https://subsurface-divelog.org/downloads/Subsurface-4.8.0-x86_64.AppImage

**Comment by wjdp** [comment]
AppImage version seems to work, UI looks a little different (slightly better I think)

Now to look into the CSV issue, it seems to not like ampersands or angled brackets in notes, perhaps due to subsurface using XML as storage?

**Comment by neolit123** [comment]
@wjdp 
> Now to look into the CSV issue, it seems to not like ampersands or angled brackets in notes, perhaps due to subsurface using XML as storage?

yes, i can confirm the `&` and `<>` not working on import.
could you please log a separate issue for that?
