### ISSUE TITLE
[Idea] Improve Used gas when creating a Plan Dive

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#146]
Hello

Would it be possible to select other gases used during our dive, instead of manually entering gas %
I read your manual, this can be interesting to manually put those values specially for your example with EAN50. But for common divers it would be more easy to directly put most common mix. Wa can have choose to use "default" or "custom" value.

Air
Nitrox (EAN 32, 36, 40)
Trimix (hypoxic, normoxic, hyperoxic)
Rebreather
Others...

Really appreciate,
Best regards.

**Comment by atdotde** [comment]
Given how long that list would be I don't see and advantage over typing two digit percentages.
