### ISSUE TITLE
Make check failing on macos

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1469]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When running “make check” on macos (and maybe other OS as well) it fails to load libgit2.26.dylib

Running e.g “otool -l TestMerge” shows that the path for libgit2.26.dylib is not corrected (actually no path) in contrast to other dylibs.

Copying lib2.26.dylib to /usr/local/lib is a workaround

### Operating system:

Macos 11.3

**Comment by dirkhh** [comment]
I can reproduce and I'll figure out how to fix that.
