### ISSUE TITLE
[Idea] Incorpore easy formula for Nitrox  Mix, EAD, MOD

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#147]
Hello

It would be really interesting to add a easy to use calculation for Nitrox 'best mix, EAD and MOD.

Really appreciate,
Best regards.

**Comment by Subsurface-divelog** [comment]
I'm not clear what you mean by that. We already add so much information in the info overlay, so I'm hesitant to add more...

**Comment by dirkhh** [comment]
forgot to close this
