### ISSUE TITLE
Can´t configure a OSTC 2 TR with Subsurface 4.8

### ISSUE THREAD

**Issue by MarioSDR93** [subsurface/subsurface#1474]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I can´t configure a OSTC 2 TR with Subsurface 4.8 on Windows.

When i try to connect to the divecomputer over Bluetooth to change settings i get the error message "Unsupported operation"

### Operating system:

Windows 10 x64 build 1803
OSTC 2 TR Firmware 2.97 SP1

### Subsurface version:

The error is in Subsurface 2.8, 2.7.8 is working correctly

### Steps to reproduce:

Try to connect to the divecomputer over Bluetooth to configure it.

### Current behavior:
Error message "Unsupported operation"

### Expected behavior:
Should connect without error message

### Additional information:

![ostc_2_tr_configuration_failed](https://user-images.githubusercontent.com/5072885/42412563-f7479146-820e-11e8-8842-3a2b83b57214.PNG)

I get the error with Subsurface 4.8, with 4.7.8 it works well. Here are the libdivecomputer logs from both versions 
[subsurface_4.7.8.log](https://github.com/Subsurface-divelog/subsurface/files/2172887/subsurface_4.7.8.log)
[subsurface_4.8.log](https://github.com/Subsurface-divelog/subsurface/files/2172888/subsurface_4.8.log)

**Comment by dirkhh** [comment]
Derek set milestone: 4.8

**Comment by dirkhh** [comment]
Derek close: https://github.com/Subsurface-divelog/subsurface/commit/4c2e1529c02bd72ec9662a04f856d9099f3f327d

**Comment by MarioGeckler** [comment]
I still get the same error on 4.8.1

Is there any other bluetooth related change from 4.7.8 to 4.8(.1) ?
