### ISSUE TITLE
Crash using ruler (with language  set to 'french')

### ISSUE THREAD

**Issue by frdrc66** [subsurface/subsurface#1513]
### Describe the issue:

- [X ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Using the ruler make SubSurface crash when language  is set to 'french'.
Seems working with UI language set to 'english'

### Operating system:

Windows 10

### Subsurface version:

4.8.1

Already present in 4.7.8

official release

### Steps to reproduce:

Just click on the red disk and try to move it

### Current behavior:

Subsurface crashes after few seconds

### Expected behavior:

The red circle should move (and subsurface not crash !)

**Comment by mturkia** [comment]
There is a typo in the translation on transifex for france. It currently
reads:
        <translation>SAC : %.*f%s/min</translation>
But it should be:
        <translation>%s SAC : %.*f%s/min</translation>

I do not have access to  the French translation, so I cannot do the fix
myself, Guillaume (CC) should be able to fix this.

**Comment by dirkhh** [comment]
I fixed this on Transifex - the next version will bring in the corrected translation.

**Comment by frdrc66** [comment]
Well done Guys, I've patched I've patched : it works!
BTW : we are the champion, vive la France!!!

**Comment by ggardet** [comment]
Thanks for the fix @dirkhh 
You were faster than me. ;)
