### ISSUE TITLE
Dive media files: Add "Open file location in file manager" to context menue

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#1514]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

This is a small feature request for the dive media files implementation which I would like to discuss and maybe also ask s.o. to implement it.
It's simply that I would like to have a context menu entry to open the selected media files folder in the systems default file manager. Use case is: I found a nice picture or video of a dive which I want to share e.g. by copying to my Dropbox of sending it by email. That would work much faster if I immediately can open the correct folder with the file(s).

### Mentions:

@bstoeger @atdotde

**Comment by bstoeger** [comment]
Doesn't look too hard.

What should happen if multiple files belonging to different folders are selected? Open all directories?

Generally, I feel that the context-menu should be moved down from `TabDivePhotos` to `DivePictureWidget`. From the latter we have easy access to the item that is below the mouse cursor and the user could simply right-click > open file in filemanager, without need for explicit selection.

**Comment by atdotde** [comment]
You can open the directory via QDesktopServices::openUrl( QUrl::fromLocalFile( path ) );

If you want to highlight files, this might be relevant: https://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt
