### ISSUE TITLE
Print formatting notes

### ISSUE THREAD

**Issue by lucagrossi85** [subsurface/subsurface#153]
You can't print notes respecting formatting.
Also if I save and then print my plans immersion, into field notes I see html code.

**Comment by atdotde** [comment]
Have a look at the last question of https://subsurface-divelog.org/faq/ This sounds like it could be your problem.

**Comment by Subsurface-divelog** [comment]
please report back here if this worked (and close the issue) :)

**Comment by lucagrossi85** [comment]
If you select Log > Plain dive from menu bar, then you click button save, after click from menu bar file > print, in this litte window open select one dive with template and click preview, a new little window is open and you can see in the field Notes html code: 

<div><b>DISCLAIMER / WARNING: THIS IS A NEW IMPLEMENTATION OF THE BUHLMANN ALGORITHM AND A DIVE PLANNER...<b></div><br><div><b>Subsurface dive plan</b><br>based on B.....ith GFlow = 30 and GFhigh = 75</div>.

I don't saw my Notes formatted into page print.

**Comment by dirkhh** [comment]
did you take a look at the FAQ that @atdotde mentioned above, @lucagrossi85 ?
It seems quite likely that you have a local copy of an outdated print template which is causing this behavior, the faq contains the necessary steps to fix this. If you tried that and it didn't work, please let us know here so we can investigate further.

**Comment by lucagrossi85** [comment]
Ok now it work. Thank you all!!
