### ISSUE TITLE
DCDeviceData.bluetooth_mode true even w/o BT_SUPPORT

### ISSUE THREAD

**Issue by kristapsdz** [subsurface/subsurface#1541]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When BT_SUPPORT is *not* enabled, the "use bluetooth" checkbox is not displayed (cf. desktop-widgets/downloadfromdivecomputer.cpp) and setBluetoothMode is never called.  However, DCDeviceData (core/downloadfromdcthread.cpp) sets bluetooth_mode to true by default.  Since the button does not engage without BT_SUPPORT and is checked by default, the downloader always tries to use BT even if it's not compiled in.  This makes downloading from any DC impossible.

I've locally patched core/downloadfromdcthread.cpp as:

```c
#ifdef BT_SUPPORT
        data.bluetooth_mode = true;
#else
        data.bluetooth_mode = false;
#endif
```

And everything works fine.  This is on OpenBSD, which doesn't have bluetooth at all.

Alternatively, desktop-widgets/downloadfromdivecomputer.cpp could be patched to setBluetoothMode(false) if the CPP check for BT_SUPPORT is false.

(I can make a git pull, but it's a tiny patch and I'm still getting the hang of git...)

**Comment by dirkhh** [comment]
I'd love to see a pull request.
Practice makes perfect.
