### ISSUE TITLE
No package for Ubuntu 18.04 i386

### ISSUE THREAD

**Issue by bubjo** [subsurface/subsurface#1559]
At the moment it is not possible to install Subsurface under Ubuntu 18.04 32-bit.

**Comment by bubjo** [comment]
That is the 64-bit version, but I need the 32-bit version.

For Artful this version exists in the ppa, but not for Bionic.

**Comment by dirkhh** [comment]
On Thu, Aug 09, 2018 at 09:18:37PM +0000, bubjo wrote:
> That is the 64-bit version, but I need the 32-bit version.

Build from source. I don't think there's another path right now.

/D

**Comment by ghost** [comment]
You can build from source as suggested by @dirkhh or how about you try to use snaps instead.
https://snapcraft.io/subsurface

**Comment by dirkhh** [comment]
I didn't realize that the Snap was available in 32bit as well. My fault. And thanks for pointing this out @sarthakthakur24

**Comment by bubjo** [comment]
Sorry, but then Snap-Version does not work under Bionic 32-bit.

Have you a little description who to build a program from code?

**Comment by mturkia** [comment]
there is now a 32 bit version on launchpad for bionic. Would be great to hear if everything works on it.
