### ISSUE TITLE
Insufficient quoting in HTML export

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#1576]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

from the user forum:

Got the following two errors in the JS console:
```
list_lib.js:813 Uncaught ReferenceError: trips is not defined
    at getItems (list_lib.js:813)
    at window.onload (dives.html:109)
```
and 
```
dives.html_files/file.js:63 Uncaught SyntaxError: Unexpected identifier
```
Looking at line 63, I see I have some double quotes inside a string, which apparently weren't sanitized/escaped before including in file.js. Changing to single quotes and it's fine.
So, for those of us who don't know a) much Javascript, and b) what is and is not escaped upon being written to file.js, what else should I be careful of using in various free-form fields?

**Comment by neolit123** [comment]
cannot reproduce the user issue.
everything is escaped correctly via `membuffer.c::put_quoted()`

asked for feedback on the forum...

**Comment by jmedway** [comment]
One thing to make clear as the original reporter: The issue might be restricted to the "Trip Location" field not being sanitized. Any chance that is handled differently?

**Comment by neolit123** [comment]
i will submit a fix in a minute.
