### ISSUE TITLE
Application crashes immediately when typing a comma into coordinates

### ISSUE THREAD

**Issue by ghost** [subsurface/subsurface#158]
I use Subsurface 4.5.6 on a Mac with Mac OS X 10.11.6.
When I edit the data for a location and enter the coordinates manually, typing a comma immediately crashes the program. I have set the format of coordinates to decimal.

**Comment by fedMasias** [comment]
I can confirm this is also happening on 4.6 Beta 2 on 10.11.6.

It does not appear to happen on Beta 2 on Ubuntu 14.04 or Windows 7 though, so it's another macOS thing.

**Comment by dirkhh** [comment]
Thanks for the report and the verification that it's still happening in the current source. I'll look into this.

**Comment by dirkhh** [comment]
I pushed a new daily build that should fix the bug. Please test it here:

http://subsurface-divelog.org/downloads/daily/Subsurface-4.5.97-45-g1ab6e7fc8a76.dmg

**Comment by fedMasias** [comment]
It's fixed and working with the new daily.
