### ISSUE TITLE
Add "dive mode" field to CSV dive details export

### ISSUE THREAD

**Issue by p-neves** [subsurface/subsurface#1588]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [X ] New feature request
- [ ] Discussion request

### Issue long description:

Can we please add a "Dive mode" field to the CSV dive details export format?

### Additional information:

This will facilitate filtering the Subsurface data on external programs...

**Comment by bstoeger** [comment]
@mturkia: I think this one is for you...
