### ISSUE TITLE
Add unit selection preference to mobile app

### ISSUE THREAD

**Issue by emonty** [subsurface/subsurface#1591]
### Describe the issue:
- [ ] Bug
- [ ] Change request
- [ x ] New feature request
- [ ] Discussion request

### Issue long description:
For reasons surpassing my personal understanding, my partner prefers Imperial units. And yet, the dive detail views in the mobile app only show the dive information in metric. Now, clearly metric is superior in virtually every way, but yet still I'd like to help those who have not yet transitioned their thinking.

### Operating system:
Android

### Subsurface version:
2.1.0(4.8.0.0)

### Steps to reproduce:
Open a dive in the mobile app
Try to see units in Imperial.

### Current behavior:
Only gloriously understandable metric units

### Expected behavior:
Confusing and nonsensical imperial units are displayed instead.

### Additional information:
I started digging through the code, but I'll have to admit I have some things to learn about QML+Android and could use some structural pointers.

**Comment by janiversen** [comment]
This is something that is in the works. buth the pointers are easy look at the directory mobile-widgets qmlmanager.cpp as well as the qml directory.

**Comment by mfbernardes** [comment]
Hello @emonty 

The way it should currently works is based on your locale.

We've seen some problems with certain locales, so.
- What is your locale? You can simply copy the log by going to About, and clicking "Copy logs to clipboard" (or equivalent in your language).

**Comment by janiversen** [comment]
@mfbernardes 

are you sure about the sync bit? qPrefUnit only loads local settings, but I did not check if that is overwritten in all places where used.

**Comment by mfbernardes** [comment]
@janiversen hmm... true, for some reason I had in mind it worked and didn't check the code now.

So, yeah, it will be Locale based only.

**Comment by jbygdell** [comment]
Derek assign: me
