### ISSUE TITLE
Edit existing dive in planner sets altitude to 3000m

### ISSUE THREAD

**Issue by flo269** [subsurface/subsurface#161]
Steps to reproduce:
- open SSRF
- select any existing dive
- >Log>Edit dive in planner
- confirm the dialog "Trying to replan a dive that's not a planned dive." with OK
- the altitude is set to 3000m (and thus the ATM pressure us wrong too).

Subsurface 4.6.0
OSX 10.12.2

![screen shot 2017-01-16 at 16 37 07](https://cloud.githubusercontent.com/assets/25147331/21976030/c9843486-dc0a-11e6-9670-a05fd23af594.png)

**Comment by atdotde** [comment]
Bummer. Just after the release. Patch already sent.
