### ISSUE TITLE
QFormlayout warnings on MAC, with master as of 1/9/2018

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1618]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When compiling standard for iOS and Mac the following warnings appear:

/Users/jani/develop/src/subsurface/desktop-widgets/preferences/preferences_defaults.ui: Warning: The name 'formLayout' (QFormLayout) is already in use, defaulting to 'formLayout1'.

/Users/jani/develop/src/subsurface/desktop-widgets/preferences/preferences_defaults.ui: Warning: The name 'horizontalLayout_3b' (QHBoxLayout) is already in use, defaulting to 'horizontalLayout_3b1'.

I believe (but are not 100% sure) this is due to a merge done over the summer period.

### Operating system:

OSX newest, Xcode newest

none, compiler warning

Qt 11.1
./subsurface/scripts/build.sh -desktop

### Expected behavior:

No warnings.

**Comment by bstoeger** [comment]
Thanks for the report - this is due to the new video fields. Feel free to rename the layouts to your liking.
