### ISSUE TITLE
Old warnings when compiler for osx.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1620]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When compiling for Mac, we continue getting these warnings:
## cd /Users/jani/LO/mac ##
Last login: Fri Aug 31 21:10:15 on ttys002
janMac:~ jani$ source ~/.bash_profile
janMac:~ jani$ cd develop/src
janMac:src jani$ ls
/Users/jani/develop/src/subsurface/core/color.cpp:9:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_1, { FUNGREEN1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                          }
/Users/jani/develop/src/subsurface/core/color.h:12:19: note: expanded from macro 'FUNGREEN1'
#define FUNGREEN1 QColor::fromRgbF(0.0, 0.4, 0.2, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:10:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_2, { APPLE1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~
                   {                       }
/Users/jani/develop/src/subsurface/core/color.cpp:11:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_3, { ATLANTIS1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                          }
/Users/jani/develop/src/subsurface/core/color.h:19:19: note: expanded from macro 'ATLANTIS1'
#define ATLANTIS1 QColor::fromRgbF(0.4, 0.8, 0.2, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:12:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_4, { ATLANTIS2, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                          }
/Users/jani/develop/src/subsurface/core/color.h:20:19: note: expanded from macro 'ATLANTIS2'
#define ATLANTIS2 QColor::fromRgbF(0.6, 0.8, 0.2, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:13:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_5, { EARLSGREEN1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                            }
/Users/jani/develop/src/subsurface/core/color.h:22:21: note: expanded from macro 'EARLSGREEN1'
#define EARLSGREEN1 QColor::fromRgbF(0.8, 0.8, 0.2, 1)
                    ^
/Users/jani/develop/src/subsurface/core/color.cpp:14:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_6, { HOKEYPOKEY1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                            }
/Users/jani/develop/src/subsurface/core/color.h:31:21: note: expanded from macro 'HOKEYPOKEY1'
#define HOKEYPOKEY1 QColor::fromRgbF(0.8, 0.6, 0.2, 1)
                    ^
/Users/jani/develop/src/subsurface/core/color.cpp:15:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_7, { TUSCANY1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                         }
/Users/jani/develop/src/subsurface/core/color.h:28:18: note: expanded from macro 'TUSCANY1'
#define TUSCANY1 QColor::fromRgbF(0.8, 0.4, 0.2, 1)
                 ^
/Users/jani/develop/src/subsurface/core/color.cpp:16:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_8, { CINNABAR1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                          }
/Users/jani/develop/src/subsurface/core/color.h:32:19: note: expanded from macro 'CINNABAR1'
#define CINNABAR1 QColor::fromRgbF(0.9, 0.3, 0.2, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:17:13: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_9, { REDORANGE1, BLACK1_LOW_TRANS } },
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   {                           }
/Users/jani/develop/src/subsurface/core/color.h:33:20: note: expanded from macro 'REDORANGE1'
#define REDORANGE1 QColor::fromRgbF(1.0, 0.2, 0.2, 1)
                   ^
/Users/jani/develop/src/subsurface/core/color.cpp:19:19: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { VELO_STABLE, { CAMARONE1, BLACK1_LOW_TRANS } },
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                         {                          }
/Users/jani/develop/src/subsurface/core/color.h:11:19: note: expanded from macro 'CAMARONE1'
#define CAMARONE1 QColor::fromRgbF(0.0, 0.4, 0.0, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:20:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { VELO_SLOW, { LIMENADE1, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                          }
/Users/jani/develop/src/subsurface/core/color.h:18:19: note: expanded from macro 'LIMENADE1'
#define LIMENADE1 QColor::fromRgbF(0.4, 0.8, 0.0, 1)
                  ^
/Users/jani/develop/src/subsurface/core/color.cpp:21:21: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { VELO_MODERATE, { RIOGRANDE1, BLACK1_LOW_TRANS } },
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           {                           }
/Users/jani/develop/src/subsurface/core/color.h:21:20: note: expanded from macro 'RIOGRANDE1'
#define RIOGRANDE1 QColor::fromRgbF(0.8, 0.8, 0.0, 1)
                   ^
/Users/jani/develop/src/subsurface/core/color.cpp:22:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { VELO_FAST, { PIRATEGOLD1, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                            }
/Users/jani/develop/src/subsurface/core/color.h:29:21: note: expanded from macro 'PIRATEGOLD1'
#define PIRATEGOLD1 QColor::fromRgbF(0.8, 0.5, 0.0, 1)
                    ^
/Users/jani/develop/src/subsurface/core/color.cpp:23:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { VELO_CRAZY, { RED1, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~
                        {                     }
/Users/jani/develop/src/subsurface/core/color.h:37:14: note: expanded from macro 'RED1'
#define RED1 QColor::fromRgbF(1.0, 0.0, 0.0, 1)
             ^
/Users/jani/develop/src/subsurface/core/color.cpp:25:11: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PO2, { APPLE1, BLACK1_LOW_TRANS } },
                 ^~~~~~~~~~~~~~~~~~~~~~~~
                 {                       }
/Users/jani/develop/src/subsurface/core/color.h:15:16: note: expanded from macro 'APPLE1'
#define APPLE1 QColor::fromRgbF(0.2, 0.6, 0.2, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:26:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PO2_ALERT, { RED1, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~
                       {                     }
/Users/jani/develop/src/subsurface/core/color.h:37:14: note: expanded from macro 'RED1'
#define RED1 QColor::fromRgbF(1.0, 0.0, 0.0, 1)
             ^
/Users/jani/develop/src/subsurface/core/color.cpp:27:11: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PN2, { BLACK1_LOW_TRANS, BLACK1_LOW_TRANS } },
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 {                                 }
/Users/jani/develop/src/subsurface/core/color.h:41:26: note: expanded from macro 'BLACK1_LOW_TRANS'
#define BLACK1_LOW_TRANS QColor::fromRgbF(0.0, 0.0, 0.0, 0.75)
                         ^
/Users/jani/develop/src/subsurface/core/color.cpp:28:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PN2_ALERT, { RED1, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~
                       {                     }
/Users/jani/develop/src/subsurface/core/color.h:37:14: note: expanded from macro 'RED1'
#define RED1 QColor::fromRgbF(1.0, 0.0, 0.0, 1)
             ^
/Users/jani/develop/src/subsurface/core/color.cpp:29:11: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PHE, { PEANUT, BLACK1_LOW_TRANS } },
                 ^~~~~~~~~~~~~~~~~~~~~~~~
                 {                       }
/Users/jani/develop/src/subsurface/core/color.h:62:16: note: expanded from macro 'PEANUT'
#define PEANUT QColor::fromRgbF(0.5, 0.2, 0.1, 1.0)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:30:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PHE_ALERT, { RED1, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~
                       {                     }
/Users/jani/develop/src/subsurface/core/color.h:37:14: note: expanded from macro 'RED1'
#define RED1 QColor::fromRgbF(1.0, 0.0, 0.0, 1)
             ^
/Users/jani/develop/src/subsurface/core/color.cpp:31:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { O2SETPOINT, { PIRATEGOLD1_MED_TRANS, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        {                                      }
/Users/jani/develop/src/subsurface/core/color.h:30:31: note: expanded from macro
      'PIRATEGOLD1_MED_TRANS'
#define PIRATEGOLD1_MED_TRANS QColor::fromRgbF(0.8, 0.5, 0.0, 0.75)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:32:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CCRSENSOR1, { TUNDORA1_MED_TRANS, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        {                                   }
/Users/jani/develop/src/subsurface/core/color.h:43:28: note: expanded from macro
      'TUNDORA1_MED_TRANS'
#define TUNDORA1_MED_TRANS QColor::fromRgbF(0.3, 0.3, 0.3, 0.5)
                           ^
/Users/jani/develop/src/subsurface/core/color.cpp:33:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CCRSENSOR2, { ROYALBLUE2_LOW_TRANS, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        {                                     }
/Users/jani/develop/src/subsurface/core/color.h:54:30: note: expanded from macro
      'ROYALBLUE2_LOW_TRANS'
#define ROYALBLUE2_LOW_TRANS QColor::fromRgbF(0.2, 0.2, 0.9, 0.75)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:34:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CCRSENSOR3, { PEANUT, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        {                       }
/Users/jani/develop/src/subsurface/core/color.h:62:16: note: expanded from macro 'PEANUT'
#define PEANUT QColor::fromRgbF(0.5, 0.2, 0.1, 1.0)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:35:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SCR_OCPO2, { PIRATEGOLD1_MED_TRANS, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                                      }
/Users/jani/develop/src/subsurface/core/color.h:30:31: note: expanded from macro
      'PIRATEGOLD1_MED_TRANS'
#define PIRATEGOLD1_MED_TRANS QColor::fromRgbF(0.8, 0.5, 0.0, 0.75)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:37:16: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PP_LINES, { BLACK1_HIGH_TRANS, BLACK1_LOW_TRANS } },
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      {                                  }
/Users/jani/develop/src/subsurface/core/color.h:42:27: note: expanded from macro 'BLACK1_HIGH_TRANS'
#define BLACK1_HIGH_TRANS QColor::fromRgbF(0.0, 0.0, 0.0, 0.25)
                          ^
/Users/jani/develop/src/subsurface/core/color.cpp:39:23: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TEXT_BACKGROUND, { CONCRETE1_LOWER_TRANS, WHITE1 } },
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             {                            }
/Users/jani/develop/src/subsurface/core/color.h:46:31: note: expanded from macro
      'CONCRETE1_LOWER_TRANS'
#define CONCRETE1_LOWER_TRANS QColor::fromRgbF(0.95, 0.95, 0.95, 0.9)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:40:16: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { ALERT_BG, { BROOM1_LOWER_TRANS, BLACK1_LOW_TRANS } },
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      {                                   }
/Users/jani/develop/src/subsurface/core/color.h:61:28: note: expanded from macro
      'BROOM1_LOWER_TRANS'
#define BROOM1_LOWER_TRANS QColor::fromRgbF(1.0, 1.0, 0.1, 0.9)
                           ^
/Users/jani/develop/src/subsurface/core/color.cpp:41:16: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { ALERT_FG, { BLACK1_LOW_TRANS, WHITE1 } },
                      ^~~~~~~~~~~~~~~~~~~~~~~~
                      {                       }
/Users/jani/develop/src/subsurface/core/color.h:41:26: note: expanded from macro 'BLACK1_LOW_TRANS'
#define BLACK1_LOW_TRANS QColor::fromRgbF(0.0, 0.0, 0.0, 0.75)
                         ^
/Users/jani/develop/src/subsurface/core/color.cpp:42:14: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { EVENTS, { REDORANGE1, BLACK1_LOW_TRANS } },
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {                           }
/Users/jani/develop/src/subsurface/core/color.h:33:20: note: expanded from macro 'REDORANGE1'
#define REDORANGE1 QColor::fromRgbF(1.0, 0.2, 0.2, 1)
                   ^
/Users/jani/develop/src/subsurface/core/color.cpp:43:19: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAMPLE_DEEP, { QColor(Qt::red).darker(), BLACK1 } },
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         {                               }
/Users/jani/develop/src/subsurface/core/color.cpp:44:22: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAMPLE_SHALLOW, { QColor(Qt::red).lighter(), BLACK1_LOW_TRANS } },
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            {                                          }
/Users/jani/develop/src/subsurface/core/color.cpp:45:16: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SMOOTHED, { REDORANGE1_HIGH_TRANS, BLACK1_LOW_TRANS } },
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      {                                      }
/Users/jani/develop/src/subsurface/core/color.h:34:31: note: expanded from macro
      'REDORANGE1_HIGH_TRANS'
#define REDORANGE1_HIGH_TRANS QColor::fromRgbF(1.0, 0.2, 0.2, 0.25)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:46:14: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { MINUTE, { MEDIUMREDVIOLET1_HIGHER_TRANS, BLACK1_LOW_TRANS } },
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    {                                              }
/Users/jani/develop/src/subsurface/core/color.h:67:39: note: expanded from macro
      'MEDIUMREDVIOLET1_HIGHER_TRANS'
#define MEDIUMREDVIOLET1_HIGHER_TRANS QColor::fromRgbF(0.7, 0.2, 0.7, 0.1)
                                      ^
/Users/jani/develop/src/subsurface/core/color.cpp:47:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TIME_GRID, { WHITE1, BLACK1_HIGH_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
                       {                        }
/Users/jani/develop/src/subsurface/core/color.h:48:16: note: expanded from macro 'WHITE1'
#define WHITE1 QColor::fromRgbF(1.0, 1.0, 1.0, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:48:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TIME_TEXT, { FORESTGREEN1, BLACK1 } },
                       ^~~~~~~~~~~~~~~~~~~~
                       {                   }
/Users/jani/develop/src/subsurface/core/color.h:23:22: note: expanded from macro 'FORESTGREEN1'
#define FORESTGREEN1 QColor::fromRgbF(0.1, 0.5, 0.1, 1)
                     ^
/Users/jani/develop/src/subsurface/core/color.cpp:49:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { DEPTH_GRID, { WHITE1, BLACK1_HIGH_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
                        {                        }
/Users/jani/develop/src/subsurface/core/color.h:48:16: note: expanded from macro 'WHITE1'
#define WHITE1 QColor::fromRgbF(1.0, 1.0, 1.0, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:50:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { MEAN_DEPTH, { REDORANGE1_MED_TRANS, BLACK1_LOW_TRANS } },
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        {                                     }
/Users/jani/develop/src/subsurface/core/color.h:35:30: note: expanded from macro
      'REDORANGE1_MED_TRANS'
#define REDORANGE1_MED_TRANS QColor::fromRgbF(1.0, 0.2, 0.2, 0.5)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:51:15: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { HR_PLOT, { REDORANGE1_MED_TRANS, BLACK1_LOW_TRANS } },
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     {                                     }
/Users/jani/develop/src/subsurface/core/color.h:35:30: note: expanded from macro
      'REDORANGE1_MED_TRANS'
#define REDORANGE1_MED_TRANS QColor::fromRgbF(1.0, 0.2, 0.2, 0.5)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:52:15: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { HR_TEXT, { REDORANGE1_MED_TRANS, BLACK1_LOW_TRANS } },
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     {                                     }
/Users/jani/develop/src/subsurface/core/color.h:35:30: note: expanded from macro
      'REDORANGE1_MED_TRANS'
#define REDORANGE1_MED_TRANS QColor::fromRgbF(1.0, 0.2, 0.2, 0.5)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:53:15: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { HR_AXIS, { MED_GRAY_HIGH_TRANS, MED_GRAY_HIGH_TRANS } },
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     {                                       }
/Users/jani/develop/src/subsurface/core/color.h:44:29: note: expanded from macro
      'MED_GRAY_HIGH_TRANS'
#define MED_GRAY_HIGH_TRANS QColor::fromRgbF(0.5, 0.5, 0.5, 0.25)
                            ^
/Users/jani/develop/src/subsurface/core/color.cpp:54:20: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { DEPTH_BOTTOM, { GOVERNORBAY1_MED_TRANS, BLACK1_HIGH_TRANS } },
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          {                                        }
/Users/jani/develop/src/subsurface/core/color.h:52:32: note: expanded from macro
      'GOVERNORBAY1_MED_TRANS'
#define GOVERNORBAY1_MED_TRANS QColor::fromRgbF(0.2, 0.2, 0.8, 0.5)
                               ^
/Users/jani/develop/src/subsurface/core/color.cpp:55:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { DEPTH_TOP, { MERCURY1_MED_TRANS, WHITE1_MED_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                                   }
/Users/jani/develop/src/subsurface/core/color.h:45:28: note: expanded from macro
      'MERCURY1_MED_TRANS'
#define MERCURY1_MED_TRANS QColor::fromRgbF(0.9, 0.9, 0.9, 0.5)
                           ^
/Users/jani/develop/src/subsurface/core/color.cpp:56:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TEMP_TEXT, { GOVERNORBAY2, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                             }
/Users/jani/develop/src/subsurface/core/color.h:51:22: note: expanded from macro 'GOVERNORBAY2'
#define GOVERNORBAY2 QColor::fromRgbF(0.2, 0.2, 0.7, 1)
                     ^
/Users/jani/develop/src/subsurface/core/color.cpp:57:17: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TEMP_PLOT, { ROYALBLUE2_LOW_TRANS, BLACK1_LOW_TRANS } },
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       {                                     }
/Users/jani/develop/src/subsurface/core/color.h:54:30: note: expanded from macro
      'ROYALBLUE2_LOW_TRANS'
#define ROYALBLUE2_LOW_TRANS QColor::fromRgbF(0.2, 0.2, 0.9, 0.75)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:58:19: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { SAC_DEFAULT, { WHITE1, BLACK1_LOW_TRANS } },
                         ^~~~~~~~~~~~~~~~~~~~~~~~
                         {                       }
/Users/jani/develop/src/subsurface/core/color.h:48:16: note: expanded from macro 'WHITE1'
#define WHITE1 QColor::fromRgbF(1.0, 1.0, 1.0, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:59:20: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { BOUNDING_BOX, { WHITE1, BLACK1_LOW_TRANS } },
                          ^~~~~~~~~~~~~~~~~~~~~~~~
                          {                       }
/Users/jani/develop/src/subsurface/core/color.h:48:16: note: expanded from macro 'WHITE1'
#define WHITE1 QColor::fromRgbF(1.0, 1.0, 1.0, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:60:21: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { PRESSURE_TEXT, { KILLARNEY1, BLACK1_LOW_TRANS } },
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           {                           }
/Users/jani/develop/src/subsurface/core/color.h:14:20: note: expanded from macro 'KILLARNEY1'
#define KILLARNEY1 QColor::fromRgbF(0.2, 0.4, 0.2, 1)
                   ^
/Users/jani/develop/src/subsurface/core/color.cpp:61:18: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { BACKGROUND, { SPRINGWOOD1, WHITE1 } },
                        ^~~~~~~~~~~~~~~~~~~
                        {                  }
/Users/jani/develop/src/subsurface/core/color.h:59:21: note: expanded from macro 'SPRINGWOOD1'
#define SPRINGWOOD1 QColor::fromRgbF(0.95, 0.95, 0.9, 1)
                    ^
/Users/jani/develop/src/subsurface/core/color.cpp:62:24: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { BACKGROUND_TRANS, { SPRINGWOOD1_MED_TRANS, WHITE1_MED_TRANS } },
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              {                                      }
/Users/jani/develop/src/subsurface/core/color.h:60:31: note: expanded from macro
      'SPRINGWOOD1_MED_TRANS'
#define SPRINGWOOD1_MED_TRANS QColor::fromRgbF(0.95, 0.95, 0.9, 0.5)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:63:23: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CEILING_SHALLOW, { REDORANGE1_HIGH_TRANS, BLACK1_HIGH_TRANS } },
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             {                                       }
/Users/jani/develop/src/subsurface/core/color.h:34:31: note: expanded from macro
      'REDORANGE1_HIGH_TRANS'
#define REDORANGE1_HIGH_TRANS QColor::fromRgbF(1.0, 0.2, 0.2, 0.25)
                              ^
/Users/jani/develop/src/subsurface/core/color.cpp:64:20: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CEILING_DEEP, { RED1_MED_TRANS, BLACK1_HIGH_TRANS } },
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          {                                }
/Users/jani/develop/src/subsurface/core/color.h:36:24: note: expanded from macro 'RED1_MED_TRANS'
#define RED1_MED_TRANS QColor::fromRgbF(1.0, 0.0, 0.0, 0.5)
                       ^
/Users/jani/develop/src/subsurface/core/color.cpp:65:28: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CALC_CEILING_SHALLOW, { FUNGREEN1_HIGH_TRANS, BLACK1_HIGH_TRANS } },
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  {                                      }
/Users/jani/develop/src/subsurface/core/color.h:13:30: note: expanded from macro
      'FUNGREEN1_HIGH_TRANS'
#define FUNGREEN1_HIGH_TRANS QColor::fromRgbF(0.0, 0.4, 0.2, 0.25)
                             ^
/Users/jani/develop/src/subsurface/core/color.cpp:66:25: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { CALC_CEILING_DEEP, { APPLE1_HIGH_TRANS, BLACK1_HIGH_TRANS } },
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               {                                   }
/Users/jani/develop/src/subsurface/core/color.h:17:27: note: expanded from macro 'APPLE1_HIGH_TRANS'
#define APPLE1_HIGH_TRANS QColor::fromRgbF(0.2, 0.6, 0.2, 0.25)
                          ^
/Users/jani/develop/src/subsurface/core/color.cpp:67:25: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { TISSUE_PERCENTAGE, { GOVERNORBAY2, BLACK1_LOW_TRANS } },
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               {                             }
/Users/jani/develop/src/subsurface/core/color.h:51:22: note: expanded from macro 'GOVERNORBAY2'
#define GOVERNORBAY2 QColor::fromRgbF(0.2, 0.2, 0.7, 1)
                     ^
/Users/jani/develop/src/subsurface/core/color.cpp:68:15: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { GF_LINE, { BLACK1, BLACK1_LOW_TRANS } },
                     ^~~~~~~~~~~~~~~~~~~~~~~~
                     {                       }
/Users/jani/develop/src/subsurface/core/color.h:40:16: note: expanded from macro 'BLACK1'
#define BLACK1 QColor::fromRgbF(0.0, 0.0, 0.0, 1)
               ^
/Users/jani/develop/src/subsurface/core/color.cpp:69:25: warning: suggest braces around
      initialization of subobject [-Wmissing-braces]
        { AMB_PRESSURE_LINE, { TUNDORA1_MED_TRANS, BLACK1_LOW_TRANS } }
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               {                                   }
/Users/jani/develop/src/subsurface/core/color.h:43:28: note: expanded from macro
      'TUNDORA1_MED_TRANS'
#define TUNDORA1_MED_TRANS QColor::fromRgbF(0.3, 0.3, 0.3, 0.5)
                           ^
57 warnings generated.

Should we not add the proposed braces ?

### Operating system:

osx newest, xcode newest.

### Expected behavior:

no warnings.

**Comment by dirkhh** [comment]
These are the result of the breadth of compilers that we support.
Adding the braces that clang asks for results in gcc on a couple of platforms failing to compile these files.

**Comment by bstoeger** [comment]
> Feel free to try it to submit a PR and then observe the gcc output vs clang output.

I'd love to, but it seems to me that the Travis Mac build fails to compile `libdivecomputer`...?

**Comment by bstoeger** [comment]
Must have been a fluke.

> [ 26%] Building CXX object core/CMakeFiles/subsurface_corelib.dir/color.cpp.o
[ 26%] Building CXX object qt-models/CMakeFiles/subsurface_models_desktop.dir/divelocationmodel.cpp.o

Looks good, no?

**Comment by dirkhh** [comment]
So I think this should be fixed now. Thanks @bstoeger
