### ISSUE TITLE
Map code seems broken since Qt 5.11

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1627]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When closing thee app, there are a lot of:
item QDeclarativeGeoMapQuickItem(0x7fce968c0120, parent=0x0, geometry=-3903.47,24310.4 32x32) still referenced

“a lot of” is exactly one pr dive, at least in my case.

### Operating system:

OSX

mac

### Subsurface version:

master

### Steps to reproduce:

open app with a logbook that contains map entries, close app.

### Additional information:

@dirkhh noted that he has seen the same problem.

**Comment by janmulder** [comment]
Ok, I see this as well, also running Qt 5.11.1. Interestingly, mentioned messages appear in my case at the start of the application (so not at the exit, this might be just a buffering thing of stuff written to the console). Some investigation shows that the fix of QTBUG-68366 introduced those `qWarning() ` printouts (this fix went in for Qt 5.11.1). Notice further this `qWarning()` printouts are ifdeff-ed QT_DEBUG in another Qt fix that probably goes into Qt 5.11.2 (see fd6c6e9654a147 of Qt's location module).

This all said. Nothing seems broken (as the title of this issue suggests). The map is displayed and working just fine. And yes, the `qWarning()` printouts are annoying, but the relevance at this point in relation to our codebase is (very) unclear.

**Comment by dirkhh** [comment]
Thanks for that investigation, I think it's reasonable to simply ignore them for now - I don't see a rational way to work around these warnings without patching Qt.
