### ISSUE TITLE
Request for changes in DC import form

### ISSUE THREAD

**Issue by xplwowi** [subsurface/subsurface#1640]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

It would be nice to have a couple of small changes in DC import selection form. I'm using KDE Plasma 5 on HiDPI  (2860x1620) laptop with with base font size 12pt and DPI 120.
 
1. This form has fixed size and always returns to the default setting with a horizontal scrollbar and last column mostly off the window. Consider adding saveState/saveGeometry to the dialog widget and stretchLastSection property to the table content.
![screenshot_20180906_021751](https://user-images.githubusercontent.com/5732649/45127922-369aab80-b17b-11e8-9a36-de34afc70fcd.png)

2. Recently added Garmin Descent MK1 is intended for every day use and may contain dozens of "shallow diving" activities recorded when swimming. It happens because last used diving activity is automatically engaged when the watch is submerged a few feet. 
   - It would be nice to have a possibility to use >=/<= filters in the columns and allow multiple rows selection mode for including/excluding activities. Excluded activities shouldn't appear in next import attempts. 
   - Alternatively, a selectable column sorter could be used for it.

3. Point 2, variant 1 implies changing the behavior of two buttons from select/unselect all to select/unselect visible.

### Operating system:

Linux, Garmin Descent MK1

### Subsurface version:

4.8.1/GIT

**Comment by dirkhh** [comment]
I don't think I want to invest the work to make this simple form sort-able. It is rather easy to simply sort the divelist afterwards (and if necessary, renumber the dives).
I realize that to the user this will feel like "hey, why aren't you doing this simple thing?", but the reality is that every little thing like this adds complexity and chances to break thing and regress... this just doesn't seem like it affects a lot of people - and there is a reasonable workaround, IMHO.
