### ISSUE TITLE
[Android] Cannot see text at top of screen

### ISSUE THREAD

**Issue by cmacdonnacha** [subsurface/subsurface#165]
Hey,

I'm using the android app and the text at the top of the main screen is truncated. See screenshot.

My phone is on Android  version 6.0.1 and the device is OnePlus Three.

Thanks,
Cathal

![screenshot_20170118-143756](https://cloud.githubusercontent.com/assets/9777763/22055285/085326bc-dd8d-11e6-9dd4-7f682337eb2c.png)

**Comment by dirkhh** [comment]
Happy to see your patches. Or the native Android app that you announced in your Google Play review.

**Comment by cmacdonnacha** [comment]
@dirkhh not sure what you mean by "happy to see your patches"?

**Comment by dirkhh** [comment]
That's how open source works. People see something that doesn't work, figure out what causes it, and then submit patches. You do realize that this project is written and maintained by all volunteers, that no one sees a penny for the tens and hundreds and thousands of hours they spend. Quite the contrary, some of us spend a lot of our own money to provide infrastructure (like the cloud storage) so others can use it for free (and then complain about it).

**Comment by cmacdonnacha** [comment]
Ah ok now in understand, you'd be happy to see my commits to fix this. Apologies I didn't mean to sound ungrateful and as I said in my review on the play store I hate to leave a poor review but it's an honest review regardless of it being maintained by volunteers or not. You should probably leave this issue open so that it can be tracked.
