### ISSUE TITLE
"Configure dive computer" fails for Oceanic 2.0

### ISSUE THREAD

**Issue by ghost** [subsurface/subsurface#166]
Able to connect to USB Oceanic Geo 2.0 and download dives from the computer.  Can also connect via the “Configure dive computer” window, but “Retrieve available details” fails.  My Geo 2.0 has version 1I (2014) firmware, which is the most current available.

![errorimg](https://cloud.githubusercontent.com/assets/25255255/22165641/d0cfac84-df11-11e6-84cf-15c47a48ccb5.png)

**Comment by glance-** [comment]
As you see in the left column of that dialog, it supports the OSTC3-family, the Suunto Vyper family and the OSTC family of computers and nothing else.

It certainly doesn't support the "Oceanic Geo 2.0" computer.

**Comment by dirkhh** [comment]
Yep, not supported.
