### ISSUE TITLE
mobile: default cylinder not used when downloading dives.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1677]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When manually adding a dive, the cylinder is automatically filled with the value of default_cylinder,
When downloading dives from a dive computer (in my case Suunto core) the cylinder is not filled and shows as unknown

### Operating system:

iOS

an iOS device and my Mac

### Subsurface version:

master

yes the upcoming release.

b79dd2c423b580781cda1dcc7e727c8fa08daa1a

### Steps to reproduce:

1) download dives from DC
2) check cylinder field.

### Current behavior:

cylinder field is "unknown"

### Expected behavior:

cylinder field = default_cylinder

**Comment by jbygdell** [comment]
I'll have time to look into this during the weekend.

**Comment by jbygdell** [comment]
@janiversen tested this with latest master (d16bcd897811) and the default cylinder __is applied__ to the downloaded dives as expected. 
This is on android, so we might again have a android vs iOS issue.

**Comment by janiversen** [comment]
@jbygdell, hmmm, yes it would seem so, or could it be that Suunto core reports the Cylinder and that name if unknown to Ssrf.

I looked in downloadfromdcthread.cpp to see if I could find where the dive was created, but without luck...do you happen to know where that happens ?

**Comment by jbygdell** [comment]
Isn't downloadfromdcthread just getting the data from the DC? The actual dive creation happens later.

If you follow it from DiveImportedModel::recordDives it ends in dive.c (fixup_dive) where the cylinders are validated.

**Comment by janiversen** [comment]
aaah yes you are right, I was too focused on the actual download, thanks. I will try with a breakpoint there, and see why iOS (or my DC) does funny things.

**Comment by janiversen** [comment]
btw, this commit might interest you:
https://github.com/janiversen/subsurface-mobile-enhancements/commit/f5b3dd5a599d9c3e9c6d2ffc94b9d88ad35e022c

you version works !!! but it is faster to do assignments

**Comment by janmulder** [comment]
>  you version works

Does that mean: no bug in Subsurface? @jbygdell cannot reproduce on master, and now @janiversen cannot reproduce on iOS? When I'm right, I propose to close this here.

**Comment by janiversen** [comment]
eeeeh ? I never wrote it works in iOS if you refer to my preceding message, it was about setting default_cylinder and my comment referred to the commit.

**Comment by janmulder** [comment]
Yes, I'm getting confused when you say "you version works".

**Comment by janiversen** [comment]
No problem :-)

**Comment by janiversen** [comment]
Solved, the problem is due to my DC.
