### ISSUE TITLE
QML UI issue with empty data fields

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#1694]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Download from dive computer in Subsurface-mobile.
Edit dives.

> there seems to be some residual information stuck in the build. I put “none” in my log for divemaster, but it came out “Parrots Landing Watersport Part” and I also wrote “none” in the bathing suit space, but it came out “bathing”. 

### Operating system:

iOS

### Subsurface version:

latest test binary

**Comment by bstoeger** [comment]
I can reproduce in so far that editing of Suit does not always work. But for me it seems the other way round: empty fields work, non-empty don't.
