### ISSUE TITLE
Changed Dive No. not saved...

### ISSUE THREAD

**Issue by tinoo** [subsurface/subsurface#170]
Hi Folks
I was just updating some dives with additional information, when i discovered the following behavior:

If i double click on the dive number at the Dive List and change the dive number, this will not be saved (into cloud)! Next time when i open subsurface again the numbers are like before...

The new dive number will only be stored when i right click -> renumber dive(s) and change the number there.
If you want to change more than one dive, this becomes very annoying... Double clicking directly into the Dive List would be much faster...
Maybe someone can put an eye on that issue? Thanks a lot!

**Comment by jbygdell** [comment]
You can renumber a continuous range of dives by selecting them, right click -> renumber dive(s), input the number that the first dive in the selection should have. The other dives will then be numbered in ascending order.

**Comment by dirkhh** [comment]
We need to figure out how to disable the double click on the dive number
