### ISSUE TITLE
Mobile: Keine automatische Cloud-Synchronisation 

### ISSUE THREAD

**Issue by dk4711** [subsurface/subsurface#1725]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
<Nach der Installation der neuen Version 2.1.3 aus dem Apple Store funktioniert beim Starten der APP die automtische Cloud Synchronisation nicht. Die App lädt die Tauchgänge aus der lokalen Datei. Es ist nur eine manuelle Synchronisation möglich.
Im Menü lässt sich die automatische Synchronisation zwar einschalten, aber die Einstellung wird nach beenden der APP wieder gelöscht. -->

### Operating system:
<Iphone 5S, Ios 12-->

**Comment by dirkhh** [comment]
Danke fuer den Report.
Der Default "offline" ist in der Tat beabsichtigt, aber die Auswahl der automtischen Synchronisation sollte permanent sein. Hoffentlich ist das einfach zu beheben.
