### ISSUE TITLE
Add/Edit location problem

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#1809]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Issue for @bstoeger. Use my simple 1 dive/2DC logbook example. Select the globe to edit the location. The map window says: drag the selected dive location. But the flag is not selected so you cannot drag. Problem introduced in commit 0aef04352.

### Operating system:
Linux (but not OS dependent)

### Subsurface version:
introduced by commit 0aef04352

### Steps to reproduce:
See above

### Current behavior:
See above

### Expected behavior:
As before this commit. The flag shall be selected to it can be moved.

### Additional information:
maybe some relation to #1804, but as that one a a very non-specific issue, that raises more questions, I decided to make this specific new issue.

### Mentions:
@bstoeger

**Comment by bstoeger** [comment]
Quick fix:
```
diff --git a/map-widget/qmlmapwidgethelper.cpp b/map-widget/qmlmapwidgethelper.cpp
index adaaf8848..4d4596ab7 100644
--- a/map-widget/qmlmapwidgethelper.cpp
+++ b/map-widget/qmlmapwidgethelper.cpp
@@ -302,6 +302,7 @@ void MapWidgetHelper::enterEditMode(quint32 uuid)
        } else {
                coord = exists->coordinate();
        }
+       centerOnDiveSiteUUID(uuid);
        emit coordinatesChanged(degrees_t { (int)lrint(coord.latitude() * 1000000.0) },
                                degrees_t { (int)lrint(coord.longitude() * 1000000.0) });
        emit editModeChanged();
```

I will only be able to analyze this fully on weekend. :( The interaction map-widget / dive location / filter is convoluted.

What happened: Entering location edit mode would set the dive-site filter. That would of course filter out everything [dive site not yet existing?] and deselect all dive-sites. The code above then centers (and selects) the newly generated dive-site. All a bit horrible...
