### ISSUE TITLE
Mac, temps off

### ISSUE THREAD

**Issue by mikecarr** [subsurface/subsurface#181]
Temps seem to be way off, it shows a min temp of 41 degrees, low temp was 56

Subsurface 4.6.0
Hollis DG03

**Comment by dirkhh** [comment]
That's not a lot of information to go on - can you provide more context? Can you post a screenshot of the dive?

**Comment by jbygdell** [comment]
Even better, export the offending dive as XML and upload it.
That way we can see if it is something in the data that supports the low temp reading.

**Comment by johnsgill3** [comment]
Are you sure that it's Subsurface and not the DG03? My dive buddy and I both have DG03's and the temp gauge on his is always 5 degrees cooler than mine.

**Comment by dirkhh** [comment]
no response in 5 weeks
