### ISSUE TITLE
New "Connect to Facebook" is not working

### ISSUE THREAD

**Issue by ChristianMehrer** [subsurface/subsurface#1828]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I want to "Connect to Facebook" to be able to share dives on Facebook. This is not working.

### Operating system:
Windows 7

### Subsurface version:
offical release 4.8.3

### Steps to reproduce:
Always when I try to connect to facebook. 

### Current behavior:
Afterwards "Share on Facebook" is still grayed out.

### Expected behavior:
Connecting works without error. Sharing is possible.

### Additional information:
![grafik](https://user-images.githubusercontent.com/44505258/47579000-23ba8100-d94b-11e8-811b-2ad59bd655c3.png)
![grafik](https://user-images.githubusercontent.com/44505258/47579015-2c12bc00-d94b-11e8-96ab-c6f6b77302e3.png)

**Comment by seanwhe** [comment]
Agreed using Ubuntu Bionic and Chromium Browser

Message received is 
Facebook has detected Subsurface isn't using a secure connection to transfer information.
Until Subsurface updates its security settings, you won't be able to use Facebook to log into it.

**Comment by neolit123** [comment]
we are  removing the FB feature:
https://github.com/Subsurface-divelog/subsurface/pull/1958
