### ISSUE TITLE
Adding dive media files for multiple dives - conceptional issue

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#1844]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [ ] New feature request
- [x] Discussion request

### Issue long description:

When adding my photos and videos for my last dive trip I found a kind of conceptional issue with our current add dive media function. Example scenario:
- 3 dives A, B and C
- 3 sets of media files I, II and III
- Time stamps of media file set I fits dive time of dive A +-30min
- Time stamps of media file set II fits dive time of dive B +-30min
- Time stamps of media file set III fits dive time of dive C but there are files outside the +-30min range for this dive
- I select the dives A, B and C
- I do "Load media files from disk" for these dives
- I select all files (set I, II and III)
- I receive the warning that some files are outside the +-30min range
- I select "Load media files even if the time does not match the dive time"
- Result: For each of the dives A, B and C all the files from set I plus II plus III are added.

Not the desired result but also not unexpected. We have no logic to find out to which dive the files outside the +-30min range belong to and also the files from the other dives are then treated in the same way as files outside the range.
From my point of view it's not so simple to find a "perfect" solution for this.
There is one simple fix: Disable (gray out) the "Load media files even if the time does not match the dive time" as soon as multiple dives are selected. The user would need to add the files outside the +-30min range for every single dive. That sounds acceptable for me.

Any better ideas?

### Operating system:

All

### Subsurface version:

Current master

**Comment by atdotde** [comment]
Sounds good to me.

**Comment by bstoeger** [comment]
Yes - this has annoyed me for a very long time.

**Comment by bstoeger** [comment]
> From my point of view it's not so simple to find a "perfect" solution for this.

Last time I thought about this my plan was to associate the media-file with the dive it's closest to. Of course a problem arises if we can't extract the meta-data properly. For this case, perhaps add a 24-h safeguard?

**Comment by mturkia** [comment]
Usually when I add pics to dives on a dive trip, I just want the matching files to be associated with dives. I select all the dives from the trip, all the pictures during the time and want the pics that occurred during the dives to be matched. In this scenario I am just happy if the pics that are not directly associated with a dive are ignored. Anyway, if it is not possible to select multiple dives, the media handling becomes quite tedious task.

**Comment by bstoeger** [comment]
@sfuchs79: If you find time, could you perhaps check if current master is fine for you? Thx.

**Comment by bstoeger** [comment]
I'm closing this as the behavior in the report (adding the same picture to multiple dives) does not exist anymore. If the new behavior needs adaptations, please reopen or make a new report.
