### ISSUE TITLE
Subsurface-mobile: multiple divemaster entries fail

### ISSUE THREAD

**Issue by kittykat** [subsurface/subsurface#1853]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When I have two divemasters listed in a dive (added using the desktop app) and click edit in the Android app, the field clears automatically and I get left with no divemasters listed.

### Operating system:
Android 7.0

### Subsurface version:
Subsurface-mobile 2.1.4(4.8.3.0) from the Android app store.

### Steps to reproduce:
1) Open Subsurface Linux desktop app (4.8.3) and add two divemasters to a dive.
2) Save to cloud storage from Linux desktop app.
3) Open Subsurface-mobile and "Manual sync with cloud" to download the dive.
4) Look at the dive and see two divemasters listed.
5) Press the edit button at the bottom of the screen and see the divemaster field empty.

### Current behavior:
Subsurface-mobile loses the divemaster info.

### Expected behavior:
Subsurface-mobile supports showing and adding multiple divemasters.

### Additional information:
None, let me know if you need anything.

**Comment by jbygdell** [comment]
Multiple entries for anything than buddies are not implemented in the mobile version. Still, data loss should not happen on edit and needs to be fixed.
