### ISSUE TITLE
Number of dives in trip isn't shown in Subsurface-mobile

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#1867]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

With current master, if I start Subsurface-mobile, all trips are listed as having 0 dives. Filtering and un-filtering fixes that.

### Operating system:

Should be independent - I tested Subsurface-mobile on Mac desktop

### Subsurface version:

master, bug was introduced in 6b283e598a3a08c6133d66b5d5617370296e7d0e

### Steps to reproduce:

1) start Subsurface-mobile with a dive log that has trips in it

### Current behavior:

trips are shown with "0 dives"

### Expected behavior:

correct number of dives should be shown

### Additional information:

bisecting leads me to 6b283e598a3a08c6133d66b5d5617370296e7d0e which clearly changes the code for this. I tried to follow this and haven't figured out why trip->dives->nr would be 0 in this situation. I hope that this will be easier for @bstoeger to spot :-)

### Mentions:

@bstoeger

**Comment by dirkhh** [comment]
I am not claiming that the code before was perfect in all scenarios. I'm claiming that before when I started `Subsurface-mobile` I saw a correct number of dives in each trip. Now I don't.

**Comment by bstoeger** [comment]
Fixed with #1872 (at least according to my humble test).
