### ISSUE TITLE
Website broken link to build instructions

### ISSUE THREAD

**Issue by jakkarth** [subsurface/subsurface#1902]
The page at https://subsurface-divelog.org/documentation/contributing/ contains information about how to contribute to Subsurface. However, it includes a link to https://subsurface-divelog.org/documentation/building/ for more information on building Subsurface, and that page does not exist. I'm not sure if it was renamed or moved or what. If it's gone, I suggest making it a link to this github's INSTALL file, which appear to contain the directions needed.

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

**Comment by dirkhh** [comment]
You are right - we removed the building page as redundant (and constantly out of date). I'll fix this.
