### ISSUE TITLE
Main Menu: Move Share on

### ISSUE THREAD

**Issue by seanwhe** [subsurface/subsurface#1910]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The Share on item in the Main Menu is a feature not a generic menu. Suggest relocation to the Log menu and/or inclusion in context menus within the Dive List or Dive Profile panels.

Move the setup of the Share on into the File>Preferences dialog under Social.

### Subsurface version:

v4.8.4

### Steps to reproduce:

Not Applicable

### Current behavior:

Share on is a main menu

### Expected behavior:

- Move Share on to sub menu Log > Share
- Move Share on config/setup to File > Preferences dialog

**Comment by dirkhh** [comment]
I think that's mostly a matter of taste.
To the best of my knowledge sharing to Facebook is currently broken and no one cares enough to fix it...

**Comment by neolit123** [comment]
my vote goes to removing the "share on facebook" functionality from the code base along with the "share on" menu.

> Then again, is social sharing a core intent behind the software?

i don't think that social sharing has seen much demand or use, so i would say no.

**Comment by neolit123** [comment]
we are  removing the FB feature:
https://github.com/Subsurface-divelog/subsurface/pull/1958
