### ISSUE TITLE
Preferences: Change dialog name

### ISSUE THREAD

**Issue by seanwhe** [subsurface/subsurface#1912]
### Describe the issue:

- [ ] Bug
- [x ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The dialog resulting from File > Preferences is incorrectly named 'Subsurface'. Change the dialog name to 'Preferences'

### Subsurface version:

v4.8.4

### Steps to reproduce:

File > Preferences

### Current behavior:

Dialog name is displayed as 'Subsurface'

### Expected behavior:

Dialog name should display as 'Preferences'

**Comment by dirkhh** [comment]
Fixed
