### ISSUE TITLE
Plan dive: Should be a Main Menu item

### ISSUE THREAD

**Issue by seanwhe** [subsurface/subsurface#1913]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [ ] New feature request
- [x ] Discussion request

### Issue long description:

The Plan dive menu item is actually launching a very comprehensive module. So much so that it could be argued that this menu item should not be under the Log menu but should should be a Main Menu item of its own named Plan.

Since dive planning and dive logging are different tasks, separated in both space and time, it may also be argued that Dive Plans are not a part of the Dive List. They may therefore be either:
- included in the Dive List
- included in a Dive Plan List

If the decision is to include Dive Plans into the Dive List as it currently is implemented, one could suggest that there should exist an easy visual way to distinguish actual dive logs and dive plans from each other. This naturally may also have further feature requests such as the ability to filter these logs by:
- All logs
- Dive logs
- Dive plans

If the decision is to provide separate lists then filtering is such a requirement. However, the ability to associate and compare a plan against a dive (vis-a-versa) would be a good feature that will enable comparison and analysis of how good dive planning was and how closely the dive was to planning (Plan the Dive, Dive the Plan).

### Subsurface version:

v4.8.4

**Comment by dirkhh** [comment]
Interesting idea.
@atdotde - this is your area, thoughts?

**Comment by atdotde** [comment]
I guess it is. Let’s do this next year. Prost Neujahr!

**Comment by atdotde** [comment]
Here are my first thoughts:

* I would love more prominence of the planner in the UI. Having a separate menu with just one ore two entries (plan and edit dive in planner), however, seems a bit weird to me. Will do some testing to see how much I like it.

* Having more than one dive list I guess would be quite a change to Subsurface's internal structure. So on a short time scale, this is unlikely to materialise.

* Currently, planned dives are dives where the dive computer has a special name "Planned dive". A dive can have more than one computer, so in particular, you can have a dive with both a plan and the n an actual readout from a dive computer. By switching between dive computers for that dive you can compare the two versions. For more extensive analysis you can do the "Plan dive in planner" thing with the actual dive.

* If you want to keep your plans separate from your actual dives, you can do that by having two different dive log files. Of course, that way you lose the ability to use the tissue loadings from past dives in the planner and you cannot directly compare dive and plan.

* I think what would be most urgently be required from your suggestions is to filter dives with respect to "real vs planned". Thus I would suggest to aim for that first. I would add two checkboxes for "planned" and "logged" dives (the first selecting dives that have a dive computer called "Planned dive" the second those dives that have a dive computer with a different name). I need to look into the new filter to understand how it works, but that shouldn't be too hard to implement.

What do you think?

**Comment by neolit123** [comment]
> Having a separate menu with just one ore two entries (plan and edit dive in planner), however, seems a bit weird to me. 

+1

**Comment by seanwhe** [comment]
> Here are my first thoughts:
> 
> * I would love more prominence of the planner in the UI. Having a separate menu with just one ore two entries (plan and edit dive in planner), however, seems a bit weird to me. Will do some testing to see how much I like it.
> * Having more than one dive list I guess would be quite a change to Subsurface's internal structure. So on a short time scale, this is unlikely to materialise.
> * Currently, planned dives are dives where the dive computer has a special name "Planned dive". A dive can have more than one computer, so in particular, you can have a dive with both a plan and the n an actual readout from a dive computer. By switching between dive computers for that dive you can compare the two versions. For more extensive analysis you can do the "Plan dive in planner" thing with the actual dive.
> * If you want to keep your plans separate from your actual dives, you can do that by having two different dive log files. Of course, that way you lose the ability to use the tissue loadings from past dives in the planner and you cannot directly compare dive and plan.
> * I think what would be most urgently be required from your suggestions is to filter dives with respect to "real vs planned". Thus I would suggest to aim for that first. I would add two checkboxes for "planned" and "logged" dives (the first selecting dives that have a dive computer called "Planned dive" the second those dives that have a dive computer with a different name). I need to look into the new filter to understand how it works, but that shouldn't be too hard to implement.
> 
> What do you think?

**Comment by seanwhe** [comment]
> > Having a separate menu with just one ore two entries (plan and edit dive in planner), however, seems a bit weird to me.
> 
> +1

LOL Github UI is confusing.

Plan
New dive plan - Start a new dive plan
Edit dive plan - Modify an existing dive plan
Compare dive plan - Compare with another dive plan or an actual dive
Share dive plan - Share a dive plan with a team member.

**Comment by seanwhe** [comment]
> * I would love more prominence of the planner in the UI. Having a separate menu with just one ore two entries (plan and edit dive in planner), however, seems a bit weird to me. Will do some testing to see how much I like it.

Could be but then again have a look at the Edit menu :-)

> * Having more than one dive list I guess would be quite a change to Subsurface's internal structure. So on a short time scale, this is unlikely to materialise.

Yes I would have thought so. It's just a thought but does it have to change the structure? Perhaps it could just be a new structure of its own. So an addition alongside the existing structure.

> * Currently, planned dives are dives where the dive computer has a special name "Planned dive". A dive can have more than one computer, so in particular, you can have a dive with both a plan and the n an actual readout from a dive computer. By switching between dive computers for that dive you can compare the two versions. For more extensive analysis you can do the "Plan dive in planner" thing with the actual dive.

If I understand you correctly you are suggesting using an existing divelog record as the basis upon which to start a dive plan. If that is correct it would be an excellent idea and a major time saver.

> * If you want to keep your plans separate from your actual dives, you can do that by having two different dive log files. Of course, that way you lose the ability to use the tissue loadings from past dives in the planner and you cannot directly compare dive and plan.

My first instinct when using the program was to explore the software and try things. This, without much thought, resulted in me saving a dive plan. It was only then that I discovered that the dives and plans where all in one list and not distinguished from one another.

Keeping it in one place sounds better and less work with greater payoffs later.

> * I think what would be most urgently be required from your suggestions is to filter dives with respect to "real vs planned". Thus I would suggest to aim for that first. I would add two checkboxes for "planned" and "logged" dives (the first selecting dives that have a dive computer called "Planned dive" the second those dives that have a dive computer with a different name). I need to look into the new filter to understand how it works, but that shouldn't be too hard to implement.

Yes. To enhancement of the filter.

Thanks for your consideration.

**Comment by SeppoTakalo** [comment]
I came here to report almost the same feature request:
* Dive planning should be separated from a log.
* Saving a dive plan should not create a new log entry. Instead it should be just a way to store a plan and re-edit it later.
   I often plan dives to 60m - 100m region on CCR using 5 gasses. It is frustrating to start each plan from the scratch
   by feeding in 5 standard gasses that are same as last time, etc etc..
* Creating a divelog entry from a plan should be a separate function, like "Import plan as a dive".

Last, which was already discussed:
* It would be extremely useful if I can import a downloaded dive profile into a planner, so it would get the depth and used gasses. Then the profile would be, for example split in 10 minutes segment, or something, that I can alter the gasses and see just the deco phases re-calculated, but the actual bottom time and its profile would be the same as imported from computer. I would just remove the deco from the imported profile, and re-calculate.

**Comment by mikeller** [comment]
Thanks for your feedback, @SeppoTakalo .

> I came here to report almost the same feature request:
> 
> * Dive planning should be separated from a log.

I think pretty much all of @atdotde's comments in https://github.com/subsurface/subsurface/issues/1913#issuecomment-450721826 still stand. In particular the one about changing Subsurface to have two separate dive lists for 'planned' and 'actual' dives being a big undertaking. And from the looks of it none of the core contributors of Subsurface has got the time available and / or motivation to tackle this. Which does not mean that somebody outside of this group isn't welcome to start working on this...

> * Saving a dive plan should not create a new log entry. Instead it should be just a way to store a plan and re-edit it later.
>   I often plan dives to 60m - 100m region on CCR using 5 gasses. It is frustrating to start each plan from the scratch
>   by feeding in 5 standard gasses that are same as last time, etc etc..

This is already somewhat covered - if you select an existing (planned or actual) dive in the dive list before selecting 'Plan dive', the gas list for the dive plan will be copied from this dive. So you can always select your last dive plan (or a template specifically created for this) to get your gas list populated.

> * Creating a divelog entry from a plan should be a separate function, like "Import plan as a dive".

Is this assuming that a list of planned dives that is separate from the list of actual dives has been implemented? If not then 'Save' in the dive planner does exactly that.

> * It would be extremely useful if I can import a downloaded dive profile into a planner, so it would get the depth and used gasses. Then the profile would be, for example split in 10 minutes segment, or something, that I can alter the gasses and see just the deco phases re-calculated, but the actual bottom time and its profile would be the same as imported from computer. I would just remove the deco from the imported profile, and re-calculate.

'Log' / 'Edit dive in planner' does something like this - I have never used it, and I don't know how useful it is for your use case, but you could give it a spin and then provide feedback on what can be done to improve it.

**Comment by SeppoTakalo** [comment]
> >   I often plan dives to 60m - 100m region on CCR using 5 gasses. It is frustrating to start each plan from the scratch
> >   by feeding in 5 standard gasses that are same as last time, etc etc..
> 
> This is already somewhat covered - if you select an existing (planned or actual) dive in the dive list before selecting 'Plan dive', the gas list for the dive plan will be copied from this dive. So you can always select your last dive plan (or a template specifically created for this) to get your gas list populated.

This does not seem to work. I copies only the first gas, not BO gasses.

> 'Log' / 'Edit dive in planner' does something like this - I have never used it, and I don't know how useful it is for your use case, but you could give it a spin and then provide feedback on what can be done to improve it.

Perfect. I did not know about this.
This is exactly what I was looking for. This seem to copy all gasses and the exact profile. No I can just delete the deco part and re-plan with different gasses.

**Comment by mikeller** [comment]
> This does not seem to work. I copies only the first gas, not BO gasses.

That's curious - in my tests this always copies all of the gases listed for the selected dive - do you have a dive that you get this behaviour for that you can share the log file for?

**Comment by SeppoTakalo** [comment]
> > This does not seem to work. I copies only the first gas, not BO gasses.
> 
> That's curious - in my tests this always copies all of the gases listed for the selected dive - do you have a dive that you get this behaviour for that you can share the log file for?

Here is an example:
[2024-04-20 Montola CCR.zip](https://github.com/subsurface/subsurface/files/15220308/2024-04-20.Montola.CCR.zip)

It is an CCR dive with 1 diluent gas and 3 bailout gasses.
If you click "Plan dive" with this one selected, only the diluent gas is imported.
If you click "Edit dive in planner" all gasses seem to be imported.

**Comment by atdotde** [comment]
@SeppoTakalo do you have "Show unused cylinders in the Cylinders table of the Equipment tab" in the equipment preferences checked? Once you have, also your (unused) bailout cylinders should show up when planning a new dive (for me this checkmark makes the difference for this case).

**Comment by SeppoTakalo** [comment]
> @SeppoTakalo do you have "Show unused cylinders in the Cylinders table of the Equipment tab" in the equipment preferences checked? Once you have, also your (unused) bailout cylinders should show up when planning a new dive (for me this checkmark makes the difference for this case).

No I did not have. That fixed it. Thanks.
