### ISSUE TITLE
Issues Importing from Garmin Descent Mk 1

### ISSUE THREAD

**Issue by UncleConker** [subsurface/subsurface#1914]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I am unable to download dives from the Garmin Descent Mk 1 on my Windows 10 pc.

### Operating system:
Subsurface 4.8.4.0
Operating system: Windows 10 (10.0)
Microsoft Surface Pro 3
CPU architecture: i386
OS CPU architecture: x86_64
Language: en-US

### Subsurface version:
4.8.4.0
Does this happen on other versions: Not sure
Is this an official release?: Yes

### Steps to reproduce:
1) Hover over Import tab
2) Click Import from Dive Computer
3) Select "Garmin" and "Descent Mk 1"
4) Select appropriate USB port
5) Click download

### Current behavior:
Recieve window "Error Unable to open D://(Garmin) Garmin (Descent Mk 1)

### Expected behavior:
Dives should show in list to right of "Download" button and be selectable for final import.

### Additional information:
![screenshot 189](https://user-images.githubusercontent.com/46288887/50569242-375cdc00-0d2e-11e9-9753-90233dcd87d1.png)

**Comment by dirkhh** [comment]
Don't select a USB port. When you connect the Garmin it should connect as `D:\Garmin`
Enter `D:\` in that case.
The `...` menu allows you to find the right mount point.
