### ISSUE TITLE
Check for updates: server side broken

### ISSUE THREAD

**Issue by seanwhe** [subsurface/subsurface#1918]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When performing a "Check for updates" the following error is returned.
Subsurface was unable to check for updates.
The following error occurred:
Error transferring http://subsurface-divelog.org/updatecheck.html?os=linux&version=4.8.4.124&uuid=999a51fc-691e-4f97-98f3-13bfbe8602a3 - server replied: Proxy Error

### Subsurface version:

v4.8.4

### Steps to reproduce:

Help > Check for updates

### Current behavior:

The following error occurred:
Error transferring http://subsurface-divelog.org/updatecheck.html?os=linux&version=4.8.4.124&uuid=999a51fc-691e-4f97-98f3-13bfbe8602a3 - server replied: Proxy Error

### Expected behavior:

Return information as to current version and whether there is a new version available

**Comment by neolit123** [comment]
works for me. are you behind a proxy by any chance?
preferences -> network has a proxy setup.

**Comment by dirkhh** [comment]
Nope, my backend processing was crashing and I fixed it a few minutes ago.
The bug report was correct, I just already addressed the issue
