### ISSUE TITLE
Preferences>General: Change Dives group name to Log Files

### ISSUE THREAD

**Issue by seanwhe** [subsurface/subsurface#1919]
### Describe the issue:

- [ ] Bug
- [x ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

File > Preferences > General defines a Group named Dives. This group name can be improved to be more generic and in so doing provide a more accurate description of the intent for the group of settings.
Suggestion may include:
- Files
- File locations
- Log files
- Log file locations

### Subsurface version:

v4.8.4

**Comment by neolit123** [comment]
> File > Preferences > General defines a Group named Dives. 

this group is about the default file functionality and should be called in the lines of "Default file".
