### ISSUE TITLE
No images in profile export

### ISSUE THREAD

**Issue by atdotde** [subsurface/subsurface#1963]
When exporting the dive profile (as done in TeX export or the new #1962), the images are not shown in the profile, only some default camera icon. This is a regression.

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Subsurface version:

Current master as well as at least 4.8.4

### Steps to reproduce:

Select a dive with image thumbnails in the profile and do TeX export.

### Mentions:

@bstoeger do you have any idea?

**Comment by atdotde** [comment]
That was my suspicion as well. I tried waiting for three seconds after creating the widget. That should have been more than enough time for the thumbnails to load. That did not help.

**Comment by bstoeger** [comment]
I'm stupid - I had the picture thumbnails turned off. 😛

**Comment by bstoeger** [comment]
> I tried waiting for three seconds after creating the widget. 

How? I think if you simply call `sleep()`, Qt's main loop will not run and the UI thread can't update the thumbnails. You would have to pass control to the main loop for a certain amount of time. IIRC, there's a special process signals call for QThread.

**Comment by dirkhh** [comment]
We have code to do this the right way in quite a few places. E.g. `CheckCloudConnection::checkServer()`

**Comment by bstoeger** [comment]
I chose to implement a "synchronous" mode, which will not do video thumbnail extraction or download files. This should not be a problem, as the thumbnails should have been created on addition of the files. 

So far so good. But now if you export multiple dives, they will all show the same thumbnails on different profiles. Will look into that tomorrow.

**Comment by atdotde** [comment]
Indeed, sleeping with the event loop running does the job. Now, we need to figure out how to send a signal once the last thumbnail has loaded (or we give up).
