### ISSUE TITLE
Editing date in 'Info' does not correctly change date in 'List'

### ISSUE THREAD

**Issue by ec-pete** [subsurface/subsurface#1979]
### Describe the issue:

- [ X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When using the dropdown to change a dive date, the correct date shows up in the "info" dropdown but the date in the "list" is incorrect. It seems to randomly change.
I've tried editing the date in the field as well as using the calendar. Both do not update the date in the list properly.
Specifically when I change the year, it goes forward or backwards by years. Changing months go forward/backward months.

### Operating system:
Win10 English
Desktop

### Subsurface version:
4.8.5
Unsure. Have not edited the date before.
Official

### Steps to reproduce:

1) choose any dive
2) in the "info" tab, change the date
3) click on "apply changes"
4) note date is different in dive list.
### Current behavior:

Date in dive list is not same as what is entered
### Expected behavior:

Dive list should contain date entered

**Comment by dirkhh** [comment]
This should be a duplicated of #1975 which was just fixed in master. The next release will address the issue (or I can show you how to run one of our daily test builds)
