### ISSUE TITLE
Increase altitude in planner

### ISSUE THREAD

**Issue by basepr1me** [subsurface/subsurface#201]
Is there a reason the limit is 3000 on the altitude in the dive planner? I, and my team, regularly dive in the 6000+ altitude. Recommend increasing limit to 10000.

**Comment by basepr1me** [comment]
P.S. this is in feet.

**Comment by glance-** [comment]
The limit is intended for the default(sane) unit meters in desktop-widgets/diveplanner.ui. The limits on the spinbox needs to be updated as well as the unit in desktop-widgets/diveplanner.cpp:197

**Comment by dirkhh** [comment]
is a pull request for this coming, @glance- ? We could fix this for 4.6.2

**Comment by glance-** [comment]
Patch on the mailing list. git send-email was shorter to write. I should setup hub any year now.

**Comment by basepr1me** [comment]
Cool. I'll clone and test when I get back from Florida. Lots and lots of wrecks for the next week! :D
