### ISSUE TITLE
Font size in planner -> planner details

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#203]
If one changes in preferences the font and font size for tables and lists this is applied almost everywhere but not in the planner window on the planner result.
But exactly there it would be also very nice to be able to select a smaller font size.

![grafik](https://cloud.githubusercontent.com/assets/25316050/22897629/b2f1c8e8-f224-11e6-98c5-db72fa9ce72b.png)

**Comment by dirkhh** [comment]
This is now fixed, correct?
