### ISSUE TITLE
Literal Characters error

### ISSUE THREAD

**Issue by jseguin11** [subsurface/subsurface#2043]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When accessing the Cloud options and clicking on Apply, I get the following warning message:
TITLE: Literal characters 
DESC: Non-special character(s) in time format.
These will be used as is. This might not be what you intended. See http://http://doc.qt.io/qt-5/qdatetime.html#toString

I was only putting in my email and password for Cloud Storage. My email contains a dash "-". my password was alphanumerical. I did receive the warning message again when entering the PIN.

I got the email and entering the PIN seems to work as it shows "credentials verified", but get the red bar on the main page to enter my PIN "Please configure Cloud storage email and password in the preferences". Not sure if I actually configured the Cloud Storage properly...

### Operating system:
Windows 10

### Subsurface version:
4.8.5 (official)

### Steps to reproduce:
0) New install (I guess)
1) Network Settings
2) enter email and password
3) click Apply

### Current behavior:
Warning message:
TITLE: Literal characters 
DESC: Non-special character(s) in time format.
These will be used as is. This might not be what you intended. See http://http://doc.qt.io/qt-5/qdatetime.html#toString

### Expected behavior:
No warning

![Capture](https://user-images.githubusercontent.com/36050303/56035439-3279d200-5cf8-11e9-9750-0cbae4b10495.JPG)

**Comment by atdotde** [comment]
This warning has nothing to do with the cloud storage. It is about the time format in the language tab. If you like the way times are printed, it is save to ignore it.
