### ISSUE TITLE
Cylinder table header is not translated

### ISSUE THREAD

**Issue by ssttaarr** [subsurface/subsurface#206]
Checked it for three locales (ru_RU, bg_BG, de_DE) against git master, distro supplied version (4.6.1-1~xenial @ Linux Mint 18.1) and official Subsurface-4.6.1-x86_64.AppImage.

Any clue?

**Comment by sfuchs79** [comment]
I only can confirm this. I tried to have a look at it and even thought I found s.th.
Here:
setHeaderDataStrings(QStringList() << "" << tr("Type") << tr("Size") << tr("Work press.") << tr("Start press.") << tr("End press.") << tr("O₂%") << tr("He%")
						 << tr("Deco switch at") <<tr("Bot. MOD") <<tr("MND") << tr("Use"));
There is no tr() for the first empty string. This is the only difference I identified up to now compared to e.g. the weight system table.
But changing it doesn't solve the issue :-(
We need an expert here...
