### ISSUE TITLE
Can not edit dive site location on map

### ISSUE THREAD

**Issue by djunkins** [subsurface/subsurface#2076]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When editing a dive site from the dive site tab, I can no longer drag the flag on the map to update the lat/long of the dive site location.

### Operating system:

OSX 10.14.4
### Subsurface version:

* master          9bb7bbef8 [origin/master] Support for Scubapro G2 HUD discovery via bluetooth

### Steps to reproduce:

1) Navigate to dive site tab
2) Select the site to be edited
3) Enter edit mode
4) Attempt to drag flag on the site
### Additional information:

It looks like the grayed out flag for sites that do not have any dives associated with them is missing and the map is not moving to the location of those sites when you attempt to edit them as well.

### Mentions:

@bstoeger

**Comment by bstoeger** [comment]
Analysis:
1) On the dive-site tab a filter is active.
2) Switching the tab to the dive-site-edit tab resets the filter.
3) This emits `filterFinished`
4) `filterFinished` is connected to `MapWidget::reload()`
5) `MapWidget::reload()` exits edit mode and therefore the flag can't be dragged.

I think 4) is wrong, but I'm quite certain that this was introduced to fix problems with the map-edit mode. This will probably take some thinking. That's all horrible spaghetti code!

**Comment by bstoeger** [comment]
Actually I think 5) is wrong.
