### ISSUE TITLE
Crash in MainTab::updateDiveInfo()

### ISSUE THREAD

**Issue by djunkins** [subsurface/subsurface#2077]
[subsurface-crashinfo.txt](https://github.com/Subsurface-divelog/subsurface/files/3125169/subsurface-crashinfo.txt)

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Subsurface crashes when trying to select all dives (Command-A) when no dive is currently selected and in the dive sites tab.

### Steps to reproduce:

1) Click on Dive sites tab
2) Select a dive site
3) Click below the list of dives for that site to deselect dive
4) Hit Command-A to select all dives
5) Subsurface crashes

### Additional information:

Possibly related to #2046 but it does not wait for exit to crash

**Comment by bstoeger** [comment]
As a starting point: It seems to me that the trips returned in `QList<dive_trip_t *> DiveListView::selectedTrips()` are not valid. This will also need some more analysis.
