### ISSUE TITLE
Divelist sorting is wrong when date/time info is the same

### ISSUE THREAD

**Issue by RasmusAaen** [subsurface/subsurface#2086]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I just imported a lot of dives from a CSV file. The dives have Dive# and date, but no time information, so the import uses the current time as the dive time. This means that I end up with several dives with the same date/time info but different dive#.
Even though I select the Dive# as sort option, the list is still sorted by the date/time info:
![image](https://user-images.githubusercontent.com/17901350/57302013-8a7add00-70da-11e9-9f51-2d97095ce10a.png)
 
The only way to get the sorting correct is to change the time info on the dive.

### Operating system:

Running Windows 10 1803 English.

### Subsurface version:

4.8.6

### Steps to reproduce:

Import a list of dives with several dives on the same date and no time info.

**Comment by bstoeger** [comment]
Could you perhaps try #2090? Thank you.
