### ISSUE TITLE
Bugs in manual dive entry profile and dive duration.

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#2128]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When adding a dive by hand, one should be able to edit the dive profile on the profile panel as described in section 5.1.1 of the user manual. This currently does not happen. In fact it appears there are two bugs:

1) See attached image. The default profile of 15m for 45 minutes shows a crazy profile that is not useful to anyone. The descent rate to 15m should be in the order of 20m/min, NOT 15m/22min. Similarly the default ascent rate should be around 10m/min. The profile should have a square shape, not a triangular shape.

2) The normal red cross-haired cursor and the white points on the vertices of the profile are gone so that the default profile cannot be edited on the profile panel. See section 5.1.1 in user manual.

The dive time value in the Notes tab appears to be involved in these anomalies. If one retypes the 45 minutes, then the dive profile becomes "normal".

### Operating system:
 Ubuntu 18.04
 i7 laptop

### Subsurface version:
 latest master

 compiled amster

### Steps to reproduce:

Start up Subsurface
Select Log -> Add dive

**Comment by dirkhh** [comment]
You need to right-click on the profile and go to `Edit profile` to be able to edit the profile in place; then you get the red crosshair. But with the fix in #2130 the issue with the bogus descent/ascent rate is fixed.
