### ISSUE TITLE
Device shortcuts do not include BT selection

### ISSUE THREAD

**Issue by mturkia** [subsurface/subsurface#2139]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The device download shortcuts do not include bluetooth selection.

### Operating system:

Tested on Linux, but any desktop OS.

### Subsurface version:

git master

### Steps to reproduce:

If you have already downloaded from USB and BT DCs before, you are good to go.

- Click shortcut for downloading from BT DC
- Make sure the BT DL selection is ticked
- Click button to download from USB/serial DC
- Not the selection for BT DL is not changed

(works also the other way, and BT DL checkbox is not checked when using the BT DC DL button)

### Current behavior:

BT DL checkbox is not changed

### Expected behavior:

BT DL checkbox reflects the correct selection for the specific DC download button. I.e. is ticked when the download with specific DC was using BT the last time.

**Comment by dirkhh** [comment]
Definitely something that should be fixed. I'll look into it.
