### ISSUE TITLE
Bug: not possible to unset location

### ISSUE THREAD

**Issue by kittykat** [subsurface/subsurface#2148]
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Once filled, it's not possible to make the location blank (unset) again.

### Operating system:
Linux en_GB on a laptop

### Subsurface version:
4.8.4-663-g5c1446a87acb

### Steps to reproduce:
1) Create a new entry
2) Go into the "Location" field
3) Set a dive location
4) Delete the dive location
5) Save changes

### Current behavior:
The set dive location is still shown even after the field was cleared

### Expected behavior:
The location is blank (as is currently happening in 4.8.6).

**Comment by bstoeger** [comment]
Can confirm, looking into it.
