### ISSUE TITLE
Feature request: add export/import of locations

### ISSUE THREAD

**Issue by kittykat** [subsurface/subsurface#2149]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
When I do a liveaboard with buddies who also use Subsurface, I would like to be able to share the dive site data with them so that we're not all having to enter it manually as that is quite tedious for 20+ dive sites.

### Operating system:
For the desktop version

### Subsurface version:
4.8.6

### Current behavior:
It's not possible to export or import locations.

### Expected behavior:
I would like to be able to export all locations or specific ones that could then be imported by another user.

**Comment by bstoeger** [comment]
If I remember correctly, @djunkins implemented that recently...? There should be an "Import dive sites" option in the main menu.

**Comment by djunkins** [comment]
@kittykat Exporting and importing of dive sites are in the current master branch. I believe they will be in the 4.9 general release when it comes out.

**Comment by kittykat** [comment]
@djunkins Can confirm it works from master! Really happy to see the feature
