### ISSUE TITLE
CSV Export: Water temperature column always empty

### ISSUE THREAD

**Issue by h3llra1ser** [subsurface/subsurface#2169]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When you export the dive details to CSV, the water temperature column always is an empty string

### Operating system:

Win7 + Linux, both behave the same

### Subsurface version:

V 4.8.6 official

### Steps to reproduce:

Export dive details (not the dive profile) as CSV and look at the water temperature column contents

### Current behavior:

empty output

### Expected behavior:

some temperature :)

**Comment by bstoeger** [comment]
Doesn't happen with my log. But water temperature is strange, as an average of the dive computers is calculated. So it might have to do something with your particular log. Could you post a minimal example?

**Comment by h3llra1ser** [comment]
Sure, picked a random dive and attached xml and csv.
But this happens on all of my recorded dives when exporting to csv - within subsurface everything is alright (dive profile temperature graph and average temp field)

[temperature_export_example.zip](https://github.com/Subsurface-divelog/subsurface/files/3379847/temperature_export_example.zip)

**Comment by bstoeger** [comment]
Weird I have two logs from very different setups which work, but your's doesn't. And it's not immediately obvious where the difference is. Moreover, I don't understand how temperature is treated in `xslt/xml2csv.xslt`. Therefore assigning to @mturkia.
