### ISSUE TITLE
Notes field doesn't get cleared on "New logbook"

### ISSUE THREAD

**Issue by glance-** [subsurface/subsurface#2172]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When opening a new logbook, a greyed out version of the last show notes filed is still shown.

### Subsurface version:

master, 92dc441f02c73a972dddf9076e438f19b03708b8

### Steps to reproduce:

Open a logbook, ./subsurface dives/test1.xml , hit ctrl-n

### Current behavior:

The last shown notes are still there, but greayed out.

### Expected behavior:

That the notes filed gets cleared like all other fields.

**Comment by bstoeger** [comment]
Fix posted in #2173.
