### ISSUE TITLE
Trip date not correct on Trip notes page

### ISSUE THREAD

**Issue by djunkins** [subsurface/subsurface#2207]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When clicking on a trip in the dive list, the date in the Trip Notes page is not being updated to the selected trip. The trip date appears to remain on the date of the last individual dive selected even if that dive was not part of the trip.
### Operating system:

Mac OSX 10.14.5
### Subsurface version:

Tested on 4.9.0 and 4.9.1 and both exhibit this behavior.

### Steps to reproduce:

1) Select a dive in the dive list
2) Show the Notes page for the selected dive
3) Select a trip in the dive list
4) Observe that the date in the Trip Notes page remains displaying the date of the previously selected dive.

### Expected behavior:

The correct trip date should be displayed in the Trip Notes page.

**Comment by bstoeger** [comment]
Thanks for the report - I will try to find the problem in the upcoming days.

**Comment by djunkins** [comment]
I've been looking at it a bit, but I am having trouble. I would expect that in MainTab::updateDiveInfo() in maintab.cpp we would update the ui.dateEdit field somewhere around line 495. The problem is that there is no date feild in the "struct dive_trip" defined in core/trip.h. I guess we need to generate a date from the dives included in the trip?

**Comment by bstoeger** [comment]
I have a patch that fixes this, will post a PR after dinner. For trips there is the trip_date() function.
