### ISSUE TITLE
Android crash in DiveSiteSortedModel::allSiteNames

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#2222]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Backtrace:
```
  #00  pc 000000000022d2a8  /data/app/org.subsurfacedivelog.mobile-2DwhJ8aKhN2G5g4SWRa4rA==/lib/arm64/libsubsurface-mobile.so (DiveSiteSortedModel::allSiteNames() const+204)
  #01  pc 000000000020686c  /data/app/org.subsurfacedivelog.mobile-2DwhJ8aKhN2G5g4SWRa4rA==/lib/arm64/libsubsurface-mobile.so
  #02  pc 00000000002086a4  /data/app/org.subsurfacedivelog.mobile-2DwhJ8aKhN2G5g4SWRa4rA==/lib/arm64/libsubsurface-mobile.so (QMLManager::qt_metacall(QMetaObject::Call, int, void**)+88)
  #03  pc 0000000000259d28  /data/app/org.subsurfacedivelog.mobile-2DwhJ8aKhN2G5g4SWRa4rA==/lib/arm64/libQt5Qml.so
```

### Operating system:

Android 9

### Subsurface version:

4.9.0.35

### Mentions:

#2219 was supposed to fix this one - haven't seen it recur in the new version

**Comment by bstoeger** [comment]
There is now code that prevents us from accessing invalid indexes. If it still crashes, this means that the internal model state got messed up. This happened before with Qt proxy-models, so it's not completely unlikely.

Leaving open.
