### ISSUE TITLE
Cannot open existing local git repo

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#2236]
When saving a local git repo, one can afterwards go to File->Open and the git repo is in the list of recently used dive logs. However, if one exits Subsurface and restarts it, the repo is not listed in the list of recently used dive logs any more. When trying to open an existing repo, there is (at least in Gnome) not a facility to type any file name. This makes it impossible to open the repo after saving it.

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Operating system:

Subsurface V 4.9.1 on Ubuntu 18.04

### Mentions:

@dirkhh

**Comment by dirkhh** [comment]
I can confirm both parts of this.
Admittedly, local git repos aren't really a "user" feature, but we should try to make this work better.
The Gnome File-Open dialog that doesn't offer an entry field for the file name is... __special__
The fact that we don't keep the repo around as "recent" file is the most annoying in all the annoying things here.
The immediate workaround is to start Subsurface from the command line like this
`subsurface <path>/<folder>/[branch]`
i.e. in my example
`subsurface ~/.subsurface/localrepo/\[test\]`
(you need the backslashes to avoid the shell thinking that these are file glob markers)

**Comment by dirkhh** [comment]
I forgot - the "not having a file name entry field" is considered a feature... this makes opening repos from within the app impossible. But at least now they are stored in recent files
