### ISSUE TITLE
crash with "Save dive data as subtitle"

### ISSUE THREAD

**Issue by fmatray** [subsurface/subsurface#2251]
### Describe the issue:
- [ X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Crash (SIGABORT) with "Save dive data as subtitle"

### Operating system:
Mac OS 10.14.5 French (Up to date)

### Subsurface version:
Subsurface 4.9.1

### Steps to reproduce:
- Select a dive with media
- Right Click on "Save dive data as subtitle"
-> crash with sigabort

### Current behavior:
Crash

### Expected behavior:
Having the subtitles

### Additional information:
prometheus:MacOS $ ./Subsurface -v -v -v 
[...]
item  QDeclarativeGeoMapQuickItem(0x7fa69f583370, parent=0x0, geometry=152.828,44.6996 32x32)  still referenced
Subsurface(16750,0x11b3fc5c0) malloc: *** error for object 0x7ffee2401060: pointer being freed was not allocated
Subsurface(16750,0x11b3fc5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
prometheus:MacOS $

**Comment by atdotde** [comment]
Could you share the dive file (via export) with me so I can have a look? helling@atdotde.de

**Comment by bstoeger** [comment]
Can reproduce - will look into it.
