### ISSUE TITLE
Feature of identifying old planner notes in dive notes defect

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#2264]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

There was once a feature which automatically identified old planner notes in planned dive notes.
It was/is implemented here:
https://github.com/Subsurface-divelog/subsurface/blob/master/qt-models/diveplannermodel.cpp#L1130

But this feature needs the global variable "disclaimer" holding the translated disclaimer text.

And filling this global variable was removed here:
https://github.com/Subsurface-divelog/subsurface/commit/a4834e198d55d50a44d6f80e2137777b64652ce7#diff-0df10959bbcbe5342528360ce6f541a5L116

We please should have a look together how to make this work again :-)

### Subsurface version:

Current master

### Mentions:

@atdotde @bstoeger

**Comment by bstoeger** [comment]
Do I understand correctly that it is supposed to remove the old disclaimer when replanning a dive?

But how did that even work if it depends on the type of the previously planned dive? That appears extremely brittle to me.

Do you have any suggestion how to fix that?

**Comment by sfuchs79** [comment]
Fixed by #2274
