### ISSUE TITLE
Selected dive sites export is confusing

### ISSUE THREAD

**Issue by fmatray** [subsurface/subsurface#2275]
#1637 # Describe the issue:
- [ ] Bug
- [X] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I select several dive sites in "dive sites" and try to export (File -> Export -> Subsurface dive sites XML) selected dives. The first dive site is exported only.

As I selected several dive sites, I expect to have those exported.
To make it work, I have to select dives after dive sites selection.

This is a bit confusing. When I select several dive sites, I expect to have related dives selected also.

### Operating system:
MacOS Mojave

### Subsurface version:
Subsurface 4.9..1

### Steps to reproduce:
1) Select several dive sites
2) File -> Export
3) Chose "Subsurface dive sites XML" and "selected dives"
4) Export

### Current behavior:
One dive site exported

### Expected behavior:
Selected dive sites exported

### Additional information:
![Capture d’écran 2019-09-03 à 23 51 16](https://user-images.githubusercontent.com/8267716/64211303-0ed14700-cea6-11e9-8c07-82f8564b5f9b.png)

[sainte maxime.xml.zip](https://github.com/Subsurface-divelog/subsurface/files/3571783/sainte.maxime.xml.zip)

**Comment by bstoeger** [comment]
Yes, that's silly. I haven't looked into this, but I suspect that the problem is that the export works from normal-mode and from dive-site-mode.

@dirkhh: What do you think: should we change the export logic if on the dive-site-tab? Or perhaps select all dives while the dive-site-tab is active?

**Comment by dirkhh** [comment]
When opened from the dive site screen it should be "export selected dive sites", right?

**Comment by bstoeger** [comment]
That appears logical, yes. Since the dialog is modal, we can change it depending on where it was called.

**Comment by djunkins** [comment]
Sorry — I’ve been distracted with other things for the last several weeks. I can look at this early next week if you want.

-Doug

**Comment by bstoeger** [comment]
Fix attempt in #2293, though the UI is not clear about what is going on. This could still need some work.
