### ISSUE TITLE
Subsurface 4.9.3 - No more Dive suit field on the screen

### ISSUE THREAD

**Issue by msd3287** [subsurface/subsurface#2294]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I just upgrade Subsurface from 4.8.6 to 4.9.3.
When I open my log book I can't see anymore field "Drive suit" (Combinaison , in french).
I tried to install 4.9.1 in replacement and, than, the field is there visible (see  print screens below)
1) 4.9.1 with field "Combinaison"
![Bug no more dive suit field 4-9-1 = OK](https://user-images.githubusercontent.com/55650518/65384489-4dc71f80-dd23-11e9-9c9d-523367a70128.JPG)

2) 4.9.3 without field "Combinaison"
![Bug no more dive suit field 4-9-3 = notOK](https://user-images.githubusercontent.com/55650518/65384490-4e5fb600-dd23-11e9-9678-84ad59488e80.JPG)

- Another point: 
1) the old filter screen (4.8.x) was better and more user friendly than the actual one (4.9.x) as previously it was possible to chose within the existing labels what to filter but, now (4.9), you have to fully write what you want to filter.
2) in the old filter screen you saw directly the total of dives corresponding to the criteria. But, in 4.9, I didn't see this total anywhere.
### Operating system:
 Windows 10 Family 1903 64 bits (french )
 

### Subsurface version:
 4.9.3
 No (4.9.1 & 4.8.6)
 official

**Comment by dirkhh** [comment]
Check the equipment tab.

**Comment by msd3287** [comment]
Ok, thanks. 
Didn't see there.
