### ISSUE TITLE
Subsurface-mobile not syncing with Android 5.0.1 mobile phone anymore

### ISSUE THREAD

**Issue by bcogel** [subsurface/subsurface#2311]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Subsurface-mobile on Android phone fails to login into cloud storage. Message:
"Keine Antwort des Cloud-Servers zur Validierung der Anmeldeinformationen"
### Operating system:

Android 5.0.1, German 

Samsung S4 Active

Works fine on Lenovo Yoga Book with Android 7.1.1, German
### Subsurface version:

Subsurface-mobile 2.2.2(4.9.3.106)

A previous version worked fine. Don't know which...

Official Build from Play Store

### Steps to reproduce:

Trying to login to cloud storage
### Current behavior:

Login fails with "Keine Antwort des Cloud-Servers zur Validierung der Anmeldeinformationen"
### Expected behavior:

Login and Sync
### Additional information:

To check if my credentials on the device are correct, I changed the cloud password in Subsurface on my linux computer and tried to connect my phone with the new password. Fail... 
Then I uninstalled and reinstalled the app on the mobile phone. No success. 
Then I did the same on my tablet. Success. I was able to get the cloud data on the tablet.
So this seems to be a communication problem. SSL...TLS... Something that isn't supported on old Android versions? 

I've activated the developer tools. The application log shows

verify credentials for email .... (no PIN)
QSslSocket::connectToHostEncrypted: TLS initialisation failed

Hmmmm.... I don't want to by a new mobile phone while the old one is still working and is fast enough for my usecases..... even if there will be no Android update from Samsung...

**Comment by dirkhh** [comment]
This is a known bug in the current production version.
If you switch to the beta channel (you can opt in to receive beta versions right on the device in Google Play) I just released (quite literally a few hours ago) a new beta version that should work again on Android 5.x
I'd love to hear if that fixes the issue for you!
