### ISSUE TITLE
Rounding of numbers. Accumulation of errors.

### ISSUE THREAD

**Issue by Marquentein** [subsurface/subsurface#2317]
### Describe the issue:
Dive depth rounding error from 20 meter and more.
Dive time  rounding error + corrupt dive time import error

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When I manually enter a new dive with a dive depth of 20 meter and more, the windows program as well as the android app refuses to retain the entered decimal value, but round the depth and discard the decimals.

Entering dives at 19,9 meter or shallower will retain the decimal.

When I manually enter seconds in the dive time then the correct minutes and seconds are retained. However... when the dive is shown in the duration column, the dive time is rounded. 

The yearly statistic (CTRL+Y) is based in these incorrect rounded numbers, thus accumulating the rounding errors.

When I import my dive from my Suunto EON Core (firmware 1.6.5), the dive depth rounding error persists.

Furthermore I have observed, that the imported dive times are corrupted.

When importing my dives through Suuntos own DM5 software as well as the Suunto android app, I get the following dive times for 5 dives:

#1 = 0:32:15
#2 = 0:29:21
#3 = 0:52:19
#4 = 0:26:19
#5 = 0:23:38

When importing the exact same dives through Subsurface I get these dive times (extracted from a SSRF file):

#1 = 0:32:57 (off by +42 sec)
#2 = 0:30:40 (off by +79 sec)
#3 = 0:52:41 (off by +22 sec)
#4 = 0:26:52 (off by +33 sec)
#5 = 0:23:48 (off by +10 sec)

So, with dive time I have 2 sequential errors:
First, the correct dive time is not imported. Second, the corrupted dive time is then rounded anyway, which accumulates in the yearly statistic.

### Operating system:
Windows 10
Android 9.0.9

### Subsurface version:
Windows program (v4.9.3)
Android app (v2.2.2) 

### Expected behavior:
If my dive computer says, that I have been diving to 25,6 meters, I would like my Dive Log to reflect that accurately. 26 meters is false no matter how negligible the error.

If my dive computer says, that I have been diving for 0:25:15 (25 min, 15 sec) I would like, that the import does not add random phantom seconds IE. to 0:25:32 and afterward skews the time by rounding up to 26 minutes.

Thank you all in advance, and hopefully I have succeeded with providing enough reproducible information, that can lead you along the way to a patch.

**Comment by buxtonpaul** [comment]
Hi,

I suspect part of what you are seeing here is how different
systems/software interpret the dive log. So for example Subsurface
calculates the dive time looking at the samples in your log, and counts you
as being 'at the surface' for any depth shallower than 75cm. Your dive
computer may use a different threshold at which to determine the start/end
of the dive, and their is no way to realistically make the calculation
subsurface does match that done by all available dive computers.
However I would expect the yearly statistic to be based on the pre-rounded
'corrupted' values.

The 20M vs 19.9M issue is simply rounding for display purposes, it is an
explicit choice made in the code. Internally the depth is stored as mm.

Paul

**Comment by dirkhh** [comment]
I believe that Subsurface correctly accounts for dive durations and while some of the displayed data are rounded, the stored data isn't (we store mm and seconds). So unless you can show me a specific example with a data file to go along with it that shows that we are indeed accumulating errors, I'll close this.
A different app showing different values is just a matter of the developers making different choices on how to calculate dive duration, for example.
