### ISSUE TITLE
Dumb user error - how to recover?

### ISSUE THREAD

**Issue by jongross** [subsurface/subsurface#2319]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [ x ] New feature request
- [ ] Discussion request

### Issue long description:

I am on a boat in Indonesia and accidentally uploaded the current file to cloud storage, assuming it would merge, but it appears to have replaced all my cloud storage logs with the contents of my trip file that I'd been working with.

I'm hoping that this is git backed somehow, and I can revert my cloud storage to something previous to my accidental replacement of the cloud storage collection with the old extensive log, and I can figure out how to merge my current trip log file into cloud storage instead of stomping the old log in favor of the new trip log.

Is there a way to do this?  I've trolled through docs on my dodgy cell connection but can't find any way to restore things, is there?

If there isn't, I guess this is a feature request and I really really hope that I have a backup somewhere on another computer that I can utilize when I return to the US.

### Operating system:

MacOS / Catalina / English

Macbook Air

### Subsurface version:

4.9.3

hard to say

official version

### Steps to reproduce:

Save a logbook to cloud storage, and it stomps instead of merging
### Current behavior:

it stomps the old logs
### Expected behavior:

it should attempt to merge, or if it can't merge, then it should at least make sure you want to stomp

**Comment by atdotde** [comment]
Yes, it is git. Run subsurface from the command line with option -v
`/Applications/Subsurface.app/Contents/MacOS/subsurface -v`

It will tell you the location of the local repository. You need to check out the branch named like your email address and then apply the usual git commands. In my case it says

`Local git storage: /Users/helling/Library/Application Support/Subsurface/cloudstorage/c72433d1ae87cbe0`

**Comment by dirkhh** [comment]
So this all depends a bit on where you were using Subsurface - if you used in on Windows/Mac/Linux then you should be able to recover things yourself, assuming some familiarity with git. If you only use it on mobile (or if you aren't familiar with git) then your best bet is to contact me via email, tell me that you give me explicit permission to access your data on the cloud server, and I'll see what I can do for you on the backend.
If your previous data was ever successfully synced to the Subsurface cloud then it is still there.

**Comment by jongross** [comment]
Excellent. Yes I’m very familiar with git and it was on a Mac. Thanks so much!
