### ISSUE TITLE
Dive information tab shows meaningless and wrong values for SAC and gas consumption

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#2376]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

By clicking around in my dive list I can randomly produce insane values for SAC and gas consumption in the dive information tab.

Examples:
![grafik](https://user-images.githubusercontent.com/25316050/68708337-cd3ed580-0593-11ea-907a-531a2e41260f.png)
![grafik](https://user-images.githubusercontent.com/25316050/68708384-e2b3ff80-0593-11ea-9bb6-5f214b8529ae.png)
![grafik](https://user-images.githubusercontent.com/25316050/68708559-43dbd300-0594-11ea-87bd-a1a05416c36d.png)

These are all screenshots from the very same dive. Produced by unselecting/selecting this dive. The wrong values happen for gases, where there is no cylinder pressure info at all. So expected would be having printed no info at all.

### Mentions:

@dirkhh @bstoeger @willemferguson

**Comment by willemferguson** [comment]
Stefan, thank you, this is valuable. Please email me directly one of your dives and the resulting information tab? What happens when you have cylinder pressures that are defined in the Equipment tab?

**Comment by willemferguson** [comment]
@bstoeger, would it also make sense to use  dive->cylinders.nr instead of MAX_CYLINDERS as you did to solve the cylinder pressure pressure graph problem?

**Comment by bstoeger** [comment]
All MAX_CYLINDERS instances were removed. Fix is hopefully in #2378.

To test, you just need a dive without begin and/or end-pressure (and no events from an AI computer).
