### ISSUE TITLE
Rendering bug on web manual

### ISSUE THREAD

**Issue by glance-** [subsurface/subsurface#2415]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
https://subsurface-divelog.org/documentation/subsurface-4-user-manual/ gets truncated by comment about "<!--..."

### Steps to reproduce:
Look at https://subsurface-divelog.org/documentation/subsurface-4-user-manual/  in a web browser, everything after "template by replacing the section marked with: “<!-- Template must be filled" is hidden as a html comment

### Additional information:
ascii-doc bug? workaround it in the source?

### Mentions:
@willemferguson @dirkhh

**Comment by glance-** [comment]
This was initially reported by StrykerSKS on IRC.

**Comment by PeterZaal** [comment]
I think I mentioned the same problem in
https://github.com/Subsurface-divelog/subsurface/issues/2385
(literal script in user manual page), as well as several other issues on
the website.

Peter

Op ma 2 dec. 2019 12:16 schreef Anton Lundin <notifications@github.com>:

**Comment by dirkhh** [comment]
I am WAY behind on fixing these.
And they are all signs of issues with the way I abuse WordPress to create our website.
Eventually this will all come crashing down and I'll need to completely redo this.
Today isn't that day.
I believe this bug is fixed.
