### ISSUE TITLE
dive planner desktop

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#2491]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When using imperial units
Bottom Po2 and Deco Po2 still shows Bar

![Captura de pantalla 2019-12-27 a las 18 05 31](https://user-images.githubusercontent.com/6185391/71525798-b221ee00-28d3-11ea-951e-482103dd4249.png)

However examining the plist file, it converts the value from psi.

### Subsurface version:

Official 4.93 desktop on iMac Catalina 

### Steps to reproduce:

1) settings / units, choose metrics
2) dive plan
3) enter 1.5bar
4) settings / units, choose imperial
5) UI still shows 1.5bar
compared with plist values they are different.

**Comment by dirkhh** [comment]
@atdotde ?

**Comment by janiversen** [comment]
There seems to be little to no interest for making these changes on the desktop, so I will close this and make the adjustment for the mobile version.

**Comment by atdotde** [comment]
Sorry, for the late reply: This is intentional. When we set this up, I asked around and got the astwerk that even those technical divers that use imperial units use bars for partial pressures and not psi.

**Comment by janiversen** [comment]
Thanks for the explanation, I will cancel the change for mobile.

As a maybe interesting sidenote, the PADI and SSI course materials (deep dive course, which are for recreational divers, not technical divers) both use PSI in the North American version.

I guess that the BAR numbers are easier to remember than the PSI.
