### ISSUE TITLE
testGitStorage in GitHub actions builds, fails often.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#2538]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

It seems that testGitStorage often fails when running multiple builds (several PRs) on Travis.

When I rebase a serie (e.g. planner 1-4) this starts a number of builds and nearly every time I have to restart a couple of builds due to failed testGitStorage.

Having looked a bit deeper, it seems (at least for the Mac build) that testGitStorage does not like to run in parallel (2 PR builds, with both Mac builds being in the test phase).

Could the problem be that the problem is due to shared users (both testGitStorage on the 2 Mac builds use the same cloud user)?

**Comment by dirkhh** [comment]
I have given up on it and disabled it
