### ISSUE TITLE
[Idea] minimal pO2 threshold

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#259]
Currently, the program has maximum threshold values (in preferences, and for example used in the profile) for partial pressures that are too high.

Especially a low pO2 can be very dangerous, which is something that can occur very easily in pSCR diving due to the pO2 drop, and using incorrect gas in the shallow part of the dive. For example, the user manual shows a example of a pSCR dive using EAN30 all the way up to the surface, and given the default pSCR settings from Subsurface, this results in a pO2 < 0.15 bar from approx. 3m depth. Another example is the planner that shows a warning way too late. A plan with EAN30 shows a warning: low p02 of 0.05 at <end of dive>, with the last 20 minutes of the dive with pO2 < 0.15. I would say: do not try this at home.

All boils down to not having a minimal pO2 threshold value, and by consequence no proper feedback to the user for this danger.

Obviously, this is something related to technical diving wiith pSCRs or open circuit hypoxic gas diving, but as we are targeting this type of divers too, we can better do it right (oh oh, the DIR word :-)

**Comment by dirkhh** [comment]
I'm open to this idea. Since I have no interest in this type of diving, I don't see myself working on this, but patches would be very welcome.
