### ISSUE TITLE
Dive indive list does not get scope when selected

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#2595]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

1) Open a dive log
2) Select a trip heading. The trip notes are displayed.
3) Select a dive from this trip. The Notes tab does not change, still shows trip notes.
    The dive notes are not shown. I would expect it show the dive notes, not the trip notes.

### Mentions:

@dirkhh @bstoeger

**Comment by bstoeger** [comment]
Yes - that happened recently to me as well. I will look into it.

**Comment by bstoeger** [comment]
PS: Weirdly, when navigating with the cursor keys, it works - that surprised me a lot.
