### ISSUE TITLE
Equipment -> Weights Add Tank option for weight type

### ISSUE THREAD

**Issue by elibrin** [subsurface/subsurface#2609]
### Describe the issue:

- [ ] Bug
- [X] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Recommend adding the Tank weight type in the Equipment->Weights section.  Occasionally,  for trim adjustments, divers put weights on the tank(s).  I think it should be different from the Back 
plate type.

### Operating system:

All

### Subsurface version:

Version 4.9.3

**Comment by dirkhh** [comment]
You can add anything you like. Simply enter the term that you would want and a weight associated with it. The next time that term will be one of the options in the drop down.
