### ISSUE TITLE
Mobile: Rotating phone shows other dive

### ISSUE THREAD

**Issue by vanwinkeljan** [subsurface/subsurface#263]
Select latests dive (X), swipe to previous dive (X-1), rotate phone, rotate back -> next dive is shown (X-2)
Note that the dive name at the top (after Dive List) is still the name of  dive X-1 and the swipe direction (bak or forward) has no impact on the miss behavior . 
Further if the rotation is repeated the correct dive is shown (X-1 instead of X-2) and the issue is not reproducible anymore until a swipe is performed.

**Comment by dirkhh** [comment]
There are a couple of odd bugs with Subsurface-mobile showing the details of the wrong dive.
Thanks for the report - we're looking at this as part of a broader bug.
