### ISSUE TITLE
Android Mobile: DC Download Status not updated in repeated downloads

### ISSUE THREAD

**Issue by charno** [subsurface/subsurface#2651]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When repeatedly downloading from a dive computer on Android, the textual status on the right hand side of the buttons is only updated the first time.

![subsurface](https://user-images.githubusercontent.com/2691293/76152526-ce56be00-60c0-11ea-885d-6ff8cf6e03e9.gif)

### Operating system:
Galaxy S10 with supplied Android 10. 

### Subsurface version:
2.3.0 (4.9.3.1032) from Google Play Beta

### Steps to reproduce:
- Connect dive computer
- Press Download button
- Press Abort button
- Press Download button

### Current behavior:
On second download, the status is not updated anymore.

### Expected behavior:
On second download, the status should be updated.

**Comment by dirkhh** [comment]
That animated GIF is awesome. Shows me exactly what you mean.
I'm curious - how did you create that?

I'll take a look and see if I can fix this.

**Comment by charno** [comment]
I used https://play.google.com/store/apps/details?id=com.kimcy929.screenrecorder to record the screen and later transcoded the mp4 with `ffmpeg -i <input>.mp4 -r 15 <output>.gif`

Nice small fix! :)
