### ISSUE TITLE
Mobile: DC download does not trigger cloud sync

### ISSUE THREAD

**Issue by plxflx** [subsurface/subsurface#2705]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Operating system:

Android 10
Shearwater v72

### Subsurface version:

Subsurface 4.9.3.1246

### Steps to reproduce:

1. Download dives from DC 
2. Manual sync

### Current behavior:

Step 2 is instantly completed, nothing appears to sync.

### Additional information:

Workaround: Make a change to one of the dive from step 1 and do a manual sync.

**Comment by dirkhh** [comment]
Please test this with the current release 3.0.1 / 4.9.3.1251 -- the issue should be fixed
