### ISSUE TITLE
Petrel 2 not recognized as dive computer

### ISSUE THREAD

**Issue by ncgator82** [subsurface/subsurface#2739]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
iOS 13 and Shearwater Petrel2 will not connect to Subsurface mobile. Toggled verbose 
logging.  Also toggled on  temporarily show all bluetooth devices.  App log shows this:
Found new device = ""Petrel" "LE:{4447fea5-ffbb-7015-3be1-d5c9a2b0a33f}" Not
recognized as dive computer.  Device is actually Petrel2 but I am unable to achieve a connection between Subsurface Mobile and the Shearwater.  My current workaround is by connecting to a Windows PC, then performing a cloud sync.

### Operating system:
iOS 13.4.1 English
 iPhone 11 

### Subsurface version:
3.0.3(4.9.3.1328)

**Comment by dirkhh** [comment]
I'm puzzled that this wouldn't be recognized as dive computer...
```
	if (btName.startsWith("Predator") ||
	    btName.startsWith("Petrel") ||
```
Very strange.
There is a settings option to show all BT/BLE connections. If you enable that one (sorry, this is "per session only", so it does NOT stay enable between runs of the software), can you download from your Petrel2?
Please give that a try, and right after the download attempt (regardless of whether it's successful or not), please tap on Help->Ask for support in the app and send me the log that this will create as an email (the default recipient address that it will populate is just going to me, so this stays private in case you worry about that).

**Comment by ncgator82** [comment]
This release fixed my issue. Thanks so much!!

Rick Holcombe
