### ISSUE TITLE
Wrong pO / pN strings (in english) and others ?

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#274]
Hello.

Scrolling down Transifex to hunt some errors, I have found those:

english strings       Occurences
pO%s: %.2fbar⏎     ../core/profile.c:1319
pN%s: %.2fbar⏎     ../core/profile.c:1321
Apnoea                  ../desktop-widgets/configuredivecomputerdialog.ui:2346
Dive log files [...]    ../desktop-widgets/mainwindow.cpp:1832
All di&ves              ../desktop-widgets/divelogexportdialog.ui:385
di&velogs.de         ../desktop-widgets/divelogexportdialog.ui:147
I&mage depths      ../desktop-widgets/divelogexportdialog.ui:207
Sa&ve as                ../desktop-widgets/mainwindow.ui:190
P&references         ../desktop-widgets/mainwindow.ui:220
P&revious DC        ../desktop-widgets/mainwindow.ui:348
P&lan dive             ../desktop-widgets/mainwindow.ui:388
Open c&loud storage           ../desktop-widgets/mainwindow.ui:719
Save to clo&ud storage        ../desktop-widgets/mainwindow.ui:724
Clo&ud storage default file  ../desktop-widgets/preferences/preferences_defaults.ui:90
Personali&ze                         ../desktop-widgets/preferences/preferences_units.ui:47
P&rint                                    ../desktop-widgets/printdialog.cpp:103

If nothing wrong with $ in the middle of words, accept my apologies My bad ...

**Comment by janmulder** [comment]
pO%s: %.2fbar⏎ ../core/profile.c:1319
pN%s: %.2fbar⏎ ../core/profile.c:1321 : Are correct: the first %s is filled with UTF8_SUBSCRIPT_2 at runtime, so a nice subscripted 2.

Apnoea ../desktop-widgets/configuredivecomputerdialog.ui:2346 : Correct (alternative) spelling according to https://en.wikipedia.org/wiki/Apnea.

The & in menu items denote the location of the shortcut character (so no error).

And, finally, unsure what you think is wrong with Dive log files [...] ../desktop-widgets/mainwindow.cpp:1832, Ok, looking from transiflex it seems a strange piece of text, but it is a valid string to fill an option menu from code.

**Comment by Ghalr** [comment]
All my apologizes about the pN / pO strings, I still think for consistency to keep Apnea and for the other.
To translate Personali&ze (in French) it will be Per&sonnaliser So I have no idea where exactly & is supposed to be.

**Comment by atdotde** [comment]
The & marks the character for a keyboard shortcut (with alt). S might not be such a wise choice.

**Comment by Ghalr** [comment]
Thank you to confirm that.
The translation was made by Guillaume_G, a year ago
[If you are around Guillaume_G ?]
in any case we do not have Z in our french translation:
- Personnaliser
- Personnalisation
- Custom

Maybe I should create a list of "keyboard shortcut" to translate better ?
Do those "keyboard shortcut" are activated ?

**Comment by janmulder** [comment]
To see this type of keyboard shortcut, press and hold the alt key. The chosen letter gets an underline.

**Comment by Ghalr** [comment]
This is perfect. Thanks.
Well if everything is finally fine (sorry again for the bug ticket) feel free to close it, I'll have a closer look into the translation later.

**Comment by Ghalr** [comment]
@janmulder 
About what you said for pO% and pN% (filled with UTF8_SUBSCRIPT_2 at runtime, so a nice subscripted 2) why not use this method for the others too ?

**Comment by janmulder** [comment]
why not use this method for the others too? 

Well, why would we change the code for at least 30 strings, when there is no problem? There are more ways to display the subscripted 2's, and the UTF8_SUBSCRIPT_2 is just a way. We could argue about consistency, but in that case I would change the 3 occurrences of UTF8_SUBSCRIPT_2, as it is no use to dynamically construct that part of the string.

And just added a pull request for the Apnoea change.

**Comment by Ghalr** [comment]
You marked a point about to just change the 3 occurrences of UTF8_SUBSCRIPT_2

**Comment by janmulder** [comment]
@Ghalr: not sure what you mean?

**Comment by Ghalr** [comment]
You are right to change only 3 strings than 30 strings, I'm agree with you.

**Comment by janmulder** [comment]
@dirkhh: can you close this issue?
