### ISSUE TITLE
Missing dive sites

### ISSUE THREAD

**Issue by p-neves** [subsurface/subsurface#2749]
### Describe the issue:
Dive sites don't show up on the dive sites tab,

- [X ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
After starting Subsurface, if one goes to the Dive sites tab, no dive sites show up --- the list is empty.
If I click on "+" button I can populate the list with my dive sites in alphabetical order.

### Operating system:

Arch Linux; en-US locale

### Subsurface version:

Latest master

Not with an 4.9.2 appimage

self compiled

1438-g9feda560061f

### Steps to reproduce:

1) Start Subsurface
2) Open a logdive file if none is open by default
3) Open the Dive sites tab

### Current behavior:

The Dive sites tab shows no dive sites

### Expected behavior:

All my dive sites should be on the list.

**Comment by bstoeger** [comment]
Fix should be in #2759, please test.
