### ISSUE TITLE
[Idea] Change DateFormat by using a list option ?

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#276]
Hello.

I tried to change DateFormat and I noticed that you have to do it manually. 
I do have no problem with that, but it will clearly be more user friendly if we just have to choose in a list option : 

- mm/dd/yyyy (m/d/yy)
- dd/mm/yyyy (d/m/yy)
- yyyy-mm-dd (yy-m-d)

and also a box check to "Use short format" see ()

**Comment by dirkhh** [comment]
I have learned that there are a lot of different formats that people prefer.
But I agree that this would be an improvement in user experience. We should try _something_ like this...

**Comment by Ghalr** [comment]
Thank you for your support
