### ISSUE TITLE
Depth field allows large values

### ISSUE THREAD

**Issue by jirkapok** [subsurface/subsurface#2762]
### Description
When entering depth application freezes. See the provided screenshot.
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
The "Final depth" field in Dive planner points allows meaningless values to be entered.

### Operating system:
Windows 10

### Subsurface version:
Desktop Subsurface 4.9.3

### Steps to reproduce:
1. Create dive manually in planner
2. Enter values from screenshot in depth field fill "50000" meters
3. Application freezes and shows meaningless chart

### Current behavior:
Application freezes and shows meaning-less chart.
Not checked on another OS.

### Expected behavior:
Nothing is calculated, error popup is shown (based on other fields error behavior), chart isn't refreshed (or is empty).

### Additional information:
See screenshot with current behavior.
![subsurface_bug_depth](https://user-images.githubusercontent.com/25587226/79367507-47fa8b00-7f4e-11ea-960c-1c4fb5a2d2ac.png)

### Mentions:
N/A

**Comment by atdotde** [comment]
We don't impose a boundary what we think is a "reasonable" depth and what not. We try to calculate a deco plan for anything possible, but if that is too long, we stop the calculation and show the error that you see in the red bar. For a dive to that depth, deco would take too long to be calculated. I don't see a bug.

**Comment by jirkapok** [comment]
The application freezes and needs to be restarted. I think this should be enough to threat it as a bug, in any possible way. It doesn't have to be fixed by solution proposed by me.

**Comment by atdotde** [comment]
For me, it does not freeze, it just gets very very slow (as it is trying to calculate a deco schedule that takes several days). It gets back to normal as soon as I replace the stupid depth with a reasonable one.

**Comment by jirkapok** [comment]
Ok, leaving next steps up to you. I have no more comments.
