### ISSUE TITLE
Website: URL for DMG links to old version

### ISSUE THREAD

**Issue by ghost** [subsurface/subsurface#2827]
### Describe the issue:
- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
On the page
https://subsurface.github.io/de/release/2020/05/subsurface-4-9-4-released/ the download link to the DMG for Macs links to https://subsurface-divelog.org/downloads/Subsurface-4.8.1.dmg.

### Steps to reproduce:
Go to https://subsurface.github.io/de/release/2020/05/subsurface-4-9-4-released/, scroll down to _Wo finde ich ausführbare Programme?_ and download the DMG.

### Current behavior:
User downloads a different (older) version than expected.

### Expected behavior:
User downloads the correct version.

**Comment by dirkhh** [comment]
What strange bug to slip through the cracks.
Fixed.
