### ISSUE TITLE
Add SAC to the export dive details as csv

### ISSUE THREAD

**Issue by p-neves** [subsurface/subsurface#2829]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [X ] New feature request
- [ ] Discussion request

### Issue long description:

It would be nice to have the "SAC" field on the list of fields exported on the csv dive details file

### Subsurface version:

4.9.4

Self compiled

80-gce7cc7970540

**Comment by mturkia** [comment]
This will require some more effort as the export to CSV is based on saved XML file, and SAC is not stored in it (as Subsurface calculates that on-the-fly). Would it make sense to store SAC on the XML but not parse it, when opening a Subsurface XML file? This would allow XSLT to export SAC.

**Comment by dirkhh** [comment]
Interesting. I had wondered about that since SAC is indeed purely a calculated value.
Hmm. Can you poke Linus on this one? He doesn't respond to @torvalds mentions (gets way too many), so just send him an email with a link to this github issue...

**Comment by torvalds** [comment]
https://github.com/subsurface/subsurface/pull/2835

Close this if that works for you.
