### ISSUE TITLE
Subsurface mobile: Showing heart rate and skin temperature of Scubapro G2

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#2832]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

Is it possible to show additionally heart rate and skin temperature in the graph of subsurface mobile from the Scubapro G2 device dive data.

**Comment by neufeind** [comment]
Dupe/related with #1186

**Comment by mikeller** [comment]
Closing as duplicate of #1186.
