### ISSUE TITLE
I can't get the 4.9.4 to open on a mac running 10.11.16

### ISSUE THREAD

**Issue by gr8tfl** [subsurface/subsurface#2838]
I can't get the 4.9.4 to open on a mac running 10.11.16

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

**Comment by dirkhh** [comment]
macOS 10.11 is no longer supported in the official binaries since the Qt libraries that were used to build the binaries require at least macOS 10.12.
It should still be possible to build on macOS 10.11 using Qt 5.11 - but that's not something I currently have the bandwidth to do.

**Comment by dirkhh** [comment]
Hi @gr8tfl -- and thanks for the sponsorship.
I have no way to get an email address for people who send money... often I can figure out who it is from their GitHub profile, but with you that failed. So an awkward Thank You here in the only issue you ever opened :)

**Comment by gr8tfl** [comment]
If figuring out is important I unmask myself. 

Thanks for Subsurface. If I could vote on how the very small contribution is used it would be on good coffee in the morning or beer in the afternoon, but I give for you to use however you like. 

Thanks again

Max Erenberg
+1 773 771 3750
***@***.***
