### ISSUE TITLE
filter bug in Subsurface-mobile when filtering for tags

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#2842]
### Describe the issue:

- [x] Bug

### Issue long description:

From Hartley H: if I filter on a tag, such as “wreck”, it only shows dives where the ONLY tag is wreck.  Most of my dives have comma separated tags and wreck dives will have a tag of “boat, wreck” as an example.  Those dive are not found in the filter list. 

### Operating system:

iOS 12.4

### Subsurface version:

3.0.6(4.9.4.93) - but same behavior in earlier versions

### Mentions:

@bstoeger (don't know Hartley's GitHub user name)

**Comment by h2sk1** [comment]
Thanks Dirk.  To make things confusing to all, my GitHub isn't related to my subsurface handle.   Hartley

**Comment by h2sk1** [comment]
New iOS beta works for me.  Thanks.
