### ISSUE TITLE
Subsurface mobile: Can't edit fields in dive dialog

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#2862]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The fields suit, buddy and divemaster can't edited, it is only possible to use a drop down menu with the before used items.
### Operating system:

Android (10.0):arm64:de-DE"

Samsung A7

Subsurface-mobile:3.0.7(4.9.4.113)

**Comment by dirkhh** [comment]
This is fixed in 3.0.8
