### ISSUE TITLE
Same Problem with Version 3.0.6.

### ISSUE THREAD

**Issue by sausimausi** [subsurface/subsurface#2863]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

SubSurface Mobile Android does not sync dives.
Windows client is set to sync to cloud.
When loading Windows client following message appears in red background:
git-load: string marker after running out of strings ('description')

### Operating system:

Windows 10 Version 1909
Android 10 QKQ1.190825.002

### Subsurface version:

Windows: 4.9.4
Android: 3.0.6

### Steps to reproduce:

Android: tried with SmartShone and Tablet
De-installed Subsurface and re-installed 
Deleted login credentials and re-entered

### Current behavior:

Android: Message "no dives in dive list"
Manual sync seems to run but without showing dives.  (0) dives 

I can manually enter dives in Windows but these are not showing in Android
I can manually enter dives in Android but these are not showing in Windows

### Expected behavior:

Sync dives

**Comment by sausimausi** [comment]
I have the same problem: on android mobile apps no dives show with android version 3.0.6

**Comment by dirkhh** [comment]
That's not really a useful issue report.
It doesn't tell us what's not working, it doesn't include a log.
What do you expect the developers to do with this, other than waste their limited time on responding and asking you clarifying questions?
