### ISSUE TITLE
gasmix -1 error downloading dive from Shearwater Perdix AI

### ISSUE THREAD

**Issue by johnsgill3** [subsurface/subsurface#2866]
### Describe the issue:
`gasmix - 1 for tank 0 doesn't match`
- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Every time that I attempt to download dives from Shearwater Perdix AI over Bluetooth I am getting the following error banner that appears: 
<img width="190" alt="Screen Shot 2020-05-29 at 12 55 30 PM" src="https://user-images.githubusercontent.com/8923546/83300006-0f380d80-a1ac-11ea-9c94-bccfe021d1d2.png">. I am able to still successfully download the dive and import it, but the error is confusing and annoying.

### Operating system:

Mac OS X 10.15.4, English

Shearwater Perdix AI FWv72

### Subsurface version:

4.9.4

Haven't tried any other versions

Release Build

### Steps to reproduce:

1) Click `Import`
1) Click `Import from Dive Computer`
1) Select `Choose Bluetooth download mode`
1) Click `...`
1) Select `Perdix {<>}`
1) Click `Save`
1) Click `Download`
1) Error banner shows up in main window

### Current behavior:

Error banner appears importing dives from computer

### Expected behavior:

No error banner

**Comment by ghost** [comment]
Just chiming in to say I have the same issue. My Perdix AI still has firmware v71.

**Comment by bstoeger** [comment]
Hm. The obvious suspect would be the MAX_CYLINDERS removal: 7c9f46acd2

However, I don't see how the changes would affect the local `tank` structure in this file.

If you say that the gas-information is imported properly, I would cautiously simply remove the warning. That said, I'm not familiar at all with this part of the code.

@dirkhh: You wrote the warning (4be7604634), so I reckon that you would understand best what this is about.

**Comment by bstoeger** [comment]
I don't have the hardware, so I can't test it, but hopefully #2874 fixes the problem.
