### ISSUE TITLE
Dive merge loses gas data

### ISSUE THREAD

**Issue by BartJV** [subsurface/subsurface#2884]
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Merging two dives with tank pressure data included results in incorrect gas consumption /SAC report

### Operating system:
Windows and Ubuntu, Perdix AI

### Subsurface version:
4.9.6, Official release

### Steps to reproduce:

[testCase.txt](https://github.com/subsurface/subsurface/files/4822331/testCase.txt)

-Open attached log file.
-Merge dive 475 and 476
-Reported gas consumed is based on only the first dive.

### Current behavior:
Gas consumption from second log file is lost.

### Expected behavior:
Merge clenly.

**Comment by bstoeger** [comment]
This one is still an open problem. When merging the dives, gas consumption is only given for the first dive on the info tab.
