### ISSUE TITLE
Data error when Planning and saving dive with surface time

### ISSUE THREAD

**Issue by Ospeleo** [subsurface/subsurface#2901]
Bug
- Context: using the planner to plan a multi-sump dive for cave diving
It is useful to plan a multi sump dive as one single dive for deco/gaz management

- Error: If you manually enter dive points with return to surface (depth=0, with/without surface time), you save it, then the dive is correctly displayed.
If you re-edit it, then Subsurface misreads the saved file and all the zero-depth points are merged, giving a wrong dive profile.

Subsurface 4.9.6 macos 10.12.6

screen captures:
Planning the dive (entering manual dive points)
![Capture d’écran 2020-07-23 à 01 27 29](https://user-images.githubusercontent.com/12714994/88309868-3e33b100-cd0f-11ea-9392-f82e265a3d86.jpg)

The dive as it appears in the main window after being saved. It looks good
![Capture d’écran 2020-07-23 à 01 28 59](https://user-images.githubusercontent.com/12714994/88309866-3d028400-cd0f-11ea-9d3d-cf3e8b31fd26.jpg)

Re-editing the same dive: all zero-depth points have been merged
![Capture d’écran 2020-07-23 à 01 29 14](https://user-images.githubusercontent.com/12714994/88309861-3bd15700-cd0f-11ea-983c-e423395cf103.jpg)

**Comment by atdotde** [comment]
The problem is not zero depth but zero length segments (instantaneous transitions to new depth). Our computational model doesn't like you to be at two depths at once and thus deletes those waypoints. You could argue that the failure should be more gracefully, for example by adding a few seconds for the transition and I will submit a patch to that effect.

**Comment by Ospeleo** [comment]
thanks. it makes sense. 
instead of a few seconds, you could just add a millisecond so that it's not the same time.
