### ISSUE TITLE
Installation of subsurface on Fedora 32 not working.

### ISSUE THREAD

**Issue by thommmmmy** [subsurface/subsurface#2908]
### Describe the issue:

Installation of subsurface on Fedora 32 not working. The RPM-Package depends on out of date libraries. 
- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I try to run subsurface on Fedora 32 (x86-64)

Since subsurface isn't part of Fedora itself any more, it isn't working seamless anymore. 

Read https://bugzilla.redhat.com/show_bug.cgi?id=1742889 
This worked well for Fedora 30. Right after the release of Fedora 30 it was working for Fedora 32 too. But it has broken despises since months. 

The current RMP-Package ( https://download.opensuse.org/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm ) is out of date. It depends on old libraries. 

If I downgrade the affected libraries, the functionality of many qt- and KDE bases apps are broken. (E.g. dolphin, VLC, HandBrake,  kdenlive and more stops working!)

**IMPORTANT:**
I was advised to use the Flatpak-Package of subsurface more then once in the past. But there is one big issue:  Flatpak is in this case no option, because I need to be able to import data form the  commuter (over USB).

dnf trying to install subsurface on Fedora 32: 

> **root@localhost ~ $**
> 
> **root@localhost ~ $ wget https://download.opensuse.org/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm**
> --2020-08-09 11:50:29--  https://download.opensuse.org/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm
> Resolving download.opensuse.org (download.opensuse.org)... 2001:67c:2178:8::13, 195.135.221.134
> Connecting to download.opensuse.org (download.opensuse.org)|2001:67c:2178:8::13|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://ftp.gwdg.de/pub/opensuse/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm [following]
> --2020-08-09 11:50:29--  https://ftp.gwdg.de/pub/opensuse/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm
> Resolving ftp.gwdg.de (ftp.gwdg.de)... 2001:638:60f:110::1:2, 134.76.12.6
> Connecting to ftp.gwdg.de (ftp.gwdg.de)|2001:638:60f:110::1:2|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 7974100 (7.6M) [application/x-redhat-package-manager]
> Saving to: ‘subsurface-4.9.6-2.1.x86_64.rpm’
> 
> subsurface-4.9.6-2.1.x86_64.rpm                   100%[==========================================================================================================>]   7.60M  5.75MB/s    in 1.3s    
> 
> 2020-08-09 11:50:30 (5.75 MB/s) - ‘subsurface-4.9.6-2.1.x86_64.rpm’ saved [7974100/7974100]
> 
> **root@localhost ~ $ dnf install ~/subsurface-4.9.6-2.1.x86_64.rpm** 
> Last metadata expiration check: 2:51:37 ago on Sun 09 Aug 2020 08:59:43.
> Dependencies resolved.
> =====================================================================================================================================================================================================
>  Package                                                   Architecture                       Version                                               Repository                                  Size
> =====================================================================================================================================================================================================
> Installing:
>  subsurface                                                x86_64                             4.9.6-2.1                                             @commandline                               7.6 M
> Downgrading:
>  HandBrake                                                 x86_64                             1.3.1-1.fc32                                          rpmfusion-free                             438 k
>  HandBrake-gui                                             x86_64                             1.3.1-1.fc32                                          rpmfusion-free                             3.5 M
>  digikam                                                   x86_64                             7.0.0-0.3.beta2.fc32                                  fedora                                     104 M
>  digikam-doc                                               noarch                             7.0.0-0.3.beta2.fc32                                  fedora                                     8.0 k
>  digikam-libs                                              x86_64                             7.0.0-0.3.beta2.fc32                                  fedora                                     9.9 M
>  ffmpeg                                                    x86_64                             4.2.2-5.fc32                                          rpmfusion-free                             1.4 M
>  ffmpeg-libs                                               x86_64                             4.2.2-5.fc32                                          rpmfusion-free                             7.1 M
>  gpgme                                                     x86_64                             1.13.1-6.fc32                                         fedora                                     205 k
>  gpgmepp                                                   x86_64                             1.13.1-6.fc32                                         fedora                                     133 k
>  kdenlive                                                  x86_64                             19.12.3-1.fc32                                        rpmfusion-free                              13 M
>  kf5-akonadi-server                                        x86_64                             19.12.2-1.fc32                                        fedora                                     2.5 M
>  kf5-akonadi-server-mysql                                  x86_64                             19.12.2-1.fc32                                        fedora                                      11 k
>  kf5-frameworkintegration                                  x86_64                             5.68.0-1.fc32                                         fedora                                     1.6 M
>  kf5-frameworkintegration-libs                             x86_64                             5.68.0-1.fc32                                         fedora                                      29 k
>  kf5-kdeclarative                                          x86_64                             5.68.0-1.fc32                                         fedora                                     293 k
>  kf5-ktexteditor                                           x86_64                             5.68.0-1.fc32                                         fedora                                     2.5 M
>  kf5-kwayland                                              x86_64                             5.68.0-1.fc32                                         fedora                                     516 k
>  kf5-kxmlgui                                               x86_64                             5.68.0-1.fc32                                         fedora                                     674 k
>  kf5-libktorrent                                           x86_64                             2.1.1-3.fc32                                          fedora                                     692 k
>  ktorrent                                                  x86_64                             5.1.2-2.fc32                                          fedora                                     2.0 M
>  ktorrent-libs                                             x86_64                             5.1.2-2.fc32                                          fedora                                     923 k
>  kwin                                                      x86_64                             5.18.4-1.fc32                                         fedora                                      35 k
>  kwin-common                                               x86_64                             5.18.4-1.fc32                                         fedora                                     2.7 M
>  kwin-libs                                                 x86_64                             5.18.4-1.fc32                                         fedora                                     1.5 M
>  libavdevice                                               x86_64                             4.2.2-5.fc32                                          rpmfusion-free                              74 k
>  libdav1d                                                  x86_64                             0.5.2-2.fc32                                          fedora                                     360 k
>  libebml                                                   x86_64                             1.3.10-2.fc32                                         fedora                                      87 k
>  libgit2                                                   x86_64                             0.99.0-2.fc32                                         fedora                                     460 k
>  libmatroska                                               x86_64                             1.5.2-2.fc32                                          fedora                                     178 k
>  live555                                                   x86_64                             2020.04.12-1.fc32                                     rpmfusion-free                             442 k
>  mkvtoolnix                                                x86_64                             44.0.0-1.fc32                                         fedora                                     5.2 M
>  plasma-integration                                        x86_64                             5.18.4-1.fc32                                         fedora                                     153 k
>  python-qt5-rpm-macros                                     noarch                             5.13.2-5.fc32                                         fedora                                      11 k
>  python3-gpg                                               x86_64                             1.13.1-6.fc32                                         fedora                                     262 k
>  python3-qt5                                               x86_64                             5.13.2-5.fc32                                         fedora                                     1.2 M
>  python3-qt5-base                                          x86_64                             5.13.2-5.fc32                                         fedora                                     3.2 M
>  python3-qt5-webkit                                        x86_64                             5.13.2-5.fc32                                         fedora                                     135 k
>  qgis                                                      x86_64                             3.12.1-1.fc32                                         fedora                                      39 M
>  qgpgme                                                    x86_64                             1.13.1-6.fc32                                         fedora                                     242 k
>  qt5-qdbusviewer                                           x86_64                             5.13.2-5.fc32                                         fedora                                      56 k
>  qt5-qt3d                                                  x86_64                             5.13.2-2.fc32                                         fedora                                     1.8 M
>  qt5-qtbase                                                x86_64                             5.13.2-4.fc32                                         fedora                                     3.3 M
>  qt5-qtbase-common                                         noarch                             5.13.2-4.fc32                                         fedora                                      11 k
>  qt5-qtbase-gui                                            x86_64                             5.13.2-4.fc32                                         fedora                                     5.6 M
>  qt5-qtbase-mysql                                          x86_64                             5.13.2-4.fc32                                         fedora                                      41 k
>  qt5-qtconnectivity                                        x86_64                             5.13.2-2.fc32                                         fedora                                     505 k
>  qt5-qtdeclarative                                         x86_64                             5.13.2-2.fc32                                         fedora                                     3.6 M
>  qt5-qtenginio                                             x86_64                             1:1.6.2-28.fc32                                       fedora                                     163 k
>  qt5-qtgraphicaleffects                                    x86_64                             5.13.2-2.fc32                                         fedora                                     111 k
>  qt5-qtimageformats                                        x86_64                             5.13.2-2.fc32                                         fedora                                     100 k
>  qt5-qtlocation                                            x86_64                             5.13.2-2.fc32                                         fedora                                     3.0 M
>  qt5-qtmultimedia                                          x86_64                             5.13.2-2.fc32                                         fedora                                     799 k
>  qt5-qtnetworkauth                                         x86_64                             5.13.2-2.fc32                                         fedora                                      84 k
>  qt5-qtquickcontrols                                       x86_64                             5.13.2-2.fc32                                         fedora                                     1.0 M
>  qt5-qtquickcontrols2                                      x86_64                             5.13.2-2.fc32                                         fedora                                     2.0 M
>  qt5-qtscript                                              x86_64                             5.13.2-2.fc32                                         fedora                                     1.0 M
>  qt5-qtsensors                                             x86_64                             5.13.2-2.fc32                                         fedora                                     228 k
>  qt5-qtserialport                                          x86_64                             5.13.2-2.fc32                                         fedora                                      65 k
>  qt5-qtspeech                                              x86_64                             5.13.2-2.fc32                                         fedora                                      44 k
>  qt5-qtspeech-speechd                                      x86_64                             5.13.2-2.fc32                                         fedora                                      25 k
>  qt5-qtsvg                                                 x86_64                             5.13.2-2.fc32                                         fedora                                     181 k
>  qt5-qttools                                               x86_64                             5.13.2-5.fc32                                         fedora                                      39 k
>  qt5-qttools-common                                        noarch                             5.13.2-5.fc32                                         fedora                                      11 k
>  qt5-qttools-libs-designer                                 x86_64                             5.13.2-5.fc32                                         fedora                                     2.7 M
>  qt5-qttools-libs-help                                     x86_64                             5.13.2-5.fc32                                         fedora                                     133 k
>  qt5-qtvirtualkeyboard                                     x86_64                             5.13.2-2.fc32                                         fedora                                     2.3 M
>  qt5-qtwayland                                             x86_64                             5.13.2-3.fc32                                         fedora                                     1.0 M
>  qt5-qtwebchannel                                          x86_64                             5.13.2-2.fc32                                         fedora                                      93 k
>  qt5-qtwebengine                                           x86_64                             5.13.2-4.fc32                                         fedora                                      49 M
>  qt5-qtwebkit                                              x86_64                             5.212.0-0.42.alpha3.fc32                              fedora                                      13 M
>  qt5-qtwebsockets                                          x86_64                             5.13.2-2.fc32                                         fedora                                      86 k
>  qt5-qtx11extras                                           x86_64                             5.13.2-2.fc32                                         fedora                                      35 k
>  qt5-qtxmlpatterns                                         x86_64                             5.13.2-2.fc32                                         fedora                                     1.1 M
>  vlc                                                       x86_64                             1:3.0.9.2-3.fc32                                      rpmfusion-free                             1.5 M
>  vlc-core                                                  x86_64                             1:3.0.9.2-3.fc32                                      rpmfusion-free                             9.7 M
>  vlc-extras                                                x86_64                             1:3.0.9.2-3.fc32                                      rpmfusion-free                              80 k
>  xdg-desktop-portal-kde                                    x86_64                             5.18.4-1.fc32                                         fedora                                     190 k
> 
> Transaction Summary
> =====================================================================================================================================================================================================
> Install     1 Package
> Downgrade  77 Packages
> 
> Total size: 318 M
> Total download size: 311 M
> Is this ok [y/N]: N
> Is this ok [y/N]: N
> Operation aborted.
> 
> **root@localhost ~ $** 
> 

### Operating system:
- OS => up to date Fedora 32 (x86-64)
- Device => PC
- Does the same happen on another OS? => no idea?

### Subsurface version:
- Subsurface-Version => 4.9.6-2.1.
- Does the same happen on another Subsurface version? => no idea?
- Are you using official release, test build, or compiled yourself? => What does it mean? Is a link on https://subsurface-divelog.org/download/ official enough? (Why ever this is stored on opensuse.org?)

### Steps to reproduce:
1. Use Fedora 32
3. open a bash
2. `su -` followed by root password
3. `dnf upgrade -y`
4. `wget https://download.opensuse.org/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm`
5. `dnf install ./subsurface-4.9.6-2.1.x86_64.rpm`

Now dnf offers to downgrade 77 packages. 
- If you press "y" and downgrade the 77 packages, subsurface will work well, but it brakes many qt and KDE based apps. This is a no go!
- If you press "n" and don't downgrade, you have the option to force the installation (  `rpm -ivh --nodeps --force ~/subsurface-4.9.6-2.1.x86_64.rpm`  ) of the subsurface package.  

> **root@localhost ~ $ rpm -ivh --nodeps --force ~/subsurface-4.9.6-2.1.x86_64.rpm**
> warning: /root/subsurface-4.9.6-2.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID ade0842b: NOKEY
> Verifying...                          ################################# [100%]
> Preparing...                          ################################# [100%]
> Updating / installing...
>    1:subsurface-4.9.6-2.1             ################################# [100%]
> /var/tmp/rpm-tmp.X3TfGf: line 1: fg: no job control
> **root@localhost ~ $ exit**
> **thom@localhost ~ $ subsurface**
> subsurface: error while loading shared libraries: libgit2.so.0.99: cannot open shared object file: No such file or directory
> **thom@localhost ~ $** 

Subsurface won't load. Not working.

### Current behavior:
- Installation with dnf isn't working as it should. Downgrading of 77 core-packages is a now go!
- Flatpak package doesn't offer access to the dive computer. 
- After forcing the installation, subsurface won't start.

### Expected behavior:
Two options:
1. Fix despises in the package at: https://download.opensuse.org/repositories/home:/Subsurface-Divelog/Fedora_32/x86_64/subsurface-4.9.6-2.1.x86_64.rpm
Or
2. Make dive computer data import over USB working in the Flatpak package. 

### Mentions:
I really like subsurface, if I'm able to run it.

**Comment by dirkhh** [comment]
What an exhaustingly extensive bug report. Thanks for providing ooooooodles of details, @thommmmmy 
I'm talking to the open build service folks to understand why their Fedora 32 builds are linking against old libraries. Hopefully this can be fixed fairly easily.

**Comment by dirkhh** [comment]
Sorry this took so long. I finally figured out how to fix this. In hindsight the fix is of course simple and obvious, but... yeah.
Anyway, the updated RPMs should have propagated to the mirrors, version 3.9.6-4.1 should be available for Fedora 32 and I verified that it installs cleanly.

Thanks for your report!
