### ISSUE TITLE
DiveComputer.eu / tecdiving problems to impot logs with QtBluetooth

### ISSUE THREAD

**Issue by nightzero** [subsurface/subsurface#2921]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I can no longer import divelog to Subsurface. This has always worked before.

HW 3.0
SW 4.1
Subsurface version: 4.9.6
OS: Windows 10.

When clicking "Download" progress bar is not moving. Only say: "Opening rfcomm stream 'device number' "

Then I get errordialog:
"Could not open file 'device number' Tecdiving(DiveComputer.eu)"

And red bar in the bottom say "Unsupported Operation".
This is what I tried:
*Removed device in windows
*Rebooted BT interface in windows.
* Rebooted DC
* In logbook click a dive and then "Upload"
* Pair the DC in windows again
* Go to Subsurface
* Import -> Import from dive computer
* Choose Tecdive / divecomputer.eu
* Check download mode for Bluetooth
* Search for the DC in the search dialog that appear
* Select the DC in the list and press, "Save"
* Then click "Download"

At his stage I get the error described above.

As I said this worked before but have now stopped working.

I check the options to store log-file and dump-file, but no bin file is created and log file only contain:
`Subsurface: v4.9.6, built with libdivecomputer v0.7.0-devel-Subsurface-NG (7882ba423cd87569f9c9361fa999917e9ced1083)`

### Operating system:

Windows 10, swedish

### Subsurface version:

4.9.6

### Additional information:

I Run crom cammandline with the "-v -v" option. Get the following log if it helps:

Emit:  "3C:71:BF:CC:18:56"
Emit:  "D8:80:39:FE:B4:E0"
Emit:  "C0:97:27:4D:43:B1"
Starting download from  BT
downloading only new dives
Failed to create socket: 10093 "Programmet har antingen inte anropat WSAStartup eller så kunde inte WSAStartup utföras."
Linux Bluez connecting to Uuid "{00001101-0000-1000-8000-00805f9b34fb}"
Starting Bluetooth service discovery
UUID filter ("{00001101-0000-1000-8000-00805f9b34fb}")
FOUND SERVICE!
 (0)    uint 65537
 (1)    Sequence
 (1)            uuid2 1200
 (4)    Sequence
 (4)            Sequence
 (4)                    uuid2 0100
 (4)                    ushort 1
 (4)            Sequence
 (4)                    uuid2 0001
 (6)    Sequence
 (6)            ushort 25966
 (6)            ushort 106
 (6)            ushort 256
 (9)    Sequence
 (9)            Sequence
 (9)                    uuid2 1200
 (9)                    ushort 256
 (512)  ushort 259
 (513)  ushort 57
 (514)  ushort 20566
 (515)  ushort 288
 (516)  bool 1
 (517)  ushort 1

The connection step took more than expected. Wait another 20 seconds
Failed to connect to device  D8:80:39:FE:B4:E0 . Device state  QBluetoothSocket::ServiceLookupState . Error:  QBluetoothSocket::UnknownSocketError
Finishing download thread: "Could not open file D8:80:39:FE:B4:E0 Tecdiving (DiveComputer.eu)"

**Comment by nightzero** [comment]
So I downgraded to version 4.9.3 and it works again, i.e. no problem to connect to DC and download logs.

My guess is that the problem is related to rfcomm implementation, and problem was introduced with the QtBluetooth:
https://github.com/subsurface/subsurface/commit/aceb8a547f1ea70b71ab609c6e406928dee74b88

**Comment by nightzero** [comment]
@jefdriesen I tried downloading with dctool as per your instruction and it is working just fine.

What conlusion can we draw from this. Is the problim isolated to the subsurface code? Is libdivecomputer-library using Qt bluetooth as well?

**Comment by jefdriesen** [comment]
The dctool application uses libdivecomputer's built-in Bluetooth (rfcomm) implementation. Since that works fine, we can rule out problems with the dive computer itself. Subsurface uses libdivecomputer with a custom I/O implementation based on the Qt Bluetooth stack. The main reason for that is because it's available on more platforms (e.g. Mac OS X), and supports not only Bluetooth classic (rfcomm), but also Bluetooth Low Energy (BLE). But the fact that downloading with subsurface fails, while everything else is the same, points me in the direction of the Qt Bluetooth. But I'm not sure what or why is actually going wrong.

That WSAStartup error is certainly something suspicious.

Another thing is that "The connection step took more than expected. Wait another 20 seconds". The bluetooth discovery and connection is no doubt a slow operation. I just tried with my divecomputer.eu unit, and it took about 12 seconds, and I wouldn't be surprised if it can be even longer:
```
[0.001775] Opening the I/O stream (bluetooth, null).
[10.691076] INFO: Discover: address=D88039F337BD, name=DiveComputer
[10.691354] INFO: Open: address=D88039F337BD, port=0
[12.070535] INFO: SDP: channel=6
[12.295215] Opening the device (Tecdiving DiveComputer.eu).
```
Maybe subsurface doesn't wait long enough, and gives up too soon?

**Comment by dirkhh** [comment]
@nightzero - a Windows test binary that should fix your problem is available here:
https://subsurface-divelog.org/downloads/test/subsurface-4.9.6-118-g767f0a4f3eb0.exe
Sorry it took so long to get this sorted out.

**Comment by nightzero** [comment]
Thanks! Did not have the opportunity to try it before, but just did, It works perfect!
