### ISSUE TITLE
Changing weight type resets weight amount

### ISSUE THREAD

**Issue by sveinmagnus** [subsurface/subsurface#2938]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When changing the weight type for a dive the weight amount field is reset to either 0 or to last used weight amount of the given weight type. 

### Operating system:
Windows 7 English

### Subsurface version:
Subsurface 4.9.6 official

### Steps to reproduce:
Go to a dive log entry with a unknown weight type and a specified weight amount set
Change the weight type to any other type. 
the specified amount is changed to 0 for unused weight types, or to the previously used amount for the specified weight type.

### Current behavior:
weight amount is set along with weight type

### Expected behavior:
weight type and amount should be independently editable

**Comment by bstoeger** [comment]
It's not a bug - it's a (mis)feature. Indeed, when changing the weight type, then the previous weight used for that type is set.

I think the idea was that when you edited multiple dives of a trip, you generally use the same weights. However, with the multi-edit functionality this feature might be moot. It's certainly up for discussion.

**Comment by bstoeger** [comment]
I assigned a few developers whom might have an opinion on this.

**Comment by glance-** [comment]
I'm used to it, and it's bin like that for like forever, and I kinda like that feature.

Both fields are independently editable, it just autofills the last used weight.

I'm open to other suggestions, but just removing it feels like a loss of functionallity.

**Comment by dirkhh** [comment]
I agree with Anton - this has been the design since forever.
Simply in your editing process, first set the weight type, then set the weight (left to right) and you'll never have a problem with this. And if you are like most people and typically dive with the same amount of weight, then this is actually quite an intuitive and convenient design.

**Comment by sveinmagnus** [comment]
I understand that this feature might be practical when logging new dives, but when editing large amounts of existing imported dives it becomes problematic. For most imported dives the weight amount is already set as this is supported in most software, however the weight type is usually not. 
When mass-editing such imported dives to set the missing weight type this causes the existing weight amounts to be reset to the previously used weight amount for the chosen weight type, which causes the loss of the originally stored weight amount. This is especially problematic for travel divers like me who have a lot of dives using rented equipment, as well as dives with my own equipment but in highly varying locations so that the weight amounts vary a lot, even for the same weight type.

While I agree that autofill for empty fields in general is a good thing, it is rather troublesome to have an autofill that overwrites and erases existing data. I would therefore suggest as a good compromise to keep the autofill functionality as is when editing new dives where the weight amount has not been set previously to keep it stable for long-time users, but to make a minor modification so that the weight amount is left alone if it has already been defined, whether manually or by import, as this would make more sense to avoid accidentally corrupting data when doing historical edits.

**Comment by dirkhh** [comment]
What I think you are hearing here is that the current developers in general are happy with the design that we have in place.

I am certainly happy to entertain a pull request that adds this capability, but I don't think one of us will be working on this.

**Comment by sveinmagnus** [comment]
Thanks a lot @bstoeger!
When will this be in an official release?

**Comment by bstoeger** [comment]
I don't know if it will be accepted at all. You can help by testing the feature.

If you don't know how to build a pull request, you use the automatic build. E.g.: https://github.com/subsurface/subsurface/actions/runs/251174557

**Comment by atdotde** [comment]
I have no opinion as I never log weights myself (even when experimenting with weights, my weights are "big v-weight" and "small v-weight" since I made those myself and I don't even know their weight. The currently proposed solution (only overwrite 0 weights) sounds reasonable to me.
