### ISSUE TITLE
Dive info not updated when moving with pgdn

### ISSUE THREAD

**Issue by mturkia** [subsurface/subsurface#2957]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When moving between dives with page down/up or home end buttons, the dive is not switched to on the profile or info panels. All the detailed information remains in the original dive and not the one where we jumped to.

### Operating system:

Linux

### Subsurface version:

4.9.6 and git master

### Steps to reproduce:

- Open divelog with a bunch of dives
- select the first dive
- use page down to jump in the divelist
- note that the dive profile and notes and other information remains static

### Mentions:

@bstoeger

**Comment by bstoeger** [comment]
Weird - I missed the push mail - sorry.

Feel free to ping me if there is no reaction.
