### ISSUE TITLE
Visibility is missing on desktop version

### ISSUE THREAD

**Issue by fmatray** [subsurface/subsurface#2959]
### Describe the issue:
- [ ] Bug
- [ ] Change request
- [X ] New feature request
- [ ] Discussion request

### Issue long description:
Visibility is on the mobile version (IOS for me) but not the desktop version (MacOS).
Is it possible to add it, please ?

### Operating system:
MACOS

### Subsurface version:
Mobile : 3.0.14
Desktop : 4.9.6

**Comment by dirkhh** [comment]
It isn't. It just got moved to the Information tab.
