### ISSUE TITLE
Subsurface-mobile: adding a dive manually with date in the past causes wrong dive to be shown after saving

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#2971]
### Describe the issue:

- [x] Bug

### Issue long description:

Manually create a new dive, change the dive date to be in the past, before existing dives in the log
save the dive
notice that the dive isn't shown in dive details

### Operating system:

Tested mobile-on-desktop on macOS, tested on Android

### Subsurface version:

current master 4.9.6.125

### Mentions:

@bstoeger - I know you never use the mobile version... and I'm not sure it has anything to do with the model. But I thought I'd add you just in case... :-)

**Comment by bstoeger** [comment]
Happens not only for newly added dives.

**Comment by dirkhh** [comment]
I played with this for quite a bit and there's a fascinating challenge... we can select a current dive - but somehow, at some point, we lost the ability to tell the UI to SHOW that dive. I need to figure out (again) how to do that. I am pretty sure that at some point by setting a new current dive that one was "automagically" shown. But that doesn't appear to work anymore.

There is one additional issue with the manual adding of dives where sometimes we appear to add two dives by mistake, one at the current time/date with the default depth and duration, and a second one with the values the user entered. I've run into that twice in my test, but I cannot reproduce it.

**Comment by bstoeger** [comment]
I'll look into it later today.

**Comment by bstoeger** [comment]
Could you please try commenting out
```
        if (oldCurrent == current_dive)
                return;
```
in
`DiveTripModelBase::currentChanged()`
?

**Comment by bstoeger** [comment]
I'm not sure I'll have time to look closer into this today.
Apparently the swipe model doesn't update the current position correctly if dives are moved(?), but we don't send a current-changed signal, because current doesn't change. It's a bit unfortunate that mobile uses `current_dive` and desktop uses the selected dives.

**Comment by dirkhh** [comment]
> Could you please try commenting out
> 
> ```
>         if (oldCurrent == current_dive)
>                 return;
> ```
> 
> in
> `DiveTripModelBase::currentChanged()`
> ?

It's kinda interesting to contemplate what the code in the `SUBSURFACE_MOBILE` part will do when the two are the same, right?
This works, but it seems like we are doing the same thing twice there...

**Comment by bstoeger** [comment]
You would of course do something like
```
diff --git a/qt-models/divetripmodel.cpp b/qt-models/divetripmodel.cpp
index 8671a62b6..8a6885ab3 100644
--- a/qt-models/divetripmodel.cpp
+++ b/qt-models/divetripmodel.cpp
@@ -538,9 +538,6 @@ static ShownChange updateShownAll()
 
 void DiveTripModelBase::currentChanged()
 {
-	if (oldCurrent == current_dive)
-		return;
-
 	// On Desktop we use a signal to forward current-dive changed, on mobile we use ROLE_CURRENT.
 	// TODO: Unify - use the role for both.
 #if defined(SUBSURFACE_MOBILE)
@@ -549,11 +546,14 @@ void DiveTripModelBase::currentChanged()
 		QModelIndex oldIdx = diveToIdx(oldCurrent);
 		dataChanged(oldIdx, oldIdx, roles);
 	}
-	if (current_dive) {
+	if (current_dive && oldCurrent != current_dive) {
 		QModelIndex newIdx = diveToIdx(current_dive);
 		dataChanged(newIdx, newIdx, roles);
 	}
 #else
+	if (oldCurrent == current_dive)
+		return;
+
 	if (current_dive) {
 		QModelIndex newIdx = diveToIdx(current_dive);
 		emit currentDiveChanged(newIdx);
```
Nevertheless, it is conceptually wrong to send a changed signal for something that hasn't changed and the model shouldn't lose track of the current item if it is moved.

**Comment by dirkhh** [comment]
Yes, that should work. Will you send a PR? After all, you fixed the bug :-)

**Comment by bstoeger** [comment]
Feel free to commit, if this works for you. I wouldn't call it "fixing" the bug, but rather "hiding".
