### ISSUE TITLE
Error Unable to open FTDI Suunto D9 

### ISSUE THREAD

**Issue by y-ant** [subsurface/subsurface#2990]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Hi people,

Subsurface does not recognise Suunto D9 on my Mac laptop.

Not sure if these points are relevant:

- DM5 by Suunto neither was able to recognise my D9.
- I have tested this on MacBookPro 2017 which has usb c port & cheap dongle from usb c to usb ( maybe there can be an issue?) & original Suunto cable, BUT!:
-   I have tested this on MacBookPro 2015 with regular usb & original Suunto cable as well. Result negative.

These device/mount points were available, all of them did not help:

1. FTDI
2. /dev/tty.SOC
3. /dev/tty.MALS

The connection was trying to be established, but unsuccessful, also on the screen of dive computer I see **Data Transfer**, which hints me there should not be the issue, right?

### Operating system:
macOS Catalina 10.15.5, English ( MacBookPro 2017)
macOS Catalina 10.15.6, Russian ( MacBookPro 2015)

### Subsurface version:
Subsurface 4.9.7

official release, downloaded dmg file

**Comment by dirkhh** [comment]
This should be fixed in 4.9.8 (and the latest test builds)
