### ISSUE TITLE
Version 4.9.7 requires MacOS 10.15

### ISSUE THREAD

**Issue by zoeloe** [subsurface/subsurface#3005]
#1954 # Describe the issue:
Application not running on Macos 10.13.6

### Issue long description:
Version 4.9.7 requires MacOS 10.15 and fails to start on 10.13.6

### Operating system:
Macos 10.13.6
### Subsurface version:
version 4.9.6 runs fine on 10.13.6
### Steps to reproduce:
Download 4.9.7 dmg for MacOS.
Open Image, copy App to Applications folder. Try to open app.
Warning appears that App needs MacOS 10.15

### Current behavior:
App is showing forbidden sign on 10.13.6

**Comment by dirkhh** [comment]
https://subsurface-divelog.org/downloads/Subsurface-4.9.7-macOS-10.13+10.14.dmg
