### ISSUE TITLE
Releases not updating, please publish binaries for 4.9.7

### ISSUE THREAD

**Issue by zagrodzki** [subsurface/subsurface#3006]
Hello developers (and @dirkhh specifically because he left the last comment on the releases page).

https://github.com/subsurface/subsurface/releases has 4.9.4 as the last release, from May. It seems the issue with GitHub actions wasn't fixed yet. Could you please publish updated binaries for 4.9.7?

Thanks!

**Comment by dirkhh** [comment]
We actually stopped using the GitHub release binaries.
Release binaries are always at https://subsurface-divelog.org/downloads
