### ISSUE TITLE
Password manager integration

### ISSUE THREAD

**Issue by Voludu2** [subsurface/subsurface#3013]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
integrate with OS and third-party password managers such as lastpass, iCloud Keychain, etc to make generating and using sensible passwords more secure.

**Comment by dirkhh** [comment]
I really have no interest in fighting with the different password managers.
And in all honesty, the password for the Subsurface cloud doesn't behave like most account passwords. It's more like an API key. Given the size of the backlog of things that really need doing in the app, I don't think this is anywhere near the top of our priorities.
