### ISSUE TITLE
No way to copy dive

### ISSUE THREAD

**Issue by Voludu2** [subsurface/subsurface#3014]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Manual-described option to copy dive is not available.

### Operating system:
iOS
iPad

### Subsurface version:
3.0.15

### Steps to reproduce:

From dive list
1) long-press on a dive
2) the 3 described options do not appear on the selected dive
3) instead, an Actions panel slides in from right. “Copy dive” is not an option

### Current behavior:
long-press on dive results in “Actions” panel sliding in from right.  There is no action for copying a dive.
### Expected behavior:
 as described in manual: long-press on dive should result in 3 icons overplayed on item in dive list.  One of the icons should be for copy

### Additional information:

![15F527A1-07C9-4623-84F6-0B4AAD4B830D](https://user-images.githubusercontent.com/44700518/95859657-f41a0480-0d2c-11eb-840e-da342b3e5077.jpeg)

**Comment by dirkhh** [comment]
for some reason we are showing an outdated version of the mobile manual on the website (which is then linked from within the app). I thought I had fixed that, but somehow this got reverted.
The feature that you are looking for has been removed in Subsurface-mobile v3.
I'll keep this issue open until I find time to track down why we have the wrong user manual showing.

**Comment by dirkhh** [comment]
I believe the issues is fixed and the v3 manual is once again shown on the website
