### ISSUE TITLE
Support Apple keyboard trackpad mode

### ISSUE THREAD

**Issue by Voludu2** [subsurface/subsurface#3015]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

Support apple’s keyboard trackpad in order to get around the fat-finger issues while editing (such as while trying to remove that comma from the lat/Lon you have just copy/pasted)

https://techcrunch.com/2015/06/08/apple-just-turned-the-ipad-into-a-real-computer/

### Operating system:
iOS 
iPad 

### Subsurface version:
 mobile 3.0.15

### Steps to reproduce:

1) add a dive manually
2) copy/paste a lat/Lon containing a comma
3) engage trackpad: press and hold space bar until labels disappear from keyboard keys
4) use trackpad to move cursor to comma
5) lift finger from keyboard trackpad
6) use backspace key to delete comma
7) the W at the end of the lat/Lon is removed instead, and the cursor is where it was before the trackpad was engaged.
[Video](https://drive.google.com/drive/folders/1-A5M2wngK_-8cbpVg1-gVI1B-5qJNJox) 

### Current behavior:
cursor does not actually go to where you just seemed to have put it using keyboard trackpad.  Once you release the keyboard trackpad, the cursor goes back to where it was before

### Expected  behavior:
cursor should move to where it was placed using the keyboard trackpad in order to more easily edit text.

**Comment by dirkhh** [comment]
this is a feature that would have to be supported in Qt/QML - we have no way from within Subsurface to do this.
It's basically a limitation of the library / toolkit that we use in order to be able to provide a mobile app both on iOS and Android
