### ISSUE TITLE
Translation error in Italian

### ISSUE THREAD

**Issue by Energia00** [subsurface/subsurface#3024]
while opening the log, the words "sincronizzazione dei **dadi**" appear. 
The exact phrase in Italian is "sincronizzazione dei **dati**"

![Screenshot_20201015-081738_Subsurface-mobile](https://user-images.githubusercontent.com/72908781/96086330-77209380-0ec2-11eb-860f-10734e26c96c.jpg)

**Comment by dirkhh** [comment]
Thank you, this will be fixed in a future version
