### ISSUE TITLE
Translation of undo command when editing cylinders in equipment tab is not working

### ISSUE THREAD

**Issue by johan-git** [subsurface/subsurface#3068]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When adding/removing/editing cylinders in equipment tab the translation of the undo command (Edit in main menu) doesn't work as expected. The word "Undo" gets translated but not the rest of the string which describes the command. For example:
"Undo Add cylinder" doesn't translate **Add cylinder**" 
"Undo Edit cylinder" doesn't translate **Edit cylinder**" 
Tested on several different languages with the same result. So all non English languages are affected.

### Operating system:

Verified on Linux and MacOS

### Subsurface version:

Using latest development build

### Steps to reproduce:

- Change to a non English language
- Restart Subsurface
- Add a new dive
- Go to Equipment tab
- Add a new cylinder 
- Verify result under **Edit** in the main menu

### Current behavior:

Part of string get translated

### Expected behavior:

Translation of entire string

**Comment by dirkhh** [comment]
@bstoeger - these are set in the constructor calling `::tr()`, so I'm guessing that we are once again in a situation where the translations aren't loaded when the constructor is executed?

**Comment by bstoeger** [comment]
Yes, these need a `Command::Base::` as in the rest of the file.
