### ISSUE TITLE
Integrate with mention-bot

### ISSUE THREAD

**Issue by glance-** [subsurface/subsurface#308]
https://github.com/home-assistant/home-assistant/ uses mention-bot and I tink it works quite well. It looks at a PR and the history for that particular code thats changed, and mentions those persons in the PR, as potential reviewers.

I think its a great way to involve more people in the review-process.

https://github.com/facebook/mention-bot

**Comment by dirkhh** [comment]
That does look cool. I'm a bit strapped for time, trying to get Subsurface-mobile to the point where we can make another release... would you dig into this some more and give me pointers how to set this up?

**Comment by glance-** [comment]
I think https://github.com/facebook/mention-bot#how-to-use is pretty clear.

**Comment by glance-** [comment]
https://github.com/Subsurface-divelog/subsurface/pull/322 <- YEY - looks like it würks!

**Comment by atdotde** [comment]
Cannot find the .mention-bot configuration file. Where did you configure it? I would like to add myself to me mentioned for all commits touching `*plan*.c*` files as well as deco.c

**Comment by janmulder** [comment]
Dirk just activated it, without configuring any specials. So there is no config file yet.
