### ISSUE TITLE
Considers 4.9.9 newer than 4.9.10

### ISSUE THREAD

**Issue by calmh** [subsurface/subsurface#3091]
### Describe the issue:

- [X] Bug

### Issue long description:

When starting Subsurface 4.9.10 on macOS it pops up a dialog notifying that a newer version, 4.9.9, is available. Is it using string comparison for versions...?

### Operating system:

macOS 11.0.1

### Subsurface version:

4.9.10 as distributed by Homebrew

### Steps to reproduce:

Start 4.9.10, or after start use Help -> Check for updates.

<img width="562" alt="Screen Shot 2020-11-25 at 12 14 14" src="https://user-images.githubusercontent.com/125426/100220521-c6bd9a80-2f17-11eb-8752-7dfeb9c8dd19.png">

<img width="532" alt="Screen Shot 2020-11-25 at 12 14 00" src="https://user-images.githubusercontent.com/125426/100220530-c91ff480-2f17-11eb-9bb5-b9d707cb82a3.png">

**Comment by dirkhh** [comment]
Sort of. The actual problem was somewhere else, but it was deciding to call the wrong version "newer" because of a simplistic string comparison.
Either way, fixed now.
Thanks for the report.
