### ISSUE TITLE
Scubapro G2 syncing wrong dive time and can't edited

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#3094]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Last time I synced a dive from Scubapro G2 to my mobile with subsurface mobile 3.1.0 ( 4.9.9.31 ) the dive time was wrong and I was mit possible to edit.
I was able to change the value but I can't save it.
Dive time which was shown 48 min and real time was 57 min.

### Operating system:

Android 9

### Subsurface version:

3.1.0 ( 4.9.9.31 )

### Steps to reproduce:

Syncing a dive

**Comment by dirkhh** [comment]
You can edit the dive time (which is when a dive starts), but a dive with profile has calculates its duration based on the profile - therefore you can't edit the duration.

**Comment by satoschu** [comment]
But why is there a difference in syncing the dive time?
Syncing in Scubapro Logtrak and the value on the dive computer shows 57min and in Subsurface is 48 min?

**Comment by dirkhh** [comment]
Can you post a screen shot of a dive where this is the case? My guess is that you have a surface interval (or an extremely shallow interval) in the middle?

**Comment by satoschu** [comment]
Yes, there is a part on the surface in the dive profile.

**Comment by dirkhh** [comment]
Well, I guess then we will just have to agree to disagree. The Subsurface developers believe that the duration of a dive is the time that you are actually _diving_. So the dive below, in our mind, is a 10 minute dive, not a 2 hour dive.
<img width="1403" alt="Screen Shot 2020-12-13 at 12 04 39 PM" src="https://user-images.githubusercontent.com/237471/102022389-657d3000-3d3b-11eb-84ba-9cdb1175357a.png">

**Comment by satoschu** [comment]
Hello Dirk, thank you for the description of the functionality of subsurface. Have a nice evening!
