### ISSUE TITLE
Subsurface-mobile: tiny tank change icon on some screens

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#310]
reported by @willemferguson

**Comment by neolit123** [comment]
@willemferguson @janmulder did we resolve this?

**Comment by janmulder** [comment]
Not resolved at this point (2.0 from play store).

**Comment by dirkhh** [comment]
Darn - more stuff that needs fixing. I'll raise the priority to high as gas changes are quite important to have _visible_ in the profile.
