### ISSUE TITLE
Dive Download Error

### ISSUE THREAD

**Issue by district1130** [subsurface/subsurface#3104]
### Describe the issue: Dive downloader fails with "Unsupported Operation" error at the bottom.

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description: 
Libdivecomputer log is as follows: 

Subsurface: v4.9.10, built with libdivecomputer v0.7.0-devel-Subsurface-NG (e58a5866bbd6d12fba7b3482c11d0ae2bed2e1c4)
[0.000000] ERROR: Failed to get the configuration descriptor (LIBUSB_ERROR_NOT_FOUND). [in src/usb.c:318 (dc_usb_iterator_next)]

### Operating system: 
macOS 11.0.1 Big Sur

### Subsurface version: 
v4.9.10, built with libdivecomputer v0.7.0-devel-Subsurface-NG (e58a5866bbd6d12fba7b3482c11d0ae2bed2e1c4)

### Steps to reproduce: 
Attempt to download from Atomic Cobalt 2, connected via USB.

### Current behavior: 
Error message "Error, unable to open Atomic Aquatics (Cobalt 2)" comes up, and the connection fails.

### Expected behavior: 
Dive computer acknowledges connection, and dives are downloaded (worked find as of Subsurface 4.3

### Additional information: 
Firmware updated over the same connection, the issue doesn't appear to be a hardware issue, or an OS problem.

**Comment by anicolao** [comment]
Same error with a Cobalt 1 computer on a later version. 

```
Subsurface: v5.0.4, built with libdivecomputer v0.8.0-devel-Subsurface-NG (b6df353752b659654919eec3e98ced02158456d1)
[64.947298] ERROR: Failed to get the configuration descriptor (LIBUSB_ERROR_NOT_FOUND). [in src/usb.c:318 (dc_usb_iterator_next)]
```

Any updates/workarounds?

**Comment by anicolao** [comment]
Bizarrely, after downloading a few dives using macdive to verify that the dive computer USB connection was working, it started working in subsurface. :(

**Comment by anicolao** [comment]
I don't know why this is closed. Having to use another piece of software to get Subsurface to work seems in no way a fix to me.

Some sort of explanation of why this is expected behaviour would be better, or a better workaround than downloading and running trial closed-source software to fix the problem.
