### ISSUE TITLE
I install an update 4.6.3 No Dives 

### ISSUE THREAD

**Issue by micado2055** [subsurface/subsurface#316]
I have 44 dives i cloud before update after the update I imported a dive from my divecomp and this is the only div I have!! I cant find my other dive!!!!

**Comment by dirkhh** [comment]
That's strange. Can you send me the email address that you use for cloud storage? I should be able to see what happened on the backend. Please send it to dirk at hohndel.org

**Comment by dirkhh** [comment]
Did I miss your email? Just wanting to make sure that I'm not ignoring you by mistake.

**Comment by neolit123** [comment]
closing this issue due to lack of user feedback.
