### ISSUE TITLE
Profile shows unexpected bearing if cursor is after the end

### ISSUE THREAD

**Issue by PeterZaal** [subsurface/subsurface#3184]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Just a very small thing I noticed. See attached image: when the cursor is placed somewhere after the end of the dive, the profile shows an extra 'bearing: 0' line.

### Operating system:
Windows 10 Home

### Subsurface version:
4.9.10 official, 4.9.10-421 from test

![bearing](https://user-images.githubusercontent.com/27209378/105755285-6369dc00-5f4b-11eb-84cd-123b3f263a0c.png)

**Comment by beckjoj** [comment]
@dirkhh I think this is closed as of 7e6d993, right? Seems automation didn't catch it given you had to clean up the commits (sorry!) and the PR wasn't merged.

**Comment by dirkhh** [comment]
Correct - my fault for not closing it.

**Comment by PeterZaal** [comment]
Just a short confirmation that I checked with latest official 5.0.4. and this is indeed resolved, thanks.
