### ISSUE TITLE
Small bug in Android version of statistics tool

### ISSUE THREAD

**Issue by willemferguson** [subsurface/subsurface#3192]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When the statistics tool is active and one hits the Android BACK button (bottom right on my device), Subsurface terminates. I have no evidence that this is a crash. It is probably just an erroneous termination that has not been set to return to the dive list.

**Comment by bstoeger** [comment]
Is there a way to reproduce this on MobileOnDesktop? There is no back-button when on the statistics page for me.

**Comment by dirkhh** [comment]
There's code in many places to 'catch' the back behavior... if we don't catch it, the app terminates on Android (it's literally the official way to exit an app). I need to check and see why this isn't on the statistics page. I thought I added this but we refactored the code quite a few times during its development :)

**Comment by dirkhh** [comment]
BTW - Alt-left simulates the back button for me with Mobile-on-Desktop for Linux
