### ISSUE TITLE
XML data UDDF error when exporting from Subsurface

### ISSUE THREAD

**Issue by UserSBSRF** [subsurface/subsurface#3195]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The UDDF Xml formatting created by the Subsurface export function is not compatible with the UDDF standard.

The produced file contains unknown XML tags in the UDDF standard

The following sequences contained in the UDDF file are not recognized by the standard
          \<notes>
             \<para />
           \</notes>
           \<rating>
             \<ratingvalue />
           \</rating>
           \<visibility />

### Subsurface version:

 4.9.10

official release

**Comment by mturkia** [comment]
All the tags you mention are in the [UDDF 3.2.1](https://www.streit.cc/extern/uddf_v321/en/index.html) standard

**Comment by UserSBSRF** [comment]
> All the tags you mention are in the [UDDF 3.2.1](https://www.streit.cc/extern/uddf_v321/en/index.html) standard

Hello,

Your answer is far too succinct.

You should read or reread the complete information about the uddf standard before responding.

It is not enough just to stack uddf standard tags in the export file.
There are controls to be respected on the mandatory presence of data in the tags.

In the future, be less assertive and more humble, you will gain credibility.

Best regards

**Comment by atdotde** [comment]
> In the future, be less assertive and more humble, you will gain credibility.

I think this is great advice for everybody.
