### ISSUE TITLE
Edit dive in planner gets confused with dive handlers

### ISSUE THREAD

**Issue by atdotde** [subsurface/subsurface#3210]
Start with the attached dive, do "edit dive in planner". In the list of waypoints, go to runtime of 16min and control click on the trash bin. This will delete all further waypoints. Then leave the planner with "cancel". 

Back in the dive list, once more do "edit dive in planner". Either it crashes immediately or when your repeat the above delete step, it gets confused with the dive handlers and still shows some of the deleted ones (see screenshot).

I found this in current master, but the problem already existed in 16f86f2f65e73935496e3324bb16f9b8cd4d7953.

[handlers.ssrf.log](https://github.com/subsurface/subsurface/files/6064711/handlers.ssrf.log)

<img width="460" alt="Screenshot 2021-03-01 at 21 45 34" src="https://user-images.githubusercontent.com/863957/109564520-77bc6e00-7ae1-11eb-8606-d24df78e20c6.png">

@bstoeger you did something to the dive point model, any idea?

### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

**Comment by bstoeger** [comment]
I will look into this tomorrow.

**Comment by bstoeger** [comment]
Well, a very easy way to make it reliably crash is to CTRL-delete *all* dive points.

**Comment by atdotde** [comment]
Oops. 

At least, the last release seems not to be affected.

**Comment by bstoeger** [comment]
I fixed the crash with "delete all points" in #3186. It still behaves strangely, but at least I couldn't make it crash easily.

**Comment by bstoeger** [comment]
Could you please check if the problem is fixed (by chance) by the rather radical changes in #3186?

**Comment by atdotde** [comment]
Will do. Hopefully later tonight, otherwise tomorrow.

**Comment by atdotde** [comment]
Indeed, it seems #3186 fixes this.

**Comment by atdotde** [comment]
Trying the on the 5.0.0 release crashes subsurface upon opening the dive in the planner the first time. I vote for including #3186 hopefully soon in a 5.0.1 as that version is definitely an improvement to the current state.
