### ISSUE TITLE
It is too easy to delete a dive by mistake on iOS

### ISSUE THREAD

**Issue by nano-o** [subsurface/subsurface#3212]
When a dive is selected from the dive list, a delete button appears next to the edit button. If I press the delete button, the dive is immediately deleted, without prompting for confirmation. This makes it very easy to delete a dive by mistake. I know this can be undone through another menu, but I think it would be better to prompt for confirmation before deleting.

Version: 3.1.2(4.9.10.139)
iOS 14.3

**Comment by dirkhh** [comment]
This will be removed in the next version
