### ISSUE TITLE
Shearwater Peregrine not in list of supported devices

### ISSUE THREAD

**Issue by tbm** [subsurface/subsurface#3219]
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

Based on the changelog, it seems that the Shearwater Peregrine is supported, but it's not in the list of [supported devices](https://subsurface-divelog.org/documentation/supported-dive-computers/).

**Comment by dirkhh** [comment]
I'll update this with the 5.0 release
