### ISSUE TITLE
Shearwater

### ISSUE THREAD

**Issue by SousaMartins** [subsurface/subsurface#3224]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The Shearwater Perdix connects with the surface and starts importing the data, but few moments after launch an error.
"Dive data import Error"

### Operating system:

Windows 10 Pro 
version 20H2
OS Build 19042.868
Windows Feature Experience Pack 120.2212.551.0

### Subsurface version:

Subsurface 5.0.1
Official Release

**Comment by ryanm101** [comment]
v84 is out now might be worth updating the firmware

**Comment by SousaMartins** [comment]
I will

 

Thanks

 

Sousa Martins

**Comment by dirkhh** [comment]
many, many instances of this issue - in all cases people were able to get it to work eventually.
