### ISSUE TITLE
synchronisation between iPhone and Windos lead to 198 deleted dives.

### ISSUE THREAD

**Issue by thpe** [subsurface/subsurface#3225]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

There where 202 dives logged into the Windows application on the cloud storage. Newer ones from a dive computer, the older ones manual.
After restart, and reconnecting to the cloud storage, where only 174 dives visible, the older ones (all of the manual inserted) where missing.
At this time the iPhone showed all 202 dives. After a manual synchronisation, i.e., pulling down the dive list on the iPhone to force synchronisation, the iPhone showed only 4 dives, 198 dives deleted.
Reconnecting with the Windows PC and subsurface version 4.9.7. showed also only 4 dives. These 4 where manual inserted, on some random weekend 2 years ago. I don't really see, why only these are left

So, actually two bugs, why was the cloud storage out of sync in the first place?
Why, does the iPhone application just thinks it is a good idea to delete nearly everything on the cloud storage?

Bonus question, how to restore these dives?

### Operating system:

Windows 10 and iPhone SE, new model

### Subsurface version:

4.9.7 on windows, now upgraded to 5.0.1
3.2.0 (5.0.0) on iPhone

### Steps to reproduce:

None, there are no dives left to reproduce this.

### Current behavior:

Synchronisation deletes massive amount of dives without questioning.

### Expected behavior:

Don't delete dives.

**Comment by dirkhh** [comment]
send email FROM the account that you use for the Subsurface cloud to dirk at subsurface-divelog.org, requesting a restore of the data that have disappeared
