### ISSUE TITLE
can't sync with cloud from PC and maybe subusurface-mobile

### ISSUE THREAD

**Issue by emmdarakis** [subsurface/subsurface#3232]
### Describe the issue:
- [ x] Bug

### Issue long description:
Uploaded two dives from my DC to subsurface-mobile this morning and according to the app they are synced to the cloud (eg I get: completed manual sync with the cloud (changes synced locally)). 

Then I am trying to sync them to subsurface desktop. In both windows (tried with v 5.0.0 and 5.0.1)  and linux (v. 5.0.0) I get: "cannot connect to cloud server. working with local copy".
With v 5.0.0 when I try to push it further (eg try again "open cloud storage", or select "cloud storage online") subsurface would just crash. 
With v5.0.1 when I try to push it further  ("open cloud storage", or select "cloud storage online") I just get  "Failure to taking cloud storage online".

Tried visiting https://cloud.subsurface-divelog.org/user/emmdarakis@gmail.com/dives.html and I login in successfully BUT the new dives are not there (indicating that probably sync with the mobile is not successful either). 

Subsurface mobile version 3.2.1(5.0.1) running on a Xiaomi Redmi Note 9 Pro/ MIUI Global 12.0.2/ Android: 10 QKQ1.191215.002
Subsurface : v 5.0.1 and v5.0.0 running in Windows 10 Pro, 20H2, 19042.928 and  v 5.0.0 in Linux Ubuntu 20.10

If needed I can / will attach log files but can't remember how to find them. Let me know how and I will. 

Thanks a lot.

**Comment by dirkhh** [comment]
No, it tells you "changes synced locally" -- in other words, they were NOT saved to the cloud.

As I said on the mailing list - I had an out of memory event on one of the back end servers, one of the critical processes for the storage backend was killed and unfortunately not restarted. The problem is fixed (and the service file was edited to add an automatic restart to it).
