### ISSUE TITLE
Import Logfile nor properly initialized

### ISSUE THREAD

**Issue by RobertAngermayr** [subsurface/subsurface#3246]
### Describe the issue:
- [ ] Bug

### Issue long description:
When calling the dialog from the menu and after selecting the file to be imported (in my case a .apd file APD - Log Viewer ) the dialog shows in the selection combobox APD - Log Viewer - DC1 what is correct, but the fields are not initialized with the given tags for APD files - the fields are shown like "Manual import".
So i have to select another import type from the combobox and tags switch back to "APD - Log Viewer - DC1" than it shows the proper tags for the fieldlist.
When changing the language in subsurface to english (UK) the dialog is properly initialized!

### Operating system:
Windows 10 latest version german language

### Subsurface version:
Subsurface 5.0.1
official release / installer

### Steps to reproduce:
1, menu "Import"
2. click "import log files"
3. select a *.apd file"
4. check combobox and field - tags.
5. change subsurface language to german and repeat the steps.
6. change subsurface language to english (UK) and repeat the steps.

[08D006582_210228_085648.zip](https://github.com/subsurface/subsurface/files/6458787/08D006582_210228_085648.zip)

### Current behavior:
dialog depending on the language initialized.

### Expected behavior:
dialog initialized language independend and properly.

**Comment by atdotde** [comment]
It's not entirely clear to me where the fields are refilled, but given that it seems to be an issue with i18n, the candidate would be DiveLogImportDialog::setup_csv_params Maybe a typo? Should check, if it's specific to German or other languages are affected as well. Hope to have some time for this a bit later.
