### ISSUE TITLE
Drop down menu is shifted on Fedora 34 on multiple monitors

### ISSUE THREAD

**Issue by drakche** [subsurface/subsurface#3255]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When installing from the package and If I have multiple monitors connected I get  the problem that the menu is offset
![image](https://user-images.githubusercontent.com/445702/119660082-21847000-be2f-11eb-889e-b3156e4543a1.png)
![image](https://user-images.githubusercontent.com/445702/119661145-4b8a6200-be30-11eb-9e3c-63dc88475da0.png)
![image](https://user-images.githubusercontent.com/445702/119661193-57762400-be30-11eb-80c1-c623a38d8347.png)

This doesn't not occur when I disconnect the rest of the monitors

### Operating system:

Fedora 34, Gnome, English

Dell XPS15 9500

### Subsurface version:

Subsurface 5.0.1

Yes

Official release from the OBS

### Steps to reproduce:

Have multiple monitors connected in different layout than horizontal.
![image](https://user-images.githubusercontent.com/445702/119660813-f0f10600-be2f-11eb-87a3-22b73ebc87fc.png)

### Current behavior:

When opining the menu it's offset. And not displayed under the toolbar item.

### Expected behavior:

For the menu to be displayed under the toolbar item.

**Comment by dirkhh** [comment]
I have no idea what would cause that, but my obvious guess would be a Qt/Gnome incompatibility.
I don't have access to such an elaborate monitor setup, so I cannot reproduce this... so... 🤷🏼‍♂️

**Comment by drakche** [comment]
This started after the update to Fedora 34.
The display engine is Wayland.

Also, one thing I did notice is that when running the app though appImage it works fine.

**Comment by dirkhh** [comment]
Which only confirms my statement that this is a Qt/Gnome incompatibility.
Because the AppImage is linked against (and includes) a much older Qt version than is native on Fedora 34.
So my suggestion would be to file a bug against Fedora since this is a problem in the libraries they ship, not in Subsurface.
