### ISSUE TITLE
Scubapro A2 not recognized as dive computer

### ISSUE THREAD

**Issue by gioaudino** [subsurface/subsurface#3287]
### Describe the issue:

- [X] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Scubapro Aladin A2 computer is not recognised as a dive computer.

### Operating system:
OnePlus Nord w OxygenOS 11.1.1.3 (based on Android 11)

### Subsurface version:
Subsurface mobile 3.2.1 (5.0.1)

### Steps to reproduce:
Try to connect Scubapro Aladin A2 to Subsurface mobile

### Current behavior:
The computer doesn't appear on the list of devices, despite logTrak can correctly and easily connect to the computer and download dive information.

### Expected behavior:

The computer connects.

### Additional information:
```
Device found "A2" "<address>" isLeScanResult true Manufacturer data size: 1 "{0000180f-0000-1000-8000-00805ffcf9b34fb}"
"Discovered new device: 'A2' [LE:<address>]: " not recognized as dive computer"
```

**Comment by dirkhh** [comment]
Correct - you can override this temporarily in the settings. I'll need to release a new version of Subsurface mobile to fix this permanently. Thanks for pointing it out
