### ISSUE TITLE
"Water type/Density" is not editable?

### ISSUE THREAD

**Issue by oontvoo** [subsurface/subsurface#3292]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
The "Water type/Density" box in "Information" type shows a value of "unknown" and is not editable.

### Operating system:
OS: MacOS, BigSur
Dive computer model: Cressi Giotto

### Subsurface version:
Version: 5.0.2, official release
(Same issue in previous versions as well)

### Steps to reproduce:
- Import a dive from the dive computer
- Go to "Information" tab
- Look at the Water type/Density box.

### Current behavior:
The value is shown as "unknown" and is not editable

### Expected behavior:
Please allow adjusting this value.

**Comment by dirkhh** [comment]
In the preferences, go to Dive Log and enable "In the Information tab, allow editing of water salinity"
Now you can do so.
Please note, however, that this almost certainly doesn't do what you might think it does. The depth information that you got in the dive computer profile during download will not change.
