### ISSUE TITLE
Graphics when there are two computers

### ISSUE THREAD

**Issue by Energia00** [subsurface/subsurface#3293]
Con la versione 5.0.2 non riesco a passare da un grafico all'altro premendo i tasti freccia destro/sinistro e resto sempre sul computer 1/2

I cannot switch between graphs by pressing the left / right arrow keys and I can see only computer 1. The version is 5.0.2

**Comment by atdotde** [comment]
Same here. I tried mapping that to other keys (as cursor keys might be used elsewhere) but that did not help.

**Comment by mturkia** [comment]
Works on my Linux. I think @atdotde uses Mac, what is your operating system @Energia00 ?

**Comment by Energia00** [comment]
> Works on my Linux. I think @atdotde uses Mac, what is your operating system @Energia00 ?

Windows 10
