### ISSUE TITLE
Windows application crash on right click of collapsed dive trip

### ISSUE THREAD

**Issue by TheAngusBurger** [subsurface/subsurface#3302]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
The windows application version of subsurface crashes when you right click a collapsed dive trip (/folder) that contains a number of dives in it. When expanded, the application functions correctly.

### Operating system:

Windows 10 Pro, Version 19043.1165

Windows Desktop

### Subsurface version:

5.0.2

Not tried on alternative version.

Official release.

### Steps to reproduce:

1) Create a blank new dive (log->add dive)
2) Place the dive in a new trip (right click dive, 'create new trip above')
3) Collapse the folder by clicking the arrow to the left side of the name
4) Right click the folder and the application should crash

This occurs whether you create a dive or import it, whether it has information in it or not.

### Current behavior:

Application crashes

### Expected behavior:

Application does not crash. The correct context menu appears (same as when the dive trip folder is expanded).

**Comment by bstoeger** [comment]
Thanks for the report.
@mturkia was a bit faster: #3301.
