### ISSUE TITLE
Subsurface-mobile: time parsed incorrectly

### ISSUE THREAD

**Issue by mturkia** [subsurface/subsurface#331]
Looks like the time is read in as GMT when adding new dives on Subsurface-mobile. Thus my manually added dive ends up with time 3 hours before the time I entered.

**Comment by dirkhh** [comment]
with which version - I changed the code that handles this a few days ago

**Comment by mturkia** [comment]
iphone  and android 4.6.3.245

**Comment by dirkhh** [comment]
Building new binaries as we speak. The fix is more recent than 4.6.3.245. No idea why I didn't push new binaries, TBH

**Comment by dirkhh** [comment]
Please test the new binaries and report back if this is fixed. Thank you.

**Comment by mturkia** [comment]
Seems to work now on both mobile versions.
