### ISSUE TITLE
CNS and OTU calculations seems wrong in some cases (CCR + bailout exit)

### ISSUE THREAD

**Issue by desu-wtf** [subsurface/subsurface#3310]
### Describe the issue:

- [x] Bug

### Issue long description:
It seems that calculated values of CNS and OTU are too low in some cases, particularly in CCR dives with bailout deco on OC.

### Operating system:
macOS 10.14.6

### Subsurface version:
5.0.2

### Steps to reproduce:
1). Go to "Plan dive" mode
2). Set two gases: Air and EAN50
3). Set depth 40 meters with runtime 80 minutes
4). Set Dive mode: CCR, set checkbox "Bailout: Deco on OC"
5). Set GF 40/80

This is not a real plan, just an example.

### Current behavior:
CNS: 13%
OTU: 41

### Expected behavior:
Approximate values that seems to be correct:
CNS: 67%
OTU: 179
These are calculated using Android version of MultiDeco. I'm not telling MultiDeco is something should be trusted more than Subsurface, but CNS and OTU calculations are pretty close with them when planning pure OC or pure CCR dives.

### Additional information:

Also I've tried to calculate something on paper using this article https://www.borrett.id.au/downloads/cns_percentage_tracking_v1-1.pdf

```
Subsurface (5.0.2.0) dive plan created on 8/17/21
Runtime: 176min, Stop times: + 6:04 /m + 1:31 /min

  | depth | duration | runtime | gas
➘ | 40m | 2min | 2min | air (SP = 1.3bar CCR)
➙ | 40m | 78min | 80min |  
- | 40m | 1min | 81min | air Open circuit
- | 21m | 3min | 84min | EAN50
- | 18m | 3min | 87min |  
- | 15m | 6min | 93min |  
- | 12m | 10min | 103min |  
- | 9m | 14min | 117min |  
- | 6m | 19min | 136min |  
- | 3m | 37min | 173min |  
➚ | 0m | 3min | 176min |  
```

78 min on ppO2 1.3 is 0.56*78=43.68%. After 90 minutes it will be half of that, 21.84%. Of course in reality there is further increment in the ascent part that I haven't tried to calculate, but there is no way CNS could be 13% at the end of the dive at 176 minute.

Considering all above I believe current planner's calculations are not correct, probably they are not taking to the account the OC part of the dive. Please have a look.

**Comment by atdotde** [comment]
Thanks for the report. Your believe was correct.
