### ISSUE TITLE
Suunto Eon Steel (with buhlmann upgrade) unable to open in subsurface 

### ISSUE THREAD

**Issue by simenon** [subsurface/subsurface#3317]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I think the issue arose after the buhlmann upgrade of the eon steel. Since then i am unable to connect ot the EON Steel. I have updated to the lates 5.0.3 version of subsurface. I tried also with the Eon Steel Black but that doesn't either connect.

![image](https://user-images.githubusercontent.com/6181557/132093983-b1fb4927-ffa1-44db-b435-515ba03fba5f.png)

### Operating system:

Windows 10

Suunto Eon Steel (with buhlmann upgrade)

### Subsurface version:

5.0.3

release

### Steps to reproduce:

Connect Eon Steel to USB and try to import

### Current behavior:

Can't find Eon Steel

### Expected behavior:

Should find Eon Steel and import

### Additional information:

I am not sure if this is a similar issue https://groups.google.com/g/subsurface-divelog/c/OFmauByHrXE/m/bd4RvBAzCAAJ 

USB information
```
    =========================== USB Port2 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 1-2
Properties               : 0x01
 IsUserConnectable       : yes
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no
 PortConnectorIsTypeC    : no
ConnectionIndex          : 0x02 (Port 2)
CompanionIndex           : 0
 CompanionHubSymLnk      : USB#ROOT_HUB30#5&706fdfd&1&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
 CompanionPortNumber     : 0x04 (Port 4)
 -> CompanionPortChain   : 1-4

      ========================== Summary =========================
Vendor ID                : 0x1493 (Suunto)
Product ID               : 0x0036
USB Version              : 2.00 -> wrong, Device is Full-Speed only
Port maximum Speed       : High-Speed (Companion Port 1-4 supports SuperSpeed)
Device maximum Speed     : Full-Speed
Device Connection Speed  : Full-Speed
Self powered             : no
Demanded Current         : 100 mA
Used Endpoints           : 4

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB Input Device
Device Path              : \\?\USB#VID_1493&PID_0036#00000000#{a5dcbf10-6530-11d2-901f-00c04fb951ed} (GUID_DEVINTERFACE_USB_DEVICE)
Kernel Name              : \Device\USBPDO-14
Device ID                : USB\VID_1493&PID_0036\00000000
Hardware IDs             : USB\VID_1493&PID_0036&REV_0000 USB\VID_1493&PID_0036
Driver KeyName           : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0027 (GUID_DEVCLASS_HIDCLASS)
Driver                   : \SystemRoot\System32\drivers\hidusb.sys (Version: 10.0.18362.175  Date: 2019-09-27)
Driver Inf               : C:\WINDOWS\inf\input.inf
Legacy BusType           : PNPBus
Class                    : HIDClass
Class GUID               : {745a17a0-74d3-11d0-b6fe-00a0c90f57da} (GUID_DEVCLASS_HIDCLASS)
Service                  : HidUsb
Enumerator               : USB
Location Info            : Port_#0002.Hub_#0003
Location IDs             : PCIROOT(0)#PCI(1C06)#PCI(0000)#USBROOT(0)#USB(2), ACPI(_SB_)#ACPI(PCI0)#ACPI(RP07)#PCI(0000)#USBROOT(0)#USB(2)
Container ID             : {bb0215a4-514d-5f72-a97a-e42014d13c7b}
Manufacturer Info        : (Standard system devices)
Capabilities             : 0x94 (Removable, UniqueID, SurpriseRemovalOK)
Status                   : 0x0180600A (DN_DRIVER_LOADED, DN_STARTED, DN_DISABLEABLE, DN_REMOVABLE, DN_NT_ENUMERATOR, DN_NT_DRIVER)
Problem Code             : 0
HcDisableSelectiveSuspend: 0
EnableSelectiveSuspend   : 0
SelectiveSuspendEnabled  : 0
EnhancedPowerMgmtEnabled : 1
IdleInWorkingState       : 0
WakeFromSleepState       : 0
Power State              : D0 (supported: D0, D2, D3, wake from D0, wake from D2)
 Child Device 1          : HID-compliant vendor-defined device
  Device Path            : \\?\HID#VID_1493&PID_0036#9&18ef547d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (GUID_DEVINTERFACE_HID)
  Kernel Name            : \Device\000000a1
  Device ID              : HID\VID_1493&PID_0036\9&18EF547D&0&0000
  Class                  : HIDClass
  Driver KeyName         : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0028 (GUID_DEVCLASS_HIDCLASS)

```

**Comment by dirkhh** [comment]
So this device shows the new `USB ID VID 1493 / PID 0036` which is supported in Subsurface 5.0.3
Please try to download again, but in the download dialog click on "Save libdivecomputer logfile". Send that logfile and also the two Subsurface logfiles that you can find (after you exit Subsurface) in `C:\Users\Home\AppData\Roaming\Subsurface` : `subsurface_out.log` and `subsurface_err.log`

**Comment by simenon** [comment]
[subsurface.log](https://github.com/subsurface/subsurface/files/7111256/subsurface.log)
[subsurface_err.log](https://github.com/subsurface/subsurface/files/7111257/subsurface_err.log)
[subsurface_out.log](https://github.com/subsurface/subsurface/files/7111260/subsurface_out.log)

**Comment by dirkhh** [comment]
Errors aren't insightful at all. All it tells me is that it can't connect to the HID device. Duh, yeah, that was obvious.
We need more interesting error messages :)

Joking aside... let me dig into this some more and try to figure out what's going on. I don't have an EON Steel Black, but Linus does. Maybe I can borrow his and try it with my Mac and figure out what's up.

**Comment by simenon** [comment]
I recently had a windows update failure resorting me to fully reinstall windows, and guess what, the problem is gone. Subsurface sees the EON Steel Black and can download dives through USB. I guess it was a windows/driver issue
