### ISSUE TITLE
Info text printed into progress bar during DC download (OSTC 2N) not really useful

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#335]
During DC download there is some text coming from libdc printed next to the progress bar.
In my example with a HW OSTC 2N wie USB this text replaces the "xx%" value only at the end of the download which is not really usefull or nice.

If anyone is able to fix this in a way that while downloading we have constant updates of the text showing e.g. the current dive beeing downloaded that would be nice. Otherwise I personally would remove this feature and only&always show the "xx%" value.
If this already today gives much nicer results for other DC then keep it as it is.

See picture:
![subsurface_dc_download](https://cloud.githubusercontent.com/assets/25316050/25290240/7d64d52a-26cd-11e7-8f5b-fe2c0b2dee53.PNG)

**Comment by dirkhh** [comment]
Looking at the code, this text appears to come from libdc_header_parser() in libdivecomputer.c and should be updated for every dive that you download. Are you saying that even if you are downloading multiple dives (i.e., downloading into an empty logbook), the text only shows up once, at the very end, with one text talking about a "Dive 1"?

**Comment by sfuchs79** [comment]
It shows up only at the very end of the download with one text talking about the **last dive** downloaded. So if there is only one dive it says "Dive 1:..." if n dives "Dive n:...". All the other time before I see the "xx%" value beeing displayed correctly.

**Comment by dirkhh** [comment]
I played a bit, using the libdivecomputer simulator. And indeed, for those dive computers that parse while downloading, the updates are useful. But for divecomputers like the OSTC that first download, then parse, it's not.
Of course now I need to figure out how to tell a from b - but I think I have an idea.

**Comment by janmulder** [comment]
@dirkhh: the libdivecomputer simulator ... where can I find that? I found (an old) src tarball on Jef's website, and precompiled binaries, but I would like to use it for a recent libdb version, not some old (end 2014 libdc code). 

I am trying to find a CCR setpoint related bug (which looks suspiciously related to the the TestParse issue you put on the mailing list), but up to now, I am not sure if it is OSTC3 firmware, libdc or ssrf code. So with this, a simulator would be nice.

**Comment by sfuchs79** [comment]
@dirkhh 
Works here as expected. No more useless text at the end, only the xx% values. Thanks!

Unfortunately I now saw another not translated text right there. I will change it and do a pull request. Don't know if you want to do the translation loop again. The text is for sure minor important.

**Comment by glance-** [comment]
@janmulder the libdivecomputer simulator is a series of patches ontop of libdivecomputer, and the simulator doesn't have any support for simulating a OSTC3. I have some skeleton code for that laying around but nothing thats even close of working.
