### ISSUE TITLE
Subsurface-desktop: At main page, Depth and Duration column name is not aligned to the left.

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#344]
Hello.

Main-page: Depth and Duration  |  http://prntscr.com/f0925r

Subsurface-version : 	subsurface-4.6.3-287-g51ee9d4405d5.exe  |  2017-04-23 12:54  |  57M

**Comment by dirkhh** [comment]
IIRC (and this was done quite a while ago), we ended up deciding to mirror the alignment of the data with the alignment of the header. And depth and duration data are both aligned right, while the other fields are aligned left. So I would consider this intentional.

**Comment by Ghalr** [comment]
Thank you. :)
