### ISSUE TITLE
Subsurface-desktop: Preferences>Georeference>Dive Site Layout : Strings are not translated, but translated in Transifex

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#345]
Hello.

Tried French and German language and I noticed that strings into this category (Georeference>Dive Site Layout) are not translated even if they are in Transifex (and translated).

http://prntscr.com/f09zck

Subsurface-version : subsurface-4.6.3-287-g51ee9d4405d5.exe | 2017-04-23 12:54 | 57M

**Comment by dirkhh** [comment]
Hmm. Odd. Looks like a bug. I'll investigate.

**Comment by sfuchs79** [comment]
@janmulder 
The easy way of fixing it by only adding the missing tr(); doesn't seem to work. Could this be similar to:
https://github.com/Subsurface-divelog/subsurface/commit/5c89115efe3bf542b3885ce4a1c6dfc03e755b95

**Comment by janmulder** [comment]
@sfuchs79. Could well be something like the one I fixed in https://github.com/Subsurface-divelog/subsurface/commit/5c89115efe3bf542b3885ce4a1c6dfc03e755b95.

**Comment by janmulder** [comment]
@sfuchs79 (and @dirkhh). I have a fix, but running now time now to do a PR. First thing tomorrow.

**Comment by dirkhh** [comment]
Awesome - I won't do a release until later this week, possibly the weekend, so this is fine.
Thanks for the heads up

**Comment by Ghalr** [comment]
Thank you so much.
