### ISSUE TITLE
Subsurface-desktop: Usersurvey do not have "Subsurface" version strings translated

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#348]
Hello.

I noticed that "Subsurface" version is not translated, everything is fine but I found it interesting to change to

Subsurface version:

This is just a user friendly feature to fit with other strings who got the ponctuation   :    and this will allow to fully translate into our respective language. 

Thanks.

**Comment by janmulder** [comment]
you mean the 4 lines at the bottom of the survey? Like (in Dutch):

Subsurface 4.6.3.289
Besturingssysteem: Linux (Arch Linux)
Centrale verwerkingseenheid: x86_64
Taal: nl-NL

Well, this looks perfectly translated.

You seem to suggest to change the fist line to "Subsurface versie: 4.6.3.289" ... well ... IMHO not very relevant.

**Comment by Ghalr** [comment]
Yes I meant those lines, this is exactly what I want to suggest.

**Comment by dirkhh** [comment]
I don't think this really makes any difference
