### ISSUE TITLE
Ability to overwrite cloud based log too easily

### ISSUE THREAD

**Issue by flashadams** [subsurface/subsurface#351]
Setting up a new computer on my "cloud" profile and in tooling around I was able to very easily delete all dives I had saved to the cloud. 

reproduce: entered in my credentials to cloud provider, then clicked on new dive log and then accidentally clicked save to cloud. And sure enough it saved my new BLANK log to my cloud without any notification of overwrite/etc.

Windows 10
version 4.6.3

**Comment by dirkhh** [comment]
Thanks for reporting this here - I'll try to understand why you weren't warned about this when I have a moment :-/

**Comment by dirkhh** [comment]
This was fixed by #690
