### ISSUE TITLE
dive duration format

### ISSUE THREAD

**Issue by SamuelBenard** [subsurface/subsurface#361]
On main screen, dive duration should be either in minutes or in hours:minutes but not a mix of both.
Let's say I have 3 dives of 27, 54 and 62 minutes.
actually I have : 
27, 54, 1:02
I should have either : 
27, 54 and 62 
or
00:27, 00:54, 01:02

On this screenshot, you can see that I have duration in minutes but for dive 673, it switches to 1:00

![capture du 2017-04-29 10-58-04](https://cloud.githubusercontent.com/assets/1573802/25554687/66f18726-2ccb-11e7-96b1-c04a73b042a2.png)

**Comment by dirkhh** [comment]
See my comments on the other issue. In a way I'd say this all makes sense. But I can see that this isn't as consistent as you might want it... I'll need to think some more about how to make this better.
