### ISSUE TITLE
Merged dives lose gas changes

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#364]
Started with 2 dives, both with multiple gas change events. These gas change events are missing from the merged dive. To be complete in my description. Both dives are pSCR dives, and are approx 3.4 hours apart. But I can not imagine (without looking at any code yet) that this would make any difference.

**Comment by dirkhh** [comment]
Can you export the two dives as XML, send them to the mailing list and ask Linus to take a look?

**Comment by janmulder** [comment]
Done.

**Comment by janmulder** [comment]
Fixed in 9084bbae578b3996d8e8c7adb74ef9bb25da6720
