### ISSUE TITLE
Translation error when merging dives that are >90 min apart

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#365]
The dialog box that pops up when you try to merge 2 dives that are more than >90 min apart, is not translated. The code that generates this warning box does contain tr() style translations, but a check in the ts files shows no sting to translate ... so a weird and seemingly new class problem: no string to translate is generated ... so no translation is provided.

**Comment by dirkhh** [comment]
I know, I could search myself, but since you already checked, can you provide a pointer to file / line number? That way it's really easy for me to see why the tooling fails to pick this up.

**Comment by janmulder** [comment]
divelistview.cpp, line 587
