### ISSUE TITLE
Losing tags when adding new dive on windows

### ISSUE THREAD

**Issue by VA2XJM** [subsurface/subsurface#369]
Hi,

I just updated Subsurface and I really like the new way to add flat profile dives using BT and Max Depth.

Now a bug I have is that when I add a new dive, if I input the tags prior to apply the changes, all data will be saved except the tags, so I need to input the tags again.

**Comment by dirkhh** [comment]
Wow, that is indeed a bug. I'll try to track this down. Thanks for the report.
