### ISSUE TITLE
Some ideas to improve dive-planning functionality for technical diving

### ISSUE THREAD

**Issue by trimix25** [subsurface/subsurface#381]
Hallo,

da ich leider keine andere Möglichkeit zur Kontaktaufnahme mit dem Entwicklerteam gefunden habe, probiere ich es über diesen Kanal.
Ich bin VDST/CMAS Trimix Instructor und habe mich umfassend mit den Funktionen des implementierten Tauchgangs-Planer beschäftigt. Ich bin begeistert! Saubere Arbeit. Euer Projekt kann locker mit den kommerziellen Tauchgangsplanern wie MultiDeco, V-Planner, GAP etc. mithalten.
Wie auch bei den kommerziellen Tauchgangsplanern fehlt jedoch noch die ein oder andere Funktion um das Tool in der Praxis sowie in Kursen Tauchverbands-übergreifend optimal einsetzen zu können.
Ich würde hierzu gerne einige Ideen einbringen, die sicherlich nur einen sehr geringen Programmieraufwand erfordern. Über eine Kontaktaufnahme würde ich mich sehr freuen:
E-Mail: jan[at]jan-network.de

Beste Grüße
Jan

**Comment by mturkia** [comment]
Guten Abend,

Traditionally we have used developer mailing list subsurface@subsurface-divelog.org for discussing ideas and development in general. However, using issues on Github is also recommended so we can easily track the suggestions, ideas and bugs.

**Comment by dirkhh** [comment]
@atdotde : hast Du Kontakt zu Jan aufgenommen?

**Comment by atdotde** [comment]
I sent him an email with the offer to contact me directly. So far he did not. I guess for the time being, you can close this issue.

**Comment by neolit123** [comment]
closing as suggested by @atdotde
