### ISSUE TITLE
Wrong gas usage caculation

### ISSUE THREAD

**Issue by OberfragGER** [subsurface/subsurface#397]
Hey,

i´ve imported my dives from SmartTrack (Galileo Sol Trimix). I dive with a double 7 tank - that means 14 liters. All the imported data means its a single 15 liter tank. If i switch to D7 (double 7), i have a lower gas utilisation that in smarttrack calculated.

For instance:
I choose 14liters @☺ 200bar start pressure an 100bar end pressure
100bar * 14liters = 1400 liter gas usage

but subsurface shows in the information tab 1279liters gas usage. thats lower than expected.
whats wrong or what is missing...?

**Comment by glance-** [comment]
Air doesn't behave as a ideal gas at those pressures, and we actually factor in that in our calculations.

Take a look at https://subsurface-divelog.org/documentation/subsurface-4-user-manual/#S_APPENDIX_F for more information.

**Comment by atdotde** [comment]
I explained here http://euve10195.vserver.de/wp/?p=129 why the difference to an ideal gas is larger than what you might have expected.
