### ISSUE TITLE
Mobile: import from DC does not correctly number new dives

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#408]
As the title says. I imported 3 new dives in mobile (both mobile on desktop as mobile on mobile, with hacked id from my OSTC3), but they all have #0.

Looking trough the new code to add the new dives to the divelist, (visually and with the debugger) I see that the try_to_renumber() code is not executed for mobile adds ... not sure how to fix this at this point, so this issue instead.

**Comment by dirkhh** [comment]
I noticed this as well but forgot to file an issue so I'd remember :-)
Thanks. Definitely one of many bugs still hidden in the mobile code. Or let's call it "opportunity for further improvement".
