### ISSUE TITLE
[idea] Mobile UI #7: Dive list EOL and Swipe To Refresh

### ISSUE THREAD

**Issue by Bocio** [subsurface/subsurface#432]
Previous idea here:
[Mobile UI #1: general layout](https://github.com/Subsurface-divelog/subsurface/issues/425)
[Mobile UI #2: default action for main screen button](https://github.com/Subsurface-divelog/subsurface/issues/426)
[Mobile UI #3: Dive list item layout](https://github.com/Subsurface-divelog/subsurface/issues/427)
[Mobile UI #4: Dive list different layouts and menu option](https://github.com/Subsurface-divelog/subsurface/issues/428)
[Mobile UI #5: sidebar](https://github.com/Subsurface-divelog/subsurface/issues/430)
[Mobile UI #6: Dive detail title](https://github.com/Subsurface-divelog/subsurface/issues/431)

All original mockups made with moqups and are online at: (https://app.moqups.com/Bocio/3SSyFCoEwP)

Las but not the least...

## End of the list 

While sometimes I remember I'm a programmer I thought it was a bug.

![swipetorefresh](https://user-images.githubusercontent.com/27133591/26931245-138953a2-4c60-11e7-989b-2a2640d27a9b.JPG)

On android the standard way when you reach begin/end of a listview there is a fading effect on the border. On IOS and other Android apps I guess is still the classic _bungee effect_. 

## Swipe to refresh

We should use a gesture to update the dive list (aka server sync). On Android is called [Swipe To Refresh](https://goo.gl/M6WQ6U) Its' a pattern. 
See my video for swipe to refresh and EOL functionality:

[Swipe to refresh and various](https://www.youtube.com/watch?v=WeTwW0hZPXU)

During the video I disabled network to show you what's happening when you try to update the list.
Trello is a case apart because it works offline. It doesn't give you any feedback. If you edit your list it will synchronize everything later.

Bye

**Comment by dirkhh** [comment]
Forgot to automatically close this one with the last commit. This is implemented by 7b7294d
