### ISSUE TITLE
Dive list filter enhancement(s)

### ISSUE THREAD

**Issue by stuartv666** [subsurface/subsurface#435]
When using filters on the dive list, support some way to select all the entries in each filter criteria list.

Reason: to allow easy filtering for All != 'one specific value'. 

E.g. in the filter list for Location, provide a way to select all the locations in the list at once, so that once specific one can then be unselected. I.e. let me select all the locations and then unselect 'Pool', so that I can see a list off all my "real" dives.

Suggested possible solutions:

- allow multi-select on the list of filter criteria

- provide a "select all" check box at the top of each filter criteria list box

- support Ctrl-A functionality in filter criteria list box

- provide one checkbox for all filter criteria that means "show all that do NOT match".

**Comment by neolit123** [comment]
@tcanabrava hi Tomaz. do you think this is doable?
