### ISSUE TITLE
[Bug] Suunto DM5 log import shows wrong bottom gas

### ISSUE THREAD

**Issue by mjtannin** [subsurface/subsurface#437]
Seems like Subsurface ignores my EAN50 to TM13/45 gas switch at the beginning of one of my dive and shows that I've done 100+m dive with EAN50. Might be issue in Suunto DM5 log format import module?

To replicate, download my [DM4.db log file](https://www.dropbox.com/s/r3bevcrdw9uttyb/DM4.db?dl=0) and check a dive #1067 (Fri May 19, 2017 11:10 am to 106m, duration 2:01). I started the dive with EAN50 and switched to TM13/45 immediately I got below 20 meters (around 1 minute mark).

![subsurface bug](https://user-images.githubusercontent.com/2864010/27069093-daee6af4-501b-11e7-98d5-7af5cce2e93b.PNG)

**Comment by mturkia** [comment]
Fixed in https://github.com/Subsurface-divelog/subsurface/pull/438
