### ISSUE TITLE
Bluetooth disapear

### ISSUE THREAD

**Issue by marccollin** [subsurface/subsurface#443]
I use a petrel 2, habitually when i go in the download menu, I see bluetooth bottom 

but now it seem to have disapear.

![subsurface](https://user-images.githubusercontent.com/4097381/27267465-939de3be-5476-11e7-8402-14e3ef083882.png)

i use 4.6.4

**Comment by glance-** [comment]
Thats probably because you're build of subsurface is done without `BT_SUPPORT` . Where did your binaries come from?

**Comment by marccollin** [comment]
suse

https://build.opensuse.org/package/show/home:Subsurface-Divelog/Subsurface

**Comment by dirkhh** [comment]
The distro specific packages should support Bluetooth. I'll need to figure out what went wrong there... 

Guillaume, I'm traveling today (flying back from China), any chance you could take a look?

Thanks

/D

⁣-- 
From my phone​


-------- Original Message --------

**Comment by ggardet** [comment]
@marccollin which openSUSE version ? And which Subsurface version ?
Here, I have openSUSE Leap 42.2 and subsurface 4.6.4 and I have the bluetooth checkbox.

**Comment by marccollin** [comment]
hi, 

tumbleweed
4.6.4

**Comment by ggardet** [comment]
Indeed, the build log says: 
`[  612s] -- Turning off Bluetooth support as Qt version .. is insufficient for that`
I will try to have a look at it soon.

**Comment by marccollin** [comment]
no problem, will do my rebreather course in the next few day :)

2017-06-20 8:29 GMT-04:00 ggardet <notifications@github.com>:

**Comment by ggardet** [comment]
@marccollin, the problem should be now fixed. Please update your subsurface version once the update will show up in your update software and tell me if it is now ok.

**Comment by marccollin** [comment]
work fine now

another issue i saw but seem to exist since a few version... when i close
subsurface i get a crash.

2017-06-20 9:23 GMT-04:00 ggardet <notifications@github.com>:

**Comment by ggardet** [comment]
@marccollin, since this is another bug, please open a new issue on github, please.

@dirkhh, you can now close this bug as resolved.

**Comment by neolit123** [comment]
@ggardet @marccollin the other bug is covered in https://github.com/Subsurface-divelog/subsurface/issues/510

closing this issue.
