### ISSUE TITLE
Template CSS does not interpret absolute lengths correctly

### ISSUE THREAD

**Issue by mccand** [subsurface/subsurface#464]
While modifying templates, if I go into the "Flowlayout"template, and change this text:
.dataSection {
**width: 100%;**
height: 40%;
margin: 0%;
}

To read:
.dataSection {
**width: 8in;**
height: 40%;
margin: 0%;
}

I expect that the width of the data section will be approximately 8 inches.  Instead, data section shrinks to just under 4 inches.  The same problem occurs when using units of cm as well.  The problem does not seem to be confined to the flowlayout template.

Please see attached images of the output for when the data section width is "100%" vs "8in".

Here is the file where the data section is 100% wide:
![image](https://user-images.githubusercontent.com/1843483/27812608-c28b30f0-600b-11e7-8029-8c09c631262a.png) (Measurements made in Adobe Acrobat Reader DC from a PDF output)

And here is the data section where it is specified to be 8in wide:
![image](https://user-images.githubusercontent.com/1843483/27812642-fcbf1390-600b-11e7-982b-052254e32d6d.png)

This issue was observed in Subsurface 4.6.4 running on Windows 10.

Thanks,

Ben

**Comment by neolit123** [comment]
@mccandhi, i think we had a talk about this on the mailing list, but i can't find the link.

this is an important limitation of the printing engine and it's HTML / JS related.
the only reliable way to use dimensions is to make them relative (i.e. use percentages).
that way when the layout is sent for printing it can match *any* paper size.
