### ISSUE TITLE
password restrictions - correctly communicate

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#481]
Apparently we are silently failing on -mobile, claiming failed connection instead.

**Comment by bluepanter** [comment]
Probably it is the TODO in /core/cloudstorage.cpp on line 74-76 in function CloudStorageAuthenticate::uploadFinished()

>
/* TODO: Emit a signal with the error
		MainWindow::instance()->getNotificationWidget()->showNotification(get_error_string(), KMessageWidget::Error);
		*/

**Comment by Ghalr** [comment]
Is it fixed now ?

**Comment by mturkia** [comment]
> On 28 Jul 2017, at 7.51, Ghalr <notifications@github.com> wrote:
> 
> Is it fixed now ?
> 
The error message is now better, but I did not add anything to instruct about allowed characters.

**Comment by neolit123** [comment]
closing this as `QMLManager::saveCloudCredentials()` already instructs the user about the allowed password character when the user is saving his credentials.
