### ISSUE TITLE
QML style download screen

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#490]
Edited to reflect remaining issue: 

I see some issues in the newly styled download screen:
1) reference to `isBluetooth.leftPadding` ... the isBooltooth checkbox is gone, so logcat warnings.
2) 3 screenshots below. 1st: after download all looks fine. 2nd: `unselect all` button pressed, still looks fine. 3rd: select all: blue background appears (theme is pink). 

items 1) and 2) fixed below. Leaving 3) open.

3) I would like same line height as in divelist (measured on my screen 9mm in divelist, almost 12mm in download list).

**Comment by janmulder** [comment]
Propose to close this issue as nr 1/2 are fixed by referenced commit. And open a new one for 3), which seems beyond my QML skills :-)

**Comment by dirkhh** [comment]
Your commit closed this - let's re-open for the third issue. I agree, the lines are way too tall

**Comment by janmulder** [comment]
fixed in 8c0a1c2e6d357a6
