### ISSUE TITLE
[bug] Mobile app crashes deleting a dive

### ISSUE THREAD

**Issue by Bocio** [subsurface/subsurface#497]
On Subsurface-mobile-4.6.4.443-arm.apk

I tried to remove some dives keeping pressed one dive from the dive list and tapping the bin icon. Each
time Subsurface crashed but the dive was deleted.

Screencast:

https://www.youtube.com/watch?v=NZcpPPI_Pyk

**Comment by dirkhh** [comment]
I am able to recreate, but I haven't figured out how to fix it, yet.

**Comment by Bocio** [comment]
I was not able to reproduce it on the latest apk but now everything is saved on the cloud.
In my test I was deleting dives just after downloading them from the Viper DC. 
I will try to clear everything and start with a new download later.

**Comment by RickMWalsh** [comment]
I can reproduce it, but not consistently and I can't work out why it crashes sometimes but not other times.
