### ISSUE TITLE
[BUG] Crash when exiting Subsurface-mobile

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#510]

**Comment by janmulder** [comment]
Can you provide a screenshot of the confirm box you like to see removed?

**Comment by Ghalr** [comment]
I did not try the latest Android build. I suggest to use double-click than a confirmation box to exit the app. A lot of Android apps do use this behavior.

**Comment by janmulder** [comment]
So what Android build did you try then? I understand what you suggest, but I have problems finding the corresponding code. So a screenshot would help with that.

**Comment by Ghalr** [comment]
Trying the 4.6.4.508 build now

**Comment by Ghalr** [comment]
OK to exit the latest build when you are at home page just 1-click to return button will result an exit. It will be better to double-click to prevent a wrong action.

**Comment by janmulder** [comment]
So, then you better rephrase your request. There is no confirmation box (which I correctly could not find in the code). But you do want a double click end, and not the current single click ... 

I think you are a little confused here. A lot of android apps just close the screen on a single click back, leaving the app in memory which can immediately be opened from your recent apps. 

However, I am seeing a hard exit on 1-click back which is actually a crash. That crash is known for a long time, and is not in Subsurface code (but most likely Qt). Not that this matters to the average user,  but it matters to developers :-)

**Comment by neolit123** [comment]
@janmulder was this resolved?
(you are going to have collaborator access soon - please close, if see fit)

**Comment by neolit123** [comment]
renamed the title

**Comment by janmulder** [comment]
This is most likely: https://bugreports.qt.io/browse/QTBUG-61434 , which is at this moment still in review (there seems a fix ready but not reviewed, or still under discussion).

Highly annoying bug, but we just have to wait for the Qt development process to do its thing. Closing it here.
