### ISSUE TITLE
[Bug] Mobile: Startup splash screens display 2 differents background color (Black then White)

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#513]
from 4.6.4.508 build

**Comment by janmulder** [comment]
Also here. Can you show a screenshot of what you exactly mean?

**Comment by Ghalr** [comment]
I'll try to put a gif let me see if I can do it easily

**Comment by Ghalr** [comment]
Apologize about the video quality my Android is not rooted and bad internet.

videolink deleted.

You got 2 background color (Black and White) maybe the Subsurface icon are not the same size?
Please note that the first time after a fresh install it took a bit of time (5+seconds) not a big deal but faster would be up. The video also show another reported bug about password who is cleared when "Show password" is ON.

https://github.com/Subsurface-divelog/subsurface/issues/512

**Comment by janmulder** [comment]
Ok, clear. You are talking about the startup splash screens. Indeed, 2 different background colors. I know this is already for a very long time, this way. Bu yes, this seems a (imho low priority) bug.

**Comment by Ghalr** [comment]
Startup splash screens indeed.
Editing the title.....

**Comment by Ghalr** [comment]
@janmulder mind if I delete the video link, as you confirmed the issue, I notice there are my personnal email on it... lol

**Comment by janmulder** [comment]
Sure, delete the screencast if you like.

**Comment by neolit123** [comment]
@janmulder do you think this is an easy fix?

**Comment by janmulder** [comment]
New screencast to show the issue. Gunzip first :-) Made with Travis build apk 4.7.4.43

[black-white.mp4.gz](https://github.com/Subsurface-divelog/subsurface/files/1481496/black-white.mp4.gz)
