### ISSUE TITLE
[BUG] parse-xml.c - Divesoft Button Press events are creating blank events on the profile

### ISSUE THREAD

**Issue by zamedic** [subsurface/subsurface#543]
[00000009.zip](https://github.com/Subsurface-divelog/subsurface/files/1224967/00000009.zip)
Hi Guys

parse-xml.c 
`
	case 18:
				// key pressed - probably not
				// interesting to view on profile
				break;
`

above statement is creating blank events, which can fill up the graph. Can we add a check that event type 18 should not create an event?

**Comment by zamedic** [comment]
Apologies - I see you do infact want to group them... so the above event should go into the same block. maybe we can only start the event if ptr[4] != 18?

**Comment by zamedic** [comment]
I can confirm the problem is resolved in the latest 4.6.4-781 build.

**Comment by dirkhh** [comment]
Thanks
