### ISSUE TITLE
[idea] Mobile - Location Selection

### ISSUE THREAD

**Issue by rainman104** [subsurface/subsurface#546]
I'd love to see the location on the mobile app allow you to reuse your saved locations like the desktop app does.   Currently the process for me when downloading dives from the mobile app is to sync to the cloud and modify on the desktop later.   Not the most inconvenient but would definitely add polish to the app.

**Comment by neolit123** [comment]
@janmulder @dirkhh this seems dive-site related and might not be that easy to do? what do you guys think?

**Comment by dirkhh** [comment]
This is mainly a UI issue on mobile. It's not that this would be all that hard - it's a matter of time and priorities
