### ISSUE TITLE
Stichwörter werden nicht übernommen und aktiv gelöscht beim Feldwechsel

### ISSUE THREAD

**Issue by Natas-Lived** [subsurface/subsurface#550]
english version
Add a new dive manually. Press STRG and + and fill in all data. The Field "Stichworte" is filled also (this is the field below the stars for evaluation and visibility)
By pressing tabulator key move cursor / focus to the field "notes" and save the dive. (by mouse - "apply changes" button)
Now the annotations in field "Stichworte" are lost.
Same is valid if one does _not_ save but switches to the tab page "equipment", adding data. Switch back to the page "notes" and the filed "Stichworte" is empty again.

If one adds data to field "Stichworte" once more and hits "apply changes", data will be stored and added to dive log. (Valid for both variants as explained before).

Expected
Once data is filled in, this should not be deleted just by hopping to another field or tab-page.
It should not be necessary to enter data twice.

German
Ein neuer Tauchgang wird manuell angelegt: STRG++ drücken und alle Daten eingeben. Im Feld "Stichwörter" werden ebenfalls Daten eingegeben. Mit Tab in das Notizenfeld springen und Tauchgang speichern (mit der Maus, "Änderungen anwenden" Knopf).
Jetzt sieht man, daß die Daten im Feld "Stichwörter" verschwunden sind.
Gleiches gilt auch, wenn man statt zu Speichern ("Änderungen anwenden") auf die Tabulatorseite "Ausrüstung" wechselt und dort Daten eingibt. Klickt man wieder auf die Seite "Notizen", ist das zuvor gefüllte Feld "Stichwörter" wieder leer.
Trägt man (in beiden Varianten) nun abermals Daten in das Feld "Stichwörter" ein und speichert, bleiben die Daten erhalten und werden in das Tauch-Log eingetragen.

Erwartet
Trägt man Daten in ein Feld ein, so sind diese nicht zu löschen, wenn man in andere Felder springt oder die Tab-Seite wechselt.
Eine doppelte Eintragung sollte nicht notwendig sein.

**Comment by dirkhh** [comment]
also @tcanabrava

**Comment by Natas-Lived** [comment]
english translation provided.

**Comment by Natas-Lived** [comment]
english translation provided.

**Comment by dirkhh** [comment]
Thanks @Natas-Lived 
@tcanabrava can you comment if this is something you could look into?

**Comment by bstoeger** [comment]
I tried and tried, but was unable to reproduce this (current master, Kubuntu, Qt 5.9.1).

Could you perhaps provide a screen capture in case that I'm not understanding the description correctly?

**Comment by Natas-Lived** [comment]
Attached a png with the forms prior and after pressing "save" i.e. with data and and with lost data. 




![subsurface_stichworte](https://user-images.githubusercontent.com/30120716/34440771-c9f8f334-ecb7-11e7-8c90-57ae8daf7d5a.png)

**Comment by mturkia** [comment]
What version of Subsurface? Is it still an issue with 4.7.6 that was released yesterday?

**Comment by bstoeger** [comment]
Since we don't even have the "save changes" dialog anymore, we probably should close this.

**Comment by dirkhh** [comment]
agreed
