### ISSUE TITLE
Filter wird gelöscht bei Anpassung der Werte im Filterfeld

### ISSUE THREAD

**Issue by Natas-Lived** [subsurface/subsurface#551]
Die Filteransicht ist aufgerufen (STRG+F)
Der Filter ist auf "Anzug".
Es wird nach dem Eintrag "Nass" gefiltert, einige Daten werden angezeigt.
Der erste Datensatz wird bearbeitet und Naß eingetragen. Klick auf "Änderungen anwenden".
Der Filter wird entfernt und es werden wieder alle Daten (Tauchgänge) angezeigt.

erwartet:
Liste der Tauchgänge mit "Nass" wird weiterhin angezeigt, jedoch mit einem Datensatz weniger.
in der Übersicht der möglichen Filterkriterien wird neben Nass jetzt auch Naß angezeigt, mit einem Datensatz als Anzahl.

**Comment by dirkhh** [comment]
This is something that  @tcanabrava would be the best person to work on.
Tomaz, do you understand the German? Want translation help?

**Comment by dirkhh** [comment]
Quick translation:
Open the filter view (Ctrl-F)
Set the filter for a "suit"
Filter for the first entry under suit (in the German example "Nass" - using sample data, try "wet, 3mm")
Edit the first dive that is selected and shown, change the suit (let's say to "wet, 2mm") and accept the change
Result: filter is removed and all dives are shown
Expected result: still only those dives with suit "wet, 3mm" are shown, just one fewer dive, and the list of options in the filter panel should now also offer "wet, 2mm"

**Comment by bstoeger** [comment]
Fixed by #857 and #859? Please check.
