### ISSUE TITLE
falsche Daten bei manuellen Eintragungen

### ISSUE THREAD

**Issue by Natas-Lived** [subsurface/subsurface#554]
Ein neuer Tauchgang wird manuell eingetragen, die Dauer kann man ebenfalls angeben.

Nach Speichern wird in der Liste der Tauchgänge ein Wert um einen Zähler höher angezeigt. Aus 37 Minuten in der Eingabemaske wird 38 Minuten in der Tabelle.

Dabei scheint es einen Einfluß zu haben, ob man mit Cloud Speicher arbeitet.

Die Eintragungen wurden vorgenommen und auf "im Cloud Speicher sichern" gewählt, weitere Eintragungen vorgenommen, auf Speichern geklickt - damit ist nur im Cloud Speicher eine Datenablage erfolgt, lokal ist nichts gespeichert.

Schließt man und öffnet Subsurface erneut, verbindet mit dem Cloud Speicher, speichert ab als lokale XML Datei, sind einige der neue, nicht alle, Daten verschoben. Ich habe vier Eintragungen vorgenommen, bei drei Datensätzen verbleibt der Eintrag identisch, bei einem Eintrag wird aus 41 42.

**Comment by dirkhh** [comment]
Welche Subsurface Version? Welches Betriebssystem?

**Comment by Natas-Lived** [comment]
Version 4.6.4, Linux, Suse 42.1.20170515
Bildschirmabbild anbei
![zeit_in_tabelle_vs_formular](https://user-images.githubusercontent.com/30120716/30023920-d5a7b2e8-9171-11e7-9585-9b5980aeb4a6.png)

**Comment by Natas-Lived** [comment]
Version 4.6.4
BS: Linux Suse 42.1
Bildschimabbild anbei
![zeit_in_tabelle_vs_formular](https://user-images.githubusercontent.com/30120716/30024087-84f103a8-9172-11e7-9141-570b538536a6.png)

**Comment by dirkhh** [comment]
Hmm, ok, das sieht aus, als wuerden wir unterschiedlich runden. Kannst Du den einen Tauchgang, den Du da zeigst, als XML exportieren und hier anhaengen, damit wir das einfach reproduzieren koennen?

**Comment by Natas-Lived** [comment]
Datei angehängt, Endung .txt löschen, ohne unterband GitHub das Hochladen.
[554_falsche_Daten_bei_manuellen_Eintragungen_Export_TG27.ssrf.txt](https://github.com/Subsurface-divelog/subsurface/files/1284491/554_falsche_Daten_bei_manuellen_Eintragungen_Export_TG27.ssrf.txt)
Es ist ein manuell eingetragener Tauchgang:
<dive number='27' (...) duration='37:06 min'>
Woher die sechs Sekunden kommen, kann ich nicht erklären, eingegeben hab ich sie nicht.
Die Werte in Sekunden sind auch bei anderen manuell eingetragenen Datensätzen enthalten.

**Comment by bstoeger** [comment]
I think this bug is fixed:

1) After ac1ec486ae0cd0295166bb1dc0d5b82dc237a5b1, no 6 second are added to the dive duration
2) After eb38a641490752578e3dddc7b7959cfd52e0be74, the dive duration is not rounded if there are seconds.

The duration in the dive-list also seems to work: X:YY is rounded to X for Y < 30 and to X+1 for Y >= 30.

Unfortunately, I don't see how we can fix those erroneous +6s dives?

**Comment by neolit123** [comment]
> I think this bug is fixed:

ok, lets close this and open new issues if needed.
