### ISSUE TITLE
Importing from Shearwater Desktop always chooses CCR instead of OC

### ISSUE THREAD

**Issue by SeppoTakalo** [subsurface/subsurface#569]
When importing from Shearwater Desktop the Subsurface seems to assume dive mode `CCR` instead of `OC`
![nayttokuva 2017-09-12 kello 21 10 02](https://user-images.githubusercontent.com/3104794/30341503-e763739e-97fe-11e7-8489-06d422b4a2df.png)
The Shearwater seems to be showing `Dive type: OC`
![nayttokuva 2017-09-12 kello 21 14 49](https://user-images.githubusercontent.com/3104794/30341669-8d1b6d1e-97ff-11e7-9290-3ca3d5149f8d.png)

Please see the attached dive log file exported from Shearwater.
[new_dives.db.zip](https://github.com/Subsurface-divelog/subsurface/files/1296981/new_dives.db.zip)

**Comment by mturkia** [comment]
I wish I had a proper CCR dive log to see what is different in that when compared to OC. The current detection for CCR mode apparently is not the way to implement this. Is there any way to set CCR mode in Shearwater Desktop or is it displaying the mode the DC was during the dive?

**Comment by SeppoTakalo** [comment]
I believe it is showing the value that the computer was set during the dive.
I have not set any mode within the desktop application itself.
