### ISSUE TITLE
`atof()` used for converting values from databases without checking locales.

### ISSUE THREAD

**Issue by SeppoTakalo** [subsurface/subsurface#574]
It seems that `atof()` function is used to convert floating point values coming from SQLite database.
This is a problematic because `atof()` cares about users current locale settings but SQLite does not seem to.

This causes problems where decimal separator is `,` instead of `.` when SQLite seems to be always using `.`
End result would be that all numbers converted have only their integer part.

```
~/src/subsurface/subsurface $ ag "atof\(" -l --stats
core/parse-xml.c
26 matches
1 files contained matches
```

`atof_l()` could have been used with `NULL` locale, but its not portable. I don't know any portable alternatives.

**Comment by SeppoTakalo** [comment]
I wonder if it too much wrong to call `setlocale(LC_NUMERIC, "C")` before starting the conversion.

**Comment by mturkia** [comment]
Smarttrak import does the following:

        // Set an european style locale to work date/time conversion
        setlocale(LC_TIME, "POSIX");

On the other hand, we have core/strtod.c due to locale reasons.
