### ISSUE TITLE
Merging dives does not correctly combine cylinder start/end pressure

### ISSUE THREAD

**Issue by simenon** [subsurface/subsurface#577]
I combined 2 dives that i extracted from my EON Steel. However the combined dives only contained the start/end pressure of the first dive, which results in a wrong SAC and other statistics.

**Comment by neolit123** [comment]
@simenon hello, do you happen to have the 2 dives before combining them?
can you upload them somewhere for the developer team to take a look?

**Comment by simenon** [comment]
i exported the 2 dives from subsurface 

[2 dives unmerged.zip](https://github.com/Subsurface-divelog/subsurface/files/1327475/2.dives.unmerged.zip)

**Comment by neolit123** [comment]
thanks for the dives @simenon
