### ISSUE TITLE
[BUG] googlemaps: don't crash when the plugin isn't loaded

### ISSUE THREAD

**Issue by neolit123** [subsurface/subsurface#596]
https://github.com/Subsurface-divelog/subsurface/issues/589

If the plugin isn't loaded due to a missing plugin binary or qt-location modules, attempt to not crash when calling QML code from C++.

Also, either show an error message in the map-widget (1) or hide the widget completely (2).
My vote is for (1).

@dirkhh

**Comment by dirkhh** [comment]
(1) is of course better - as long as that doesn't cause odd memory corruptions or whatever else it is that causes these hangs/crashes
