### ISSUE TITLE
Investigate why MentionBot isn't working

### ISSUE THREAD

**Issue by neolit123** [subsurface/subsurface#597]
MentionBot doesn't seem to be working. Investigate why.

**Comment by neolit123** [comment]
@dirkhh seems like mentionbot is broken for others too and isn't maintained: https://github.com/facebook/mention-bot/issues/230

i've also just tested it in another repository.
i suggest we leave it as is until they fix it and unless we find a better alternative. i'm looking for alternatives.

**Comment by dirkhh** [comment]
That seems reasonable. Thanks for looking into this.

**Comment by neolit123** [comment]
closing for this for now.
