### ISSUE TITLE
show again the full list of tags

### ISSUE THREAD

**Issue by antiker1** [subsurface/subsurface#605]
Hi.

There's the filed "Tags", which auto-completes to some apparently hard-coded standard fields and to whatever one has manually used within a log.

In earlier versions, when one wrote e.g. "salt,shore," then after a new "," a dropdown list with *all* the known tags was presented.
This seems to be no longer the case and at least one letter is required for such list e.g. "s" will give salt, short and student.

I think the previous behaviour was much nicer, as it gave me the a quick overview of all the tags in use.
So one would not accidentally forget a rarely-used tag like e.g. altitude when one adds such a dive, as one could quickly go through the list.

It would be even nicer if the list was sorted first by whether a tag has already been used or not, and within those two groups alphabetically.

Thanks for your consideration

**Comment by AFulgens** [comment]
Not only that, but a "tag editor" feature would be nice: a simple CRUD for tags, and _maybe_ bulk-applying tags onto multiple dives.

**Comment by mturkia** [comment]
Bulk applying tags is supported. Just add the tags you wish to one dive, ctrl-c to copy them (you get a dialog to ask what info to copy), select multiple dives and hit ctrl-v to paste the data to all selected dives.

**Comment by AFulgens** [comment]
@mturkia my bad, I'm still a new user to Subsurface :) But am I correct, that a tag-editor does not exist currently? (I am a bit confused, because I added a custom tag to some of my dives, then deleted it from all dives, and the dropdown still shows this tag)

**Comment by dirkhh** [comment]
>@mturkia my bad, I'm still a new user to Subsurface :) But am I
>correct, that a tag-editor does not exist currently? (I am a bit
>confused, because I added a custom tag to some of my dives, then
>deleted it from all dives, and the dropdown still shows this tag)

Filter for the tag. I'm sure it's still somewhere.
Actually, let's be more precise. It was there when you opened the file.
Once you quit Subsurface and start again, only default tags and those included in your dive list will be shown.

**Comment by antiker1** [comment]
Thanks for fixing this :-)
