### ISSUE TITLE
Subsurface-mobile 2: adding multiple buddies fails

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#608]
From the user forum:
> if I enter multiple buddys (split by coma) (,) on my Android Mobile beta
> 2.0 and save it it shows up as "multiple buddys" if I open the dive on my
> Windows app also "multiple buddys" appears but I can't see who they are.

**Comment by jbygdell** [comment]
Something is broken here, "multiple buddies" should only be visible on the edit page, not passed on when saving. The current back-end can not handle entry of multiple buddies because the autocomplete only works for one entry.
I'll look into this when I redo the dive edit page.
