### ISSUE TITLE
Facebook upload not uploading as expected

### ISSUE THREAD

**Issue by fedMasias** [subsurface/subsurface#612]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

1) When passing a new Facebook upload, Subsurface prompts for an album name, and passes that to the Facebook API. However, once uploaded, Facebook groups all uploads, regardless of what the user indicates, into an album called "Subsurface Photos"
2) These uploads are supposed to be set to Private (or, "SELF", in FB API speech) but are shared by default with "Friends" -- Or at least, that's how I interpret line 124 in facebookconnectwidget.cpp
### Operating system:

macOS 10.11.6 on a late 2012 rMBP. I am unable to test other OSes at this time

### Subsurface version:

4.64.839, built by dirk (I believe this is a test build)

I believe it's using Facebook Graph 2.10, the latest FB API

### Steps to reproduce:

1) Select dive to export
2) Enter Album name
3) Upload

### Current behavior:

The dives are uploaded to "Subsurface Photos", and set to "Friends"
### Expected behavior:

The dives should be uploaded to the user defined album, and initially set to private (or "SELF")
### Mentions:

@tcanabrava -- I'm told you may be the one to ask about the API stuff?

**Comment by ggardet** [comment]
The problem is that we are lacking 'user_photos' Facebook permission to create an album, but we are able to upload the image to Facebook, but not in a specific album. So, the image will be published on your timeline (friends accessible) and Facebook will name the album 'Subsurface Photos'.

**Comment by ggardet** [comment]
@tcanabrava or @dirkhh (not sure who submitted Subsurface App to Facebook), could you add missing permissions in the Facebook admin page, please?

**Comment by dirkhh** [comment]
I’ll look into that as well - this was submitted by me.

**Comment by neolit123** [comment]
we are  removing the FB feature:
https://github.com/Subsurface-divelog/subsurface/pull/1958
