### ISSUE TITLE
Deco ceiling calculation for EAN32 dive with 3m steps on/off - very strange results

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#630]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Strange effect once again with deco ceiling calculation. This time visible outside the planner.
Example dive attached. If you for this example dive with EAN32 as bottom gas switch on/off 3m steps for deco ceiling calculation the overall ceiling result changes. This should not be the case because the 3m steps should only round up every ceiling to next 3m stop.
This issue is gone as soon as you change the bottom gas for the dive to s.th. other than EAN31-32.

Maybe linked to #601 

### Operating system:

Windows 10

### Subsurface version:

Latest master

### Additional information:

[EAN32_dive_deco_ceiling.zip](https://github.com/Subsurface-divelog/subsurface/files/1353675/EAN32_dive_deco_ceiling.zip)

**Comment by atdotde** [comment]
There are other things clearly wrong with this dive: I see spikes and what is more, the lowest ceiling does not appear at the end of the bottom time.

**Comment by sfuchs79** [comment]
Yes, exactly. Very strange. Did you try to change the bottom gas to 30% and 33%? Even no need to start the planner for this, simply change in the dive view.
Then the strange issue is gone.
Does Subsurface hate Nitrox 32?

**Comment by atdotde** [comment]
My suspicion is that this comes from the fact, that for VPMB the deepest ceiling matters and for that we probably also use the rounded value (and shouldn't). But so far, I have not checkt the source for that.

**Comment by sfuchs79** [comment]
Ok, with the change the effect from switching on/off the 3m steps is gone.
But still if you play with O2 values between 29% and 35% for the example dive you see that there is s.th. clearly wrong.
For O2 31% you have deeper/longer ceiling compared to result for O2 30%.

**Comment by atdotde** [comment]
@sfuchs79 I can confirm this. Here is a file that has both variants in it. One would naively expect the ceiling for EAN31 to be shallower than EAN30 but with VPMB+2 that seems not to be the case. @RickMWalsh any idea what could be the origin? 

[EAN2.ssrf](https://github.com/Subsurface-divelog/subsurface/files/1354847/EAN2.log)

I am, though, not sure if this is really a Subsurface bug or just another oddity of VPM-B. Have to investigate this further how the change comes about (guess: first ceiling is involved once more).

**Comment by sfuchs79** [comment]
If you plan the very same dive in the planner and increment O2 from 28% to 36% you can see that the planner is doing everything as expected. The deco/runtime for the dive is decreasing for every O2 percentage you add. Ok, sometimes adding 1% O2 doesn't change by a full minute but at least it looks as it is continuous.

So it's for me as with most of the issues in the deco ceiling display from the last weeks:
The planner code responsible for the waypoints and the written diveplan does everything correctly but the deco ceiling calculation in profile.c is clearly buggy!

@neolit123 Can you please reopen this issue?
