### ISSUE TITLE
In planner minimum switch time applied twice after gas change

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#661]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Another small bug in the planner:
In some specific dive setups the "minumum gas switch time" is applied twice after a gas switch.
The setup is also described in the screenshot but here are the important factors:
- Two deco gases (e.g. EAN50%, Oxy), both enabled
- Option "Only switch at required stops" is set
- Minimum switch time set to >0, e.g. 5min
- Duration of dive and deco and ascend rate are set in a way that the lowest stop is 6m
- This means with the options set the EAN50% is not used for deco
--> Due to this setup for the gas switch to Oxy the minimum switch time is applied twice

![grafik](https://user-images.githubusercontent.com/25316050/31379527-c419a99c-adae-11e7-872e-091ca6a3619b.png)

This for sure comes from somewhere here:
https://github.com/Subsurface-divelog/subsurface/blob/master/core/planner.c#L972
One would need to check if we need to skip one cylinder completely (the EAN50%).
Unfortunately I was not able to fix this quickly :-(

### Subsurface version:

Current master and 4.6.4

### Mentions:

@atdotde @RickMWalsh

**Comment by atdotde** [comment]
@sfuchs79 could you please check if my patch above addresses this problem?

**Comment by sfuchs79** [comment]
Nope. Crashes when I try to test the specific test case in:
planner.c @ 980
This has also been the difficulty for me to understand where we need to skip the unnecessary gaschanges. Not at this point where you put it, I guess. But I also don't know better yet.

**Comment by atdotde** [comment]
For me, this seems to work. Could you please confirm @sfuchs79 ?

**Comment by sfuchs79** [comment]
Unfortunately no. Now the EAN50 is accidentally used for the 6m stop in my test case instead of the available Oxy.
May I propose s.th.: Let's try to fix this and the O2 breaks thing post 4.7. Both items seem to be somehow linked and pretty difficult with all the effects from all the possible options in the planner.

**Comment by sfuchs79** [comment]
@atdotde 
I have the feeling that this issue either disappeared due to other improvements you did (o2 breaks?) or you fixed it by intention and I didn't recognize it.
Can you also confirm that the issue is gone?

**Comment by sfuchs79** [comment]
Ah, no, I tricked myself. It didn't really disappear. I don't see it any more for my old example dive because we now have this special treatment for 100% oxy. If I change oxy to 99% I still see the issue.
