### ISSUE TITLE
GPS fixes: apply the one that is the most close to the start of the dive

### ISSUE THREAD

**Issue by PeterZaal** [subsurface/subsurface#666]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
I just recently started using the GPS service on Subsurface-mobile (v2) and applying the GPS fixes after the dives. I noticed that sometimes the GPS position that was used was not the one most close to the starting of the dive, but instead a GPX fix was taken that was way off the exact dive location.
After reading the manual I saw this: "Subsurface-mobile applies the first GPS position that falls within the dive period of each dive". I had the GPS settings to default (distance 1000m and time 10 minutes) and what happend on my dives is that after we jumped off the boat and started our dive the boat drove away to another position. Than a GPX fix was registered and that was used for the starting point of the dive, which was way off.
Ofcourse you can use the settings to have it taken more GPX fixes, but I feel it would be more precise to apply the GPX fix that is the closest in time to the start of the dive, even if this is a fix before that actual start of the dive.
I think there are 2 scenarios:
1. the boat stays at the dive spot where you enter the water. In this case even if a fix  is used and applied which is a little before the dive it would still be the correct location, because it always takes some time to set up and enter the water. If a GPS fix would be registered in this time and later applied, this is the correct and same location where you start the dive.
2. the boat drives away after the divers are down. In this case the fix that is the most close in time to the start of the dive is the best.

So the change request is to use the GPS fix that is the most close in time to the start of the dive instead of the first one after the start of the dive. Any comments?

**Comment by salvadorcunat** [comment]
Agree with you Peter. Noticed this issue last summer while drift diving on strong current.
Posting a PR for this.
Regards.
