### ISSUE TITLE
mobile: no cloud creation fails

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#667]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Open a fresh installed mobile app session. It presents the login screen. Hit no-cloud. Nothing seems to happen, and things go downhill from there

### Operating system:
 Android
 6.01 and 7.1.2

### Subsurface version:
 from play store -966
  unknown, probably not, new credentials related.
 official beta

### Current behavior:
no response to no-cloud button

### Expected behavior:
creation of no-cloud repo on device, and presentation of empty divelist

**Comment by satoschu** [comment]
It is not only a fresh install, after update to the latest release I can' the switch to the non cloud mode.
