### ISSUE TITLE
Filter list not updated when dive site name is changed via "edit dive site" dialog

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#675]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Please assume a long logfile with many dives. I activate the dive filter. Now I for example identify some entries in the filter lists for buddy names, dive site names, tags, dive suit, whatever which I want to correct because there is a typo or similar.
If I do this directly in the main tab "Notes" and apply the change(s), immediately the filter lists are updated correctly. If e.g. an entry is removed because a typo was corrected the wrong entry disappears.
Now to the bug:
If I do change the dive site name of a dive not in the main tab but by clicking the "edit dive site" button and then edit the name there, the change is not reflected in the filter lists.

### Operating system:

Windows 10

### Subsurface version:

4.6.4.1013 which is latest master plus some WIP items.

### Current behavior:

![grafik](https://user-images.githubusercontent.com/25316050/31662490-d4c19972-b33e-11e7-90a3-1c24775206aa.png)

### Expected behavior:

Update filter lists also after a change of the dive site name in the "edit dive site" dialog is done and applied.

**Comment by dirkhh** [comment]
This is the third subtle little filter bug. @tcanabrava promised to look at the other two, let's assign this one to him as well :-)
@tcanabrava - this is fine to do after 4.7 - I'd love to see the crash (the one we discussed an hour ago) to be addressed if we can... the others we can do in 4.7.x

**Comment by bstoeger** [comment]
@sfuchs79: Could you perhaps test PR #857, to see if it behaves like you would expect? Thank you.

**Comment by sfuchs79** [comment]
@bstoeger 
This is the edit dive site dialog i'm talking about:
![grafik](https://user-images.githubusercontent.com/25316050/33235281-60a4d3e0-d235-11e7-8124-91176ab3b1e6.png)

**Comment by bstoeger** [comment]
Ok - I see what you mean. Please try #863, this should change the behavior.

Unfortunately, with the changes in #857, this means that the old selection in the dive list is lost. :( I'm also not sure how to fix it - somehow the filter would have to know which entry was renamed...
