### ISSUE TITLE
Make mention bot not suggest author of PR as reviewer

### ISSUE THREAD

**Issue by atdotde** [subsurface/subsurface#687]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

It makes little sense to review ones own changes.

### Expected behavior:

Exclude the author of PR from suggested reviewers.

**Comment by dirkhh** [comment]
I think this is a change in mention-bot, not in Subsurface...

**Comment by atdotde** [comment]
Actually, my understanding is that this is a config option, so it should be set in subsurface's config file for mention bot.

**Comment by neolit123** [comment]
@atdotde hmm, is this possible?
i didn't see a way to exclude the mention if the PR is from the same user.

**Comment by neolit123** [comment]
closing this as i think it's not possible to configure it as requested.
also, the mention bot is not even working most of the time...
