### ISSUE TITLE
Subsurface 4.7.1 crashes on start

### ISSUE THREAD

**Issue by SadRiddler** [subsurface/subsurface#752]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Subsurface 4.7.1 crashes upon launch. No splash screen shown. TaskManager briefly shows the subsurface.exe process before Windows Error Reporting kicks in. Tried different compatibility mode settings (Windows 7 and Windows 8) without success. Run the program as an administrator does not change the behavior. Deleting HKCU\Software\Subsurface and 
 C:\Users%UserName%\AppData\Local\Subsurface did not change the behavior

### Operating system:

Issue occurs on Windows 10 1709 64 bits French
Issue does not occurs on Windows 10 1709 32 bits French

### Subsurface version:

Issue occurs with Subsurface 4.7.1 downloaded from https://subsurface-divelog.org/
Issue never occured with Subsurface 4.6.4 downloaded from https://subsurface-divelog.org/

### Steps to reproduce:

1) Double-click on the Subsurface icon on the desktop or manually launch "C:\Program Files (x86)\Subsurface\subsurface.exe"

### Current behavior:

No splash screen shown. TaskManager briefly shows the subsurface.exe process before Windows Error Reporting kicks in.

### Expected behavior:

Splash screen shown and program starting normally

### Additional information:

Things tested that did not solved the problem:
- Compatibility mode settings (Windows 7 and Windows 8)
- Run the program as an administrator
- Deleting HKCU\Software\Subsurface
- Deleting C:\Users\%UserName%\AppData\Local\Subsurface
- Copying C:\Program Files (x86)\Subsurface to C:\Program Files\Subsurface

**Comment by dirkhh** [comment]
This is a known bug in 4.7.1.
Workaround: run in English (or another language, not in French).
Subsurface 4.7.2 fixes this problem and will be released in the next couple of days.
A current test build that should be very close to the final 4.7.2 is available - it can be used in French as well:
http://subsurface-divelog.org/downloads/test/subsurface-4.7.1-69-g945a0a87482d.exe
(please note that we frequently update the test builds - if the link above fails, look at http://subsurface-divelog.org/downloads/test for a similarly named Windows installer).
