### ISSUE TITLE
Cloud sync no more working

### ISSUE THREAD

**Issue by francobam** [subsurface/subsurface#757]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Cloud synchro not working properly

### Operating system:

Win 10/64 German

Android Mobile 6.01 Samsung J5

### Subsurface version:

4.7.1

![2017-11-01 19_43_30-program manager](https://user-images.githubusercontent.com/33285545/32275625-8598edb2-bf3e-11e7-98ca-bbb9df7aef29.png)

### Steps to reproduce:

Cloud Speicher öffnen
Ergebnis: Keine Synchronisation
Mobile Version 69 logged dives
Desktop Version 67 (last 2 not synchronized)

**Comment by dirkhh** [comment]
We just released 4.7.2 which addresses a couple of possible problems. Frankly, I'm not sure it will address your issue, but it seems reasonable to ask you to try. :-)

**Comment by francobam** [comment]
Thank you Dirk,
I will try next days!
Br Frank


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Dirk Hohndel <notifications@github.com> Date: 01/11/2017  21:30  (GMT+07:00) To: Subsurface-divelog/subsurface <subsurface@noreply.github.com> Cc: francobam <francobam@web.de>, Author <author@noreply.github.com> Subject: Re: [Subsurface-divelog/subsurface] Cloud sync no more working (#757) 
We just released 4.7.2 which addresses a couple of possible problems. Frankly, I'm not sure it will address your issue, but it seems reasonable to ask you to try. :-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Subsurface-divelog/subsurface","title":"Subsurface-divelog/subsurface","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Subsurface-divelog/subsurface"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dirkhh in #757: We just released 4.7.2 which addresses a couple of possible problems. Frankly, I'm not sure it will address your issue, but it seems reasonable to ask you to try. :-)"}],"action":{"name":"View Issue","url":"https://github.com/Subsurface-divelog/subsurface/issues/757#issuecomment-341122543"}}}

**Comment by janmulder** [comment]
Doing the following workflow (daily, as I am on a dive trip). Sync the OSTC3 to mobile after the dive, fill in some data, back at a wifi point, sync to cloud (manual), back on the desktop, load cloud (from online). All working perfectly. Pushing edits back to cloud from desktop, re-syncing mobile, also working as it should.

All with relatively new (but not current master) 4.7.4 on both desktop and mobile.

Propose: close this issue.
