### ISSUE TITLE
Convert README to README.md and add Travis CI build status badge

### ISSUE THREAD

**Issue by probonopd** [subsurface/subsurface#765]
If it is OK to convert `README` to `README.md` we could add a badge that shows the current build status like this:

[![Build Status](https://travis-ci.org/Subsurface-divelog/subsurface.svg?branch=master)](https://travis-ci.org/Subsurface-divelog/subsurface)

**Comment by dirkhh** [comment]
Sure, that would be fine

**Comment by probonopd** [comment]
Will send a PR
