### ISSUE TITLE
Travis-created AppImage doesn't successfully log in to Facebook

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#783]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The login page is shown (so this isn't the OpenSSL issue). But then once you enter your credentials and log in, you don't actually get logged in, you're just dumped back at the login screen.
The locally-built version on Linux works just fine, so this is an oddity with the AppImage that needs debugging.

### Operating system:

Tested on Arch Linux and Ubuntu 17.04.

### Subsurface version:

Current master with Travis-built 'official' AppImage
### Mentions:

@tcanabrava

**Comment by hhassey** [comment]
Confirm same behavior in Debian Stretch

**Comment by neolit123** [comment]
we are  removing the FB feature:
https://github.com/Subsurface-divelog/subsurface/pull/1958
