### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#784]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Open help-check for updates. The new continuous tag confuses things here as well.

The server returned the following information:
["You are running a development version; latest version is continuous.0."]

### Mentions:

@dirkhh

**Comment by dirkhh** [comment]
Yes, I'm aware of that, I just need to figure out how to work around it :-/

**Comment by dirkhh** [comment]
Oh, that was much easier than I thought.
Fixed.
