### ISSUE TITLE
Dive locations with no linked dive appear on the map

### ISSUE THREAD

**Issue by DennisArreborg** [subsurface/subsurface#786]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Upon import of GPX fixes to several dives at the same dive spot I have ended up with a number of dive location markers, that are not linked to any dive.

Dispite having slightly different gpx fixes, the dives were at the same spot. So after naming the first dive location accordingly, I applied that dive location to the remaning dives. This has left several unused dive markers on the map
![image](https://user-images.githubusercontent.com/6437980/32511205-5b4cb106-c3f3-11e7-9718-415ecaf65fd3.png)

Whenever I select one of the unused dive spots, the notes tab changes to include the depth and duration infomation, but the selected dive is the same as before.

The extra dive spots are synced to the cloud and appears on other windows machines.

### Operating system:

GPS fixes imported from Android app 2.0(4.6.4.966), Android 7.0 on Samsung A3

PC is Windows 10

### Subsurface version:

Subsurface 4.7.2 official build.

### Current behavior:

Dive locations that are not linked to any dive appear on the map.

### Expected behavior:

Only dive locations linked to a dive should appear on map.

### Additional information:

Issue reported initially reported in user forum
https://subsurface-divelog.org/user-forum/?place=topic%2Fsubsurface-divelog%2FaR_169Me5kc%2Fdiscussion

### Mentions:

@neolit123

**Comment by DennisArreborg** [comment]
[logbook.zip](https://github.com/Subsurface-divelog/subsurface/files/1451463/logbook.zip)

My logbook is attached... 
There are multiple "unused" divespots around the location of e.g. dives #393-397

**Comment by DennisArreborg** [comment]
oops

**Comment by neolit123** [comment]
@DennisArreborg 

thanks, we seem to have a backend "breakage" of sorts,
i'm going to ping the developer mailing list as i need some decision making from there.

**Comment by neolit123** [comment]
@DennisArreborg

we've decided to discard these unused dive-sites at the saving stage.
so, once you save the log book and then then reload it, these unused flags should be gone.

the fix should be available in the next windows test build.

**Comment by DennisArreborg** [comment]
That's cool!

Do I need to build it myelf? Is the test build available to download somewhere?
I do not have any linux machine running at the moment, so otherwise I will just wait for the next official release

I appreciate your efforts!

**Comment by neolit123** [comment]
i will just send you a message when we have a new Windows test build.
thanks.

**Comment by dirkhh** [comment]
A new test build that includes this feature is available here:

http://subsurface-divelog.org/downloads/test/subsurface-4.7.2-52-g13b909cf82ef.exe

It would be nice if you could test it and let us know if this fixes the issue for you. And before I forget - the latest test build is always available in that directory: http://subsurface-divelog.org/downloads/test so if we made a newer build available, the link above might fail, simply go to the second link and pick the Windows installer

**Comment by DennisArreborg** [comment]
Succes. After I did File>Open Cloud Storage the unliked sites disappeared.


2017-11-08 16:36 GMT+01:00 Dirk Hohndel <notifications@github.com>:
