### ISSUE TITLE
Get rid of the stupid MentionBot

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#846]
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Simple, the MentionBot does not work. It almost never fires, and when it fires it produces BS (like Robert has to review his own stuff). IMHO: just disable all this. While the idea is good, it does not work.

### Mentions:
euh .... @neolit123 ?

**Comment by neolit123** [comment]
talk to @dirkhh

**Comment by dirkhh** [comment]
I agree with @janmulder on both counts. It's a great idea. But it just doesn't seem to work well enough to be worth it. I'll disable it.

**Comment by dirkhh** [comment]
Hook is disabled, see https://github.com/Subsurface-divelog/subsurface/commit/32a7cde180a342aef13b1ffcbe53a088ab4dc51c
