### ISSUE TITLE
Planner crash on recreational mode

### ISSUE THREAD

**Issue by DennisArreborg** [subsurface/subsurface#849]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
When changing from Bühlman deco to recreational mode subsurface goes Not Responding

### Operating system:
WIN10

### Subsurface version:
subsurface 4.7.4

### Steps to reproduce:
Open planner
default dive is 15 m 20 min. Change to 30 m 20 min.
If in recreational mode, program stops. If not in recreational mode, program will stop upon change to recreational mode
![23-11-2017 10-06-47](https://user-images.githubusercontent.com/6437980/33165162-144a68da-d036-11e7-823c-40637f95dd7f.png)

### Current behavior:
Crash

### Expected behavior:
No Crash

**Comment by sfuchs79** [comment]
It took me some time but now I at least can reproduce this.
I had to change at least one of the two ascend rates for shallow depths (6m to surface and 50% to 6m) from my default values (3m/min and 1m/min) to higher values like 10m/min in the above screenshot to trigger the freeze.

Unfortunately I'm up to now not able to retrieve any useful debugging information.
What happens is rather a freeze than a crash and attaching gdb didn't give interesting info. But I don't have much experience in using gdb - what other command than "bt" could give useful info after one attached gdb to the frozen process?

**Comment by atdotde** [comment]
You really want to use the debugger through Qt Creator. There you can single step through the code, see variables, set breakpoints etc etc all this much easier than in the command line interface of gdb.

**Comment by sfuchs79** [comment]
I wanted to look at this again with the result that there is a chance that this issue disappeared with the latest changes in the planner. Or I'm once again too stupid to test with the correct setup....
@DennisArreborg 
Could you please check the latest Travis Continuous Build from here:
https://github.com/Subsurface-divelog/subsurface/releases

**Comment by DennisArreborg** [comment]
It runs smooth here as well!
