### ISSUE TITLE
Subsurface AppImage on Gentoo throws libgssapi_krb5.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zdavatz** [subsurface/subsurface#917]
Hi

I just tried to install Subsurface using AppImage.

Then I get the following error:
```
./Subsurface-4.7.4-x86_64.AppImage: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```
According to your description, AppImage should just work.

I am on Gentoo Linux, 64bit Kernel 4.14. wie FUSE compiled in.

Looking forward to your reply.

**Comment by dirkhh** [comment]
No idea. I don't think anyone ever tried this on Gentoo.
@probonopd - have you seen this?

**Comment by probonopd** [comment]
`usr/lib/libcurl.so.4` and `usr/lib/libcups.so.2` are pulling in Kerberos dependencies. Most people do not use Kerberos, so we might think about disabling it, hence removing the dependency on Kerberos.

For the meantime, I have [removed](https://github.com/probonopd/linuxdeployqt/commit/ff5cd2102bce70746a28446839e48a309e463fc9) `libgssapi_krb5.so.2` from the blacklist in `linuxdeployqt` so that it gets bundled into the AppImage, so the next builds should fix this.

**Comment by zdavatz** [comment]
Ok, cool, thank you. Let me know when I can test again. BTW, which C++ buildframework do you use for distributing Subsurface binaries?

**Comment by probonopd** [comment]
@zdavatz CMake, as can be see in https://github.com/Subsurface-divelog/subsurface/blob/master/scripts/linux/travisbuild.sh.

**Comment by probonopd** [comment]
@TheAssassin wrote [here](https://github.com/desktop/dugite-native/issues/42#issuecomment-352253495):

> Since libcurl is built to support a variety of protocols, it can be annoying to have to bundle all those libraries as well. Also, as part of the series https://github.com/AppImage/AppImageKit/wiki/Desktop-Linux-Platform-Issues, the CA chain is located in different places on all platforms. libcurl solves the issue by having the user specify the location on configure time. To fix this issue and also reduce the amount of dependencies, I started to build my own packages on OBS, based on the Debian ones, patched to support only HTTP(S) and search for the certificate location on runtime.
> 
> Check out https://build.opensuse.org/package/show/home:TheAssassin:AppImageLibraries/curl-httponly. Use like https://github.com/AppImage/AppImageUpdate/blob/rewrite/resources/bootstrap-container.sh#L8-L10. The packages should upgrade fine on Debian based systems. The package has been forked from the latest available unstable package.

**Comment by elbaulp** [comment]
@zdavatz How did you installed AppImage on Gentoo? I can not find any documentation about it.

**Comment by probonopd** [comment]
@elbaulp applications shipped in AppImage format do not need to be installed. Just make executable and run.

https://docs.appimage.org/introduction/quickstart.html#ref-how-to-run-appimage

**Comment by elbaulp** [comment]
Silly of me... I read that section of the docs, but still though I had to install something in order to run it...

Thanks

**Comment by TheAssassin** [comment]
@elbaulp if you think the section needs some clarification with regards to that, please feel free to open an issue and/or send a PR.

**Comment by elbaulp** [comment]
@TheAssassin Nop, its perfectly clear, was my fault :-)
