### ISSUE TITLE
iOS: Faulty navigation after aborted dive edit

### ISSUE THREAD

**Issue by fedMasias** [subsurface/subsurface#932]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When (improperly) aborting an edit, the navigation allows users to return to the dive list, but does not allow a user to view another dive, until the user properly aborts the edit. 

Sent to the mailing list, and at least one other person can reproduce the error.

### Operating system:

Tested on an iPhone 7 running 11.1.2, and an iPad mini running 9.3.5

### Subsurface version:

Running iOS beta 2.0.1 (4.7.4.280) pushed via TestFlight

### Steps to reproduce:

- Open dive from list
- Attempt to edit dive
- Abort the edit by clicking "dive list" at the top navigation bar (FWIW, I've not actually changed anything in the dive)
- Return to list
- Attempt to select a new dive, dive is highlighted but does not open

### Current behavior:

Attempts to select a new dive fail until the original edit is aborted properly (by clicking the original dive in the top navigation bar).

### Expected behavior:

Either don't allow users to abort via the "dive list" button, or make it so that either "dive list" closes the editor, or selecting a new dive aborts/saves the previous changes.

### Additional information:

I've made a video of the problem:
[gfycat link](gfycat.com/gifs/detail/HandsomeTerribleFrenchbulldog)

**Comment by mfbernardes** [comment]
Thanks for writing the report. I can reproduce the error.

About the same happens if you start adding a dive and instead of canceling just click dive list or menu and move to another page.
