### ISSUE TITLE
mobile: edit dive date does not save

### ISSUE THREAD

**Issue by janmulder** [subsurface/subsurface#949]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Edit dive date does not save. Data is unchanged.

### Subsurface version:
What version of Subsurface are you running?: latest master!-- Describe the issue in detail. -->
Does the same happen on another Subsurface version? probably yes. code is untouched for long time
Are you using official release, test build, or compiled yourself? self compiled
Provide Git hash if your are building Subsurface yourself.  375490dfc9dddb01b

### Steps to reproduce:
mobile: edit dive date, and save

### Current behavior:
No errors, but no save.

### Expected behavior:
saved change and divelist re-sorted

**Comment by janmulder** [comment]
Hmm. Even a developer can be confused. I tested this by just editing an existing date to (for example) one month earlier. And did not look to the log/console output ... which shows "unable to parse date 11/01/17 11:46 A.M. with the given format  MMM d, yyyy h:mm AP". The given format comes from the preferences, and this is not honored by the mobile app (another problem?). Then, reading the code ... oh boy ... the comments are "what a pain", "stupid Qt" and "WTF" :-) I seemed to have stept on a true minefield.

Back to thinking how to proceed here ...

**Comment by janmulder** [comment]
Just to document another curiosity. Manually add a dive. Notice that the date field is filled in with the current date/time formatted according to the preferences. Save this (sparsely filled) dive. And see that the console prints a unable to parse date message. But in the dive list the dive shows up with a correct date.

**Comment by dirkhh** [comment]
Hey at least we are consistent in being inconsistent.
:man_facepalming: 

Are you looking into that or do you want me to add it to my list?

**Comment by janmulder** [comment]
Its low on my list ... editing a dive date is something that I hardly ever do, and that holds probably for a lot of people, as this issue has been unreported for a long time.

That the date format not coming from the preferences on mobile, is higher on my list. As I have my mobile in English, and have US dates as well due to that ... that I do not like.

**Comment by janmulder** [comment]
@dirkhh: I see on the device, that in the Subsurface.conf file, there is no data for the [Language] block, so on mobile, the date/time setting is always coming from the device. Is this intentional, or just (poor) implementation? 

And added the lines on mobile manually (obviously root access is needed), and that works correctly. Still a parsing issue on editing. And I do understand why the initial add of a dive just works (without date/time parsing problems). There is no parsing in that case, and the date/time is filled from the system clock.

**Comment by dirkhh** [comment]
Back when we started Subsurface-mobile we felt that it would be smart to just use whatever language the device is running and not add too many config options.

**Comment by janmulder** [comment]
I now remember the discussion over minimal config options in the mobile app, and agree on this. The described bug is fixed without changing anything to this preferences strategy.

**Comment by janmulder** [comment]
But ... keep thinking over the settings/preferences stuff. We have (on linux and Android, and probably other plaforms too) Subsurface.conf, independent of cloudstorage, but we also have a 00-Subsurface sitting in the cloud account (so shared between devices, attached to that account). That file has some settings data, but it is unclear to me, what functionality is intended with it.

**Comment by dirkhh** [comment]
We have a few settings we want to share between desktop and mobile. Those go into 00-Subsurface

I will NOT claim that this is well designed, well thought through, consistently handled, etc.
As we all know, a lot of this is a hack on top of a kludge made to quickly fix a problem without fully thinking through the consequences.

So always feel welcome to challenge assumptions here. My comment on all this is usually to reflect on my / our thinking that got us to where we are. Sometimes I feel fairly strongly that those assumptions are correct (I don't want a ton of settings options on mobile, for example), in other cases this is just for historic reasons and changing it would be the right thing to do.

E.g. in this case... we could indeed write the language / unit prefs into 00-Subsurface because it's a reasonable assumption (IMHO) that the user wants this consistently everywhere...
