### ISSUE TITLE
4.7.5 just updated and map window no longer shows up

### ISSUE THREAD

**Issue by sikgerar** [subsurface/subsurface#978]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I just updated to 4.7.5.
the map window does no longer show anything (grey filling).

### Operating system:

xubuntu 
uname -a
mycomputer 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Subsurface version:

i used to run 4.6
I just updated to  4.7.5.

### Steps to reproduce:

update to 4.7.5
select view window-> all

### Current behavior:

no longer have a map window with a map to pick up locations or see locations

### Expected behavior:

see map

**Comment by janmulder** [comment]
Can you run run subsurface from the console using command line option -v. That way we might see what is going on, and paste the output here.

**Comment by sikgerar** [comment]
its probably a module qtquick installed, based on the log.

```
Subsurface v4.7.5,
built with libdivecomputer v0.6.0-devel-Subsurface-branch (db70c581a621814feb881494c890ae8a49da709a)
built with Qt Version 5.5.1, runtime from Qt Version 5.5.1
built with libgit2 0.26.0
validateGL(): created OpenGLContext.
validateGL(): obtained QOpenGLFunctions.
validateGL(): detected OpenGL version 3.0.
added supported DC:  Suunto   Solution
[...]
added supported DC:  Cochran   EMC-20H
Plugins Directory:  QDir( "/usr/bin" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
qrc:/MapWidget.qml:2:1: module "QtQuick" version 2.6 is not installed
QUrl("qrc:/MapWidget.qml") failed to load with status: 3
qrc:/MapWidgetError.qml:2:1: module "QtQuick" version 2.6 is not installed
loading dive data from ("/home/gerardo/.subsurface/gerardo.xml")
Set the current dive site: 0
Set the current dive site: 0

File locations:
...
```

shouldnt it be installed by default?
I had it working on 4.6

**Comment by dirkhh** [comment]
Interesting. Qt 5.5.1 for both build and runtime, so we have consistent Qt.
We may have revved the QtQuick version too far in f3d978b8a5fb6511aa0c1c611cf9b0394fdc125b @janmulder - If we want to support Qt 5.5 we can't go past QtQuick 2.5

**Comment by janmulder** [comment]
Yes, that commit to 2.6 is highly likely the reason ... but that said 5.5.1 was released in October 2015 ... So the big question is here ... do we really want to support 5.5 any longer? I bet there is a massive amount of other things like Bluetooth not working there.

**Comment by sikgerar** [comment]
so I guess it will be fixed on a next release?
should I jump back to an older release to have it working? 
I will probably not do it right now, can wait until it is fixed since I already updated all my ddbb until next summer, but I would like to see it working again in the future.

[offtopic]
btw, is there any plans to do some more integration with google maps on the android/iphone apps?
I would love to see the same map with the diving sites layer on the android app..
[/offtopic]

**Comment by dirkhh** [comment]
@sikgerar the maps in Subsurface 4.7.5 are different from 4.6 - that's one of the major changes.
Except that you don't see them :(
I don't know what you mean by "the same map with the diving sites layer" - can you explain?

@janmulder we have to be careful how aggressively we abandon distros. It's nearly impossible for normal users to update their Qt Version.

Yes, it would be much better if the users updated their distros, but...

**Comment by sikgerar** [comment]
thank you guys for the explanation. I will wait for the new version to get the maps working.

@dirkhh it would be great to have a button on the app to open a google maps/earth window with ALL the saved locations, as you can do on the computer, and not just one location (as it can be done already on the app).
I spoke about a "layer" as I though you would think on how google maps treats groups of locations. just forget about that.

**Comment by sikgerar** [comment]
fixed on 

Subsurface v4.7.6,
built with libdivecomputer v0.7.0-devel-Subsurface-branch (8ae735a4d70307ebe2a42d315697f02ce71dbe88)
built with Qt Version 5.5.1, runtime from Qt Version 5.5.1
built with libgit2 0.26.0

thank you guys
